### ISSUE TITLE
Hub v1.0 RC1 feedback enhancement suggestions

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-desktop#1056]
Below 5 screenshots with userfriendly enhancement suggestions. 
![image](https://user-images.githubusercontent.com/20902562/42930911-980f3eac-8b3e-11e8-9895-37b7f40cce1b.png)
![image](https://user-images.githubusercontent.com/20902562/42930922-9d7c1a72-8b3e-11e8-85be-f605f2dc7f04.png)
![image](https://user-images.githubusercontent.com/20902562/42930929-a04a8874-8b3e-11e8-8f40-ddaec81ff3a8.png)
![image](https://user-images.githubusercontent.com/20902562/42930934-a2b6151a-8b3e-11e8-97bd-f44555bcf47a.png)
![image](https://user-images.githubusercontent.com/20902562/42930941-a5ce3b9c-8b3e-11e8-975a-89cb9ec40658.png)

**Comment by reyraa** [comment]
Thanks for opening this issue.
This issue is now obsolete. We must have overlooked it. But the design is now completely different.
