### ISSUE TITLE
Adding Trezor and Trezor account paths

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-desktop#1192]
Trezor firmware and their libraries are almost ready for Lisk. I suppose it will be added as login option in Lisk Hub. Therefore, I propose that Lisk "accounts/addresses" shall be derived from
```
m/44'/134'/n'

m/44'/134'/0'
m/44'/134'/1'
m/44'/134'/2'
```
and so on

Additionally if requested, second signature shall be added from different account path, respectively
```sh
m/44'/134'/n'/0'

m/44'/134'/0'/0'
m/44'/134'/1'/0'
m/44'/134'/2'/0'
```

If needed, here is very simple wallet manager with implemented aforementioned solution https://github.com/karek314/LiskTrezor-CLI-wallet-manager

**Comment by ManuGowda** [comment]
This feature was implemented in Lisk Desktop 2.1.0, users can `enable custom derivation path` option in settings to use this feature.
