### ISSUE TITLE
Provide guideline for redux state 

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-desktop#1254]
### Expected behaviour
There should be several .md files documenting the different stores lisk-hub application uses. 
- which store is accountable to keep which information, 
- which actions and middlewares interact with which store fields. 

- which possible improvements could be done to the current code base to better split accountabilities between stores and shared data.

### Subtasks
- login *medium - Mike
- list and send transactions *medium - Pablo
- list delegates and vote *medium - Mike
- search (with or without login) *medium - Pablo
- price chart and newsfeed *medium - Mike

**Comment by reyraa** [comment]
We already have [these documents](https://github.com/LiskHQ/lisk-desktop/blob/development/docs).
