### ISSUE TITLE
Implement direct link to account tabs

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#1400]
### Description of the problem

There is no way to link directly to a specific tab (e.g. "Account info") of account page (e.g. `/explorer/accounts/10234607838418491979L`) 

### Suggested solution

It should be possible to specify the active tab with a search param in the URL:
All: `/explorer/accounts/10234607838418491979L?tab=all`
Incomming: `/explorer/accounts/10234607838418491979L?tab=in`
Outgoing: `/explorer/accounts/10234607838418491979L?tab=out`
Account/Delegate info:`/explorer/accounts/10234607838418491979L?tab=info`
The same should also work in wallet:
e.g.:`/wallet?tab=info`

**Comment by reyraa** [comment]
Closed in favor of #2993
