### ISSUE TITLE
Merge network switcher into the network indicator

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#1406]
### Description of the problem

Right now 
1) There is no way to change the network without going through login or signup process.
2) It is unclear in what network your action will take effect when you have network A in network indicator and network B in the network switcher when signing up or logging in.
3) Duplication which clutters ui and complicates ux
4) Two places to show the validation and connectivity errors

### Suggested solution

Merge network switcher functionality into network indicator so 
1) Network management happens in one and only place.
2) It is possible to change network in signed out mode.
3) We can verify the connectivity of the entered node when taking action to change network subsequently showing the 'green' icon or error message.
4) Changing the network should be possible only when the user is logged out, therefore Logout button should somehow visually address that logic
5) One place to show all network related errors

**Comment by reyraa** [comment]
This is already resolved.
