### ISSUE TITLE
Other Wallet - Follow a delegate account

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-desktop#1724]
### Story: As a user I’d like to follow a delegate account

We’d like to give users a possibility to follow non-delegate accounts in order to get notified about their activity.

**1.** Upon clicking “Follow Account” button users should be able to choose which notifications they’d like to recieve. The options include:

- Showing wallet activity of a given account on dashboard
- Showing delegate activity of a given account on dashboard
- Receiving notifications about given account in notification centre
- Receiving notification about delegate activity of a given account in the notification centre

**Designs:** 

**2.** Upon clicking “Confirm” the tooltip should disappear and the copy inside the “Follow Account” should change to “[checkmark] Following [down arrow]”. 

**Designs:** 

**3.** Upon clicking “Following” CTA users should be able to edit the following settings including the name and notification preferences. They can also choose to unfollow account.

**Designs:** 

**4.** When the account is unfollowed the tooltip should disappear and all the elements should go back to the pre-following state.

**Designs:**

**Comment by reyraa** [comment]
A decided to only implement bookmarks.
