### ISSUE TITLE
Implement tooltip in balance chart in Wallet

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#1747]
Subtask of https://github.com/LiskHQ/lisk-hub/issues/1676

The goal is to add the tooltip on the chart

**Comment by reyraa** [comment]
The current implementation of the balance chart is implemented wrong. It is based on time. It should be based on the transactions. meaning that It should show 20 transactions at all times (if the account has >=20 transactions.) The time/date axis is not meant to be linear. else, it’ll show stupid charts all the time

<img width="998" alt="Screenshot 2019-06-05 at 10 32 02" src="https://user-images.githubusercontent.com/666685/58942668-7d571980-877e-11e9-854d-5195dd714618.png">


This chart shows only a flat line. while the account has about 100+ transactions.

**Comment by reyraa** [comment]
This is already implemented.
