### ISSUE TITLE
Scaling on 4k monitors / fonts too small

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#1808]
On 4k the fonts are too small and the scaling could be better. There is so much left room for dynamic scaling. Lisk Hub should be dynamic and not static, in my opinion.

![grafik](https://user-images.githubusercontent.com/19614645/53897673-eff91180-4036-11e9-964d-0f71adaf3ece.png)

**Comment by slaweet** [comment]
@punkr0ck thank you for your feedback. I agree Hub is not optimized for a big screen and there is room for improvement there. I also heard that "fonts are too small" from multiple people and we will adjust some font sizes.

But I would like to better understand what are your expectations in terms of font size and scaling in a desktop aplication. The best way would be if you can post screenshots of some desktop apps you use that do the sizes and scaling well in your opinion.

I was trying to do comperison screenshot of Hub and other apps (Finder and Zeplin), and in terms of font size they are about same as Hub. Use of the space depends on how much content is there for the view at hand.

![Screen Shot 2019-03-14 at 13 59 14 (2)](https://user-images.githubusercontent.com/1254342/54359120-429f8280-4662-11e9-8754-148254a005b6.png)
<img width="1720" alt="Screen Shot 2019-03-14 at 14 00 27" src="https://user-images.githubusercontent.com/1254342/54359170-61057e00-4662-11e9-8c08-79a2fa0a1937.png">

**Comment by reyraa** [comment]
This design is obsolete.
