### ISSUE TITLE
Add "New Window" menu item to reactivate Lisk Hub main window

### ISSUE THREAD

**Issue by sdrpa** [LiskHQ/lisk-desktop#1843]
Once Lisk Hub main window is closed (when you click red x button), the only way to activate the main window again is to click Lisk Hub icon on the dock. All MacOS apps usually have "New Window" (or similar) command available in File menu as the way to activate the main window again. Currently there is no "New Window" command available in Lisk Hub so it might be confusing for a new user how to reactivate app main window without restarting the app.

**Comment by ManuGowda** [comment]
This requirement is now outdated, for now this requirement is not feasible, in future we will evaluate the wallet requirements hence closing.
