### ISSUE TITLE
Hub is overwriting port 3000

### ISSUE THREAD

**Issue by tobiaslins** [LiskHQ/lisk-desktop#1875]
### Steps to reproduce

1. Run a node application on port 3000 locally everything is working fine.  (Using docker while I tested)
2. Start Lisk Hub
3. Goto 127.0.0.1:3000 and you will see Lisk Hub (it somehow overrides the other application)

### Actual result
Lisk Hub listens on port 3000 even if the port is already in use 

### Expected result
Lisk Hub should not use "standard" ports that are often used. Use a random port instead?
#1611 #1615 seems not to fix the issue

### Version
Version 1.13.0

**Comment by slaweet** [comment]
Further info about this problem is in duplicate https://github.com/LiskHQ/lisk-hub/issues/1875
