### ISSUE TITLE
Wallet amount not recognized when copy&paste

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-desktop#1950]
Unfortunately the 'maximum amount' button is gone, so I have to copy & paste the total wallet amount again. It is only not recognized because of the comma separator in the amount.

![image](https://user-images.githubusercontent.com/20902562/56413581-48533e00-6288-11e9-8d3a-5d7a525050af.png)

**Comment by reyraa** [comment]
Already resolved by set max amount option.
