### ISSUE TITLE
Clean up login component to use login action

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#2002]
## Expected behaviour
[LoginV2 component](https://github.com/LiskHQ/lisk-hub/blob/development/src/components/loginV2/loginV2.js) should use
[login action](
https://github.com/LiskHQ/lisk-hub/blob/96432cc4675bca19619e1117ddf56142740f89d7/src/actions/account.js#L283)
instead of [liskAPIClientSet](https://github.com/LiskHQ/lisk-hub/blob/96432cc4675bca19619e1117ddf56142740f89d7/src/components/loginV2/index.js#L26).

This change will most likely allow removing all code that does something with `network`.

Also these two actions are not used anymore and can be removed https://github.com/LiskHQ/lisk-hub/blob/96432cc4675bca19619e1117ddf56142740f89d7/src/components/loginV2/index.js#L27-L28

## Current behaviour
LoginV2 uses `liskAPIClientSet`
(https://github.com/LiskHQ/lisk-hub/blob/96432cc4675bca19619e1117ddf56142740f89d7/src/components/loginV2/index.js#L26

because historically it also needed to set the active peer, but now the active peer is set by the network switcher on the splash screen, so it's enough to dispatch `login`

**Comment by sridharmeganathan** [comment]
Completed already in other ticket
