### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kencani** [LiskHQ/lisk-desktop#2006]
When I execute the third step， the instruction "npm install"，it shows :   
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN peerDependencies The peer dependency @emotion/core@^10.0.0 included from @emotion/styled-base will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^2.10.2 || ^3 || ^4 included from eslint-plugin-jsx-a11y will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
-
> cypress@3.2.0 postinstall /data/lisk-hub/node_modules/cypress
> node index.js --exec install

 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /root/.cache/Cypress/3.2.0
npm ERR! Linux 4.4.0-142-generic
npm ERR! argv "/root/.nvm/versions/node/v4.9.1/bin/node" "/root/.nvm/versions/node/v4.9.1/bin/npm" "install"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the usb@1.5.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/lisk-hub/npm-debug.log

how can i fix it?

**Comment by slaweet** [comment]
Hi @kencani ,
the problem on our side is that our README doesn't mention that the minimum node version is `8.14.0`
It's mentioned just in package.json:
https://github.com/LiskHQ/lisk-hub/blob/23e8f497bd315d88aa962ecc2b9197e6fc9f1c00/package.json#L256

Using node `8.14.0` should solve your problem.

**Comment by kencani** [comment]
> Hi @kencani ,
> the problem on our side is that our README doesn't mention that the minimum node version is `8.14.0`
> It's mentioned just in package.json:
> https://github.com/LiskHQ/lisk-hub/blob/23e8f497bd315d88aa962ecc2b9197e6fc9f1c00/package.json#L256
> 
> Using node `8.14.0` should solve your problem.

ok，thx，I will try 

> Hi @kencani ,
> the problem on our side is that our README doesn't mention that the minimum node version is `8.14.0`
> It's mentioned just in package.json:
> https://github.com/LiskHQ/lisk-hub/blob/23e8f497bd315d88aa962ecc2b9197e6fc9f1c00/package.json#L256
> 
> Using node `8.14.0` should solve your problem.

ok，thx.

**Comment by kencani** [comment]
> Hi @kencani ,
> the problem on our side is that our README doesn't mention that the minimum node version is `8.14.0`
> It's mentioned just in package.json:
> https://github.com/LiskHQ/lisk-hub/blob/23e8f497bd315d88aa962ecc2b9197e6fc9f1c00/package.json#L256
> 
> Using node `8.14.0` should solve your problem.


I tried, but there was a second problem.



npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-14T09_32_59_695Z-debug.log

**Comment by kencani** [comment]
> > Hi @kencani ,
> > the problem on our side is that our README doesn't mention that the minimum node version is `8.14.0`
> > It's mentioned just in package.json:
> > https://github.com/LiskHQ/lisk-hub/blob/23e8f497bd315d88aa962ecc2b9197e6fc9f1c00/package.json#L256
> > 
> > Using node `8.14.0` should solve your problem.
> 
> I tried, but there was a second problem.
> 
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the usb@1.5.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-05-14T09_32_59_695Z-debug.log

I slove this but when i run start ，there was a problem:
/data/lisk-hub/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! lisk-hub@1.16.0 start: `electron ./app/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lisk-hub@1.16.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-14T10_39_01_355Z-debug.log

**Comment by slaweet** [comment]
@kencani I guess you're on Linux, right? The team uses MacOS and didn't have this problem. 
On Linux, there are some dependencies you need to install https://electronjs.org/docs/development/build-instructions-linux

We should update our README with this as well. Maybe once you'll find all the problems, you can open a pull request to update our README. Or I'll do it.

**Comment by reyraa** [comment]
I'll close this due to inactivity.

**Comment by PanSzpila** [comment]
Hi! I allso have problems on Windows during "npm ci" or "npm i"
I'm installing like in readme,  have node. v12.19.0 (Currently using 64-bit executable).
I allso have read [https://www.electronjs.org/docs/latest/development/build-instructions-windows](url), and install all reqired dependencies, and nothing seems to work :(

Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\out\fs.js
- C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\out\util.js
- C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\electron-builder\out\cli\cli.js
- C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\electron-builder\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\src\fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\src\util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Lisk@3.0.0-debug.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Lisk@3.0.0-debug.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thuocupid** [comment]
> Hi! I allso have problems on Windows during "npm ci" or "npm i" I'm installing like in readme, have node. v12.19.0 (Currently using 64-bit executable). I allso have read [https://www.electronjs.org/docs/latest/development/build-instructions-windows](url), and install all reqired dependencies, and nothing seems to work :(
> 
> Error: Cannot find module 'fs/promises' Require stack:
> 
>     * C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\out\fs.js
> 
>     * C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\out\util.js
> 
>     * C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\electron-builder\out\cli\cli.js
> 
>     * C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\electron-builder\cli.js
>       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
>       at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>       at Module.require (internal/modules/cjs/loader.js:903:19)
>       at require (internal/modules/cjs/helpers.js:74:18)
>       at Object. (C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\src\fs.ts:5:1)
>       at Module._compile (internal/modules/cjs/loader.js:1015:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>       at Module.load (internal/modules/cjs/loader.js:879:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>       at Module.require (internal/modules/cjs/loader.js:903:19)
>       at require (internal/modules/cjs/helpers.js:74:18)
>       at Object. (C:\Users\pansz\Documents\Kod\Open Source Contributions\lisk-desktop\node_modules\builder-util\src\util.ts:25:1)
>       at Module._compile (internal/modules/cjs/loader.js:1015:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>       at Module.load (internal/modules/cjs/loader.js:879:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>       npm ERR! code ELIFECYCLE
>       npm ERR! errno 1
>       npm ERR! Lisk@3.0.0-debug.0 postinstall: `electron-builder install-app-deps`
>       npm ERR! Exit status 1
>       npm ERR!
>       npm ERR! Failed at the Lisk@3.0.0-debug.0 postinstall script.
>       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Did you find a solution for this?
