### ISSUE TITLE
Error in start

### ISSUE THREAD

**Issue by kencani** [LiskHQ/lisk-desktop#2009]
Hello, I asked some questions about installation before, but now I have some problems about startup. And I would like to ask if it is feasible to install according to README. md, or if there is a new installation document?

run :LISK_HUB_URL="http://localhost:8080" npm run start.
then :
/data/lisk-hub/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! lisk-hub@1.16.0 start: `electron ./app/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lisk-hub@1.16.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-14T10_39_01_355Z-debug.log

**Comment by massao** [comment]
It seems to be related to running on Linux, and not having the libgtk-3 and maybe others electron dependencies, could you try as suggested by @slaweet at https://github.com/LiskHQ/lisk-hub/issues/2006#issuecomment-492548890?

**Comment by reyraa** [comment]
I'll close this due to inactivity.
