### ISSUE TITLE
Improve the update modal user experience

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2016]
### Description
The updates popup opens without users direct action, and according to user feedback, it can be frustrating. I'd suggest we use a simple toast message to show the update, and after the user clicked on it we open the change log popup on which we provide the "update now" button. A sample of such a toaster is the one Gmail uses to inform users about the result of deleting an email:
<img width="354" alt="Screenshot 2019-05-15 at 15 31 59" src="https://user-images.githubusercontent.com/666685/57779584-a0198380-7726-11e9-96f4-eea85993baf3.png">
Which has two actions: _Undo_ and _Close_. The actions in our toast message can be _Update_ and _Close_. 

Design: https://projects.invisionapp.com/d/main#/console/17570736/369054984/preview

### Motivation 
Improve the user experience by removing the onstacles blocking their intended action. 

### Development steps
MVP
As the first step we can adapt the existing popup to the new design. I'll add a link to the design guides as soon as they're ready. #2134 

MLP
On a next step, we can Implement the banner design [here](https://projects.invisionapp.com/d/main#/console/17570736/369054984/preview), the release details popup appear when the user clicks on it. On this step we should use a React popup instead of the implementing outside the React app within a new window. #2144

Nice to have
Further, After the user clicked on the update button, a new popup can open. which draws a circular progress chart. #2145

**Comment by slaweet** [comment]
I agree that the current popup is too intrusive and should be improved.

But toasts are for something temporary that goes away after several seconds. I don't think that update notification should go away after several seconds. We got this top banner designed https://zpl.io/bLdDyP7 for notifications that should stay until the user takes an action 
<img width="1361" alt="Screenshot 2019-05-15 at 16 09 09" src="https://user-images.githubusercontent.com/1254342/57782163-f89f4f80-772b-11e9-9561-d707d20cd6ed.png">

**Comment by reyraa** [comment]
@slaweet This looks like a rainbow :-D
Updating the app is not the main action the user runs the app for. Not even one of the notable reasons. A toast would suffice. According to several users, the problem with the toast is not its location but its prominence. This is my own personal experience too. Such a huge red (or any other color) box is even more freaking than the blue popup we already have.

**Comment by slaweet** [comment]
IMO it's good that the new version notification is irritating as it urges the user to update and it's in our best interest that users are on the latest version. 

The problem with the currently implemented popup is that user has to interact with it immediately when it appears, but with the banner, the user can still finish the action started before the banner appeared and interact with the banner only afterward. 

But we can go with a toast as well, we'll just have to implement toasts that don't hide after X seconds.

**Comment by reyraa** [comment]
Implemented.
