### ISSUE TITLE
Delegate page: Uncaught TypeError: Cannot read property 'custom' of undefined

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2069]
### Steps to reproduce

1. Enable autologin
1. Open other's account page who is delegate http://localhost:8080/#/explorer/accounts/537318935439898807L  
1. It happens sometimes

### Actual result

See the screenshot
Cypress if failing because of that

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/58263948-4dbb1100-7d7d-11e9-883b-12efa492e922.png)

**Comment by sridharmeganathan** [comment]
Already addressed.
