### ISSUE TITLE
Use lisk-service to fetch the data needed to show all the votes of the account

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2122]
### Description of the problem

Now in order to show all the voted delegates at once on the Voted tab of Delegate page, we would need to make multiple delegates lists requests and implement complicated logic on the frontend.
Lisk-core wants to keep the api simple so they dont want to implement sorting by address/username.
Lisk-service would provide the needed api.

**Comment by reyraa** [comment]
Already done.
