### ISSUE TITLE
Make a COPY button for the LSK in your wallet

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-desktop#2132]
It is very annoying to retype long numbers if you want to send everything in your wallet. 
The 'max ammount' button is also gone in the 'Send' window of your wallet.  
Could you just make a simple 'Copy to clipboard' button on the top right of your wallet? 
![image](https://user-images.githubusercontent.com/20902562/59373128-50d86a00-8d49-11e9-9c8b-04841fd619eb.png)

**Comment by reyraa** [comment]
This is resolved by #2155
