### ISSUE TITLE
Align the design of Delegate stat

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2174]
Should we align to the design of stats we have in the design?
https://projects.invisionapp.com/d/main#/console/17570736/365527950/preview

**Comment by Efefefef** [comment]
@reyraa Please decide. We cant leave it like that
![image](https://user-images.githubusercontent.com/6704159/59909183-5f8ce400-940f-11e9-9498-845ee8893fb2.png)

**Comment by reyraa** [comment]
@Efefefef The design needs more thought and the API endpoints are not ready. This feature can't be released by 1.1.9.0. We have to postpone this for the future version so we have enough time to prepare the prerequisites.
