### ISSUE TITLE
Impossible to login in Hub if btc-test.lisk.io is unavailable

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2197]
### Steps to reproduce

1. Enable BTC token
1. Logout
1. Block btc-test.lisk.io
1. Login

### Actual result

Can't login because btc-test.lisk.io is unavailable

### Expected result

This problem should not prevent from logging in

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/60269180-404df500-98ee-11e9-808e-f1b37bb01121.png)

**Comment by reyraa** [comment]
@Efefefef BTC is one of the two blockchains we gather information for, if it's not available, what's the point of signing in? I think there's no difference between not being connected to internet and not having a functioning API. hence, this ticket seems invalid to me.

**Comment by Efefefef** [comment]
@reyraa Alright, agree

**Comment by slaweet** [comment]
I think it's not the top priority, but we can at least detect this situation and give a more helpful error message. I propose to show the URL without path and add some info. `Unable to connect to the node "https:/btc-test.lisk.io". If the error persists you can still use your LSK if you disable BTC in setings`
