### ISSUE TITLE
Tx details: Cant open pending transaction

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2210]
### Steps to reproduce

1. Send some money to somebody
1. Click on tx while it sill pending

### Actual result

404 page

### Expected result

Tx details page

**Comment by slaweet** [comment]
Note that the API util already tries to fetch unconfirmed transactions https://github.com/LiskHQ/lisk-desktop/blob/c1f9af55ec87c0e1ea5928b29c0ab9dd507c027c/src/utils/api/lsk/transactions.js#L89-L92

I just tested it and it worked for me.

**Comment by reyraa** [comment]
This is already fixed.
