### ISSUE TITLE
Update trezor.js file in electron side

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk-desktop#2226]
In the electron side the **app/src/trezor.js** file needs to be refactor.

At this moment this file is using the **trezor.js** library, what is deprecated [trezor.js](https://www.npmjs.com/package/trezor.js-node) and the library that we need to use instead is [trezor-connect](https://github.com/trezor/connect).

Because of this change we need update and refactor the trezor.js file is being use in the project to communicate properly with the hardware wallet.

The trezor.js library is used in the app/src/trezor.js file in the following parts.

**Line 14:**
```
const trezor = require('trezor.js'); // eslint-disable-line import/no-extraneous-dependencies
```

and then use the method DeviceList in **Line 27**:
```
const list = new trezor.DeviceList({ debug });
```

After we get the trezor instance, this instance is in use in the following places for different executions.

**Line 102**, is the function that is on charge of detect a new trezor device.
```
list.on('connect', (device) => {
```

**Line 151**, function on charge of detect error related the connection.
```
list.on('error', (error) => {
```

**Line 159**, function on charge of the unacquire device
```
list.on('connectUnacquired', (device) => {
```

Line 226, inside **executeTrezorCommand** function
```
const tDevice = list.asArray().find(d => d.features.device_id === device.deviceId);
```

The **executeTrezorCommand** function is the most important as in that function is where all the events related the wallet take place like **GET_PUBLICKEY**, **GET_ACCOUNT**, **SIGN_MSG**, **SIGN_TX**

This is a big function and needs to be refactor.

### After remove trezor.js and import trezor-connect.js

All the functions mentioned before on each line need to be remove or update to use the new syntax.

Here is one example that can be follow as a guide to use the new functions [trezor-connect-electron](https://github.com/szymonlesisz/trezor-connect-electron-boilerplate).

You can check the src/index.j**s file where is all the trezor logic**

**Comment by ManuGowda** [comment]
After careful considerations, we have made a conscious decision to remove support for Trezor in Lisk Desktop. 
Marketing team will do the detailed communications in coming weeks.
