### ISSUE TITLE
cannot copy and paste total LSK amount

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-desktop#2234]
The 'send max' button is gone. Now I have to copy and paste the total amount of LSK in my wallet and deduct 0.1 lsk. 
Since the format is not  compatible it doesnt work. Please make the decimal notation the same.

![image](https://user-images.githubusercontent.com/20902562/61198512-a1413f80-a6da-11e9-9c2b-c7f571b7d27a.png)

**Comment by reyraa** [comment]
This is already resolved by adding the set max amount option.
