### ISSUE TITLE
System to prevent typos from Hub and Mobile

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2239]
System to prevent typos from Hub and Mobile.

**Comment by slaweet** [comment]
One way to prevent typos would be to use a translation management system (we used https://lingohub.com/ for https://github.com/LiskArchive/lisk-nano in the past) and treat English as one of the translations, (German as another translation in the future) and don't have the user-facing strings in the code. 

In the translation management system each string than can go through a review process (by someone outside of the dev teeam) which is focused just on the copy, to make sure there are no typos or other problems.
