### ISSUE TITLE
Generalize toolbox components

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2245]
### Description
Desired is that all the components in shared directory have a reasonable level of generalization so they are ready to be used by several HOC. 
Components must be well documented in order to make it easy and accessible for developers to use in future and prevent code duplication.

### Dependency
This ticket must be started after #2287.

### Acceptance criteria
todo

**Comment by slaweet** [comment]
Some ideas for toolbox component improvements:
- Create <ButtonGroup direction={vertical|horizontal} /> component
- Create <Form />, submit by enter; unify Send, Request, Bookmark, Login, RegisterDelegate, FilterTransactions, 2ndPassphrase in SummaryStep,
- Create <Label /> and <Value /> component to use in transaction summary, transaction details, deleagte details, etc.
- Create <BoxEmptyState /> component to use in transactions, transactionsFiltered, walletVotes, walletVotesFiltered, delegates, delegatesFiltered, delegatesVoted, bookmarks, bookmarksFiltered
- Add autofocus prop to Input component <Input autofocus /> and use where appropriate
- Create <AvatarNameAndAddress /> to use in wallet, delegates, bookmarks, dashboard
- Create <Box.Header /> <Box.Footer /> <Box.Content /> components and use where needed
- Change <Tabs /> to <Box.Tabs /> as it is dependent on being in Box header
- Create new prop: <Box isLoading={true}>  and use it in Delegates, Votes, Transactions, NewsFeed, RecentTransactions
- Use <DropdownButton /> in Request, Bookmark, FilterTransactions, Search, Account, NetworkSwitcher,
- Create new prop: <Box narrow /> max-width: 720px; unify TxDetail, Send, Vote, Register2ndPass, RegisterDelegate, Bookmarks, AddBookmark
- Create new prop: <Box main /> min-height: 600px; Transactions, Votes, Delegates, Bookmarks, Newsfeed, Send, Vote
- Create <Box.Row /> component (with hover, paddings and border-bottom gray line)

**Comment by slaweet** [comment]
There are already these tickets that contribute to the goal of this epic: https://github.com/LiskHQ/lisk-hub/issues/2001 https://github.com/LiskHQ/lisk-hub/issues/2128 https://github.com/LiskHQ/lisk-hub/issues/2091 https://github.com/LiskHQ/lisk-hub/issues/2098
