### ISSUE TITLE
[Trezor]Can't find the [Sign in with hardware wallet] link at the second sign in.

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-desktop#2252]
### Steps to reproduce

Please carry out this operation faithfully. 
You can understand what I want to fix.

1. click [Sign in with hardware wallet] link
![01](https://user-images.githubusercontent.com/14948578/61466995-d937d380-a9b5-11e9-8b1e-72985f570cf9.png)
2. Sign in with Trezor
![02](https://user-images.githubusercontent.com/14948578/61467019-e81e8600-a9b5-11e9-9977-9b250fa51a2a.png)
3. Sign out the wallet
![03](https://user-images.githubusercontent.com/14948578/61467046-f1a7ee00-a9b5-11e9-8244-690c77c45ec0.png)

4. 

**I WANT TO SIGN IN WITH TREZOR AT THIS TIME** 

![04](https://user-images.githubusercontent.com/14948578/61467072-fb315600-a9b5-11e9-9bd4-9ab8da981ab5.png)

5.Can't find the  [Sign in with hardware wallet] link
![06](https://user-images.githubusercontent.com/14948578/61467225-3764b680-a9b6-11e9-9db0-05c31f424a7c.png)
 

### Actual result

Only Trezor account,
Can't find the [Sign in with hardware wallet] link at the second sign in.

Of course,
I can click the [ Go Back] link to go the [Welcome to Lisk Hub!] Page
However,
This operation is very very wasteful.

### Expected result

![05](https://user-images.githubusercontent.com/14948578/61466825-8bbb6680-a9b5-11e9-8795-4148f82abacb.png)

### Version
Lisk Hub 1.19.0-rc1

**Comment by Efefefef** [comment]
Totally agree here

**Comment by reyraa** [comment]
The design has been updated. this ticket is not valid anymore.
