### ISSUE TITLE
Hub should display the IP / URL of custom node

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-desktop#2255]
@punkr0ck commented on [Fri Jul 19 2019](https://github.com/LiskHQ/lisk-sdk/issues/3982)

If I connect to my custom node https://lisk-api.punkrock.me Lisk Hub (1.19.0) shows "Connected to Mainnet". It should show the IP or the domain, depending on what a user entered because there is no visible difference now between official node and custom node.

**Comment by reyraa** [comment]
We have a goal set which will have dedicated design and tickets.
