### ISSUE TITLE
Create and use central Test mocks for transactions, delegates, votes, etc.

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#2256]
## Current behavior
We have central test mocks for accounts
https://github.com/LiskHQ/lisk-hub/blob/development/test/constants/accounts.js and some other data, but not for transactions, delegates, votes, etc.

## Expected behavior
We should have central test mocks for all data we use from the REST API (transactions, delegates, votes, ..) and use those in all unit tests that need to use the data from the REST API.

**Comment by reyraa** [comment]
Already done.
