### ISSUE TITLE
Bookmarks synchronization 

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2292]
As a user; I'd like my bookmarks to be available through different devices. 

### Motivation
This feature improves usability by enabling users to use the same bookmark list for a single account through multiple devices.

### Acceptance criteria
 - Bookmarks must be stored on a per-account basis.
 - Bookmarks must be encrypted before storing them.
 - Users should be able to choose to store their bookmarks locally or online.
 - Users must receive proper onboarding regarding this feature.
 - If this option is enabled, the application must automatically retrieve the bookmarks from the online service.

### Description
To give the users the option to retrieve their bookmarks on different devices, we should provide the option to store the bookmarks on a central service. We should clearly explain it to users that by enabling this option, they are using a centralized service. 
In order to keep the data safe, we should encrypt the bookmarks object before storing it. Users must be able to retrieve their bookmarks on Hub and Mobile.
If users decide not to use this service, we should store their bookmarks locally as we do at the moment.
The bookmarks must be stored on a per-account basis.

**Comment by slaweet** [comment]
This looks like a duplicate of https://github.com/LiskHQ/lisk-desktop/issues/2462

**Comment by reyraa** [comment]
We decided not to take this direction.
