### ISSUE TITLE
HW: Disconnecting Ledger S while logged in with Trezor T logs you out

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2295]
### Steps to reproduce

1. Connect both types of HW
1. Login with Trezor T
1. Disconnect Ledger S

### Actual result

You are logged out

### Expected result

You see the popup saying Ledger S was disconnected and you stay logged in 

### Version

1.19.0, 1.19.1

**Comment by Efefefef** [comment]
Note: Disconnecting Trezor T while logged in with Ledger S works as expected

**Comment by reyraa** [comment]
This is not a practical situation. We support only one account, meaning that you only need to connect one HW. Plus, I can't think of any real world need for connecting two HW at the same time. Yet in the worse case, you just need to sign in again using the HW you need at the moment; which takes just a few seconds.
