### ISSUE TITLE
Lisk Balance Graph broken data

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-desktop#2308]
### Steps to reproduce

1. Open Hub
2. Sign in
3. Navigate to your account or someone else that has a considerable amount of tokens

### Actual result

Graph that shows hours/time below, and they are all condensed/crowded.
<img width="1395" alt="Screenshot 2019-08-02 at 11 48 58" src="https://user-images.githubusercontent.com/45934100/62369526-2f695280-b530-11e9-9f1b-4521ca138625.png">

### Expected result

Show the amount/balance on the right and the month on the bottom row.

<img width="1051" alt="Screenshot 2019-08-02 at 14 18 29" src="https://user-images.githubusercontent.com/45934100/62369614-6c354980-b530-11e9-8321-f24812840a01.png">

### Version

Hub 1.19.1

**Comment by reyraa** [comment]
I'd suggest we use a more intelligent approach to show the horizontal labels. 
If the last 20 transactions (or all if less than 20) has been created in range of:
 - over a year, we show month acronym and year in `mmm yy` format.
 - between 6 month and 1 year, we show only month acronyms in `mmm` format.
 - between 6 days and 6 month, we show 6 equally distributed days.
 - less than 6 days we show date in `mmm dd`.

**Comment by reyraa** [comment]
ChartJS has [a method](https://www.chartjs.org/docs/latest/configuration/legend.html#html-legends) that allows you generate custom legend.

**Comment by slaweet** [comment]
I was looking for and example of how generating custom legend in ChartJS works and found this https://codepen.io/anon/pen/opzdZo

Based on that demo, I think it cannot do what we need. We need custom `label` not `legend`

<img width="620" alt="Screenshot 2019-08-05 at 17 16 24" src="https://user-images.githubusercontent.com/1254342/62475347-29c87280-b7a5-11e9-82d5-da9ba22a08d1.png">
