### ISSUE TITLE
Prompt users to give feedback

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#2315]
As a developer/PO of Lisk Hub; I'd like to hear more feedback from users so that I can better understand what to focus on and how implemented features are used. 

### Motivation
This feature will allow us to better understand user needs, better prioritize what to work on and how features should work. It will also allow us to have continuous metrics (e.g. net promoter score, number of reported UX glitches) of how happy are the users with the product. This will allow us to evaluate if a new feature improved user satisfaction or not.

### Description
A banner that looks like this should be displayed in conditions described below

![Screenshot 2019-08-06 at 09 12 21](https://user-images.githubusercontent.com/1254342/62518645-52468000-b82a-11e9-81cf-ec499aa9996e.png)

### Acceptance criteria
- A feedback banner is displayed if user used the app for at least X amount of time. X can be 1 week?
- The banner says `How is your experience of using Lisk Hub? Help us improve it by sharing your thoughts.` (to be reviewed by a native speaker)
- The banner contains a link to feedback form - same link as in account dropdown
- The banner is displayed until the user closes it.
- When the user closes the banner, Hub will remember the current date when it was closed, so that in the future we can implement functionality to show the banner again after Y months.

**Comment by reyraa** [comment]
We decided not to take this direction.
