### ISSUE TITLE
Update Electron to latest version

### ISSUE THREAD

**Issue by massao** [LiskHQ/lisk-desktop#2380]
There are some divergences when rendering the app inside electron and in the Browser, such as the ones in #2370, updating to the latest version seems to solve the rendering differences.

For updating Electron to `6.0.3`, it may be needed to update the electron dependencies on: https://github.com/LiskHQ/lisk-hub/blob/fa6b4f20f8ca83083e3da9af6305e40da870ad0f/app/package.json#L15-L17

**Comment by sridharmeganathan** [comment]
Addressed in #2828
