### ISSUE TITLE
[Lisk Balance]graph should not be updated due to changes in transaction tab

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-desktop#2386]
### Steps to reproduce

1. Sign in to the LiskHub. 
2. Click the [Wallet] tab.
3. Please focus on the [Lisk Balance] and [transaction] tab.

### Actual result

The Lisk Balance graph changes whenever you change the transaction tab.

**Case 1:All transaction**
 All status is correct!
![1](https://user-images.githubusercontent.com/14948578/63450832-d715d880-c47d-11e9-8afc-65cb092d8d67.png)

**Case 2 : Incoming transactions**
 Transaction is correct.
 However,Lisk Balance graph start under zero.

![2](https://user-images.githubusercontent.com/14948578/63450842-e3019a80-c47d-11e9-80fb-524b88b93397.png)

**Case 3 : Outgoing transactions**
 Transaction is correct.
 However,Lisk Balance graph goes down to zero.

![3](https://user-images.githubusercontent.com/14948578/63450846-ea28a880-c47d-11e9-96ce-8140d5867f68.png)

### Expected result

[Lisk Balance] graph should be always shown the correct balance.

So,[Lisk Balance] graph should not be updated due to changes in transaction tab.
It should always shown the value at [All transaction] choice is.

### Version

LiskHub : 1.20.0-beta.1
OS: Windows 10 Home 1903 build 18362.295 Japanese

**Comment by reyraa** [comment]
Fixed by #2862
