### ISSUE TITLE
BTC: Tx details: Recipient of tx with several outputs is not properly handled

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2394]
### Description of the problem

If I open this transaction details in testnet as a genesis address: mkakDp2f31btaXdATtAogoqwXcdx1PqqFo
I see the tx from 2Myf3fLXAJDXg8MBfX14vqrbdXWcrq56vrh to 2N53UATYsvmpAr9pauNM3tpbxTbToQfsP6i
https://jenkins.lisk.io/test/lisk-hub/PR-2368/#/explorer/transactions/5305099e8e5cb93bdb18257fa83988d70a7f11de107ae42411491d86b0cecf30
Which is the other part of the transaction
https://tbtc.bitaps.com/5305099e8e5cb93bdb18257fa83988d70a7f11de107ae42411491d86b0cecf30
Faucets pay to many outputs, instead of creating single transactions - this saves on the fees
It looks like we did not consider this use case

### Suggested solution

Show all recipients and amounts

**Comment by ManuGowda** [comment]
With the removal of BTC https://github.com/LiskHQ/lisk-desktop/issues/3928, this issue is no longer valid to be considered for development/bugfix.
