### ISSUE TITLE
Requires hard refresh viewing new accounts when connected to Devnet SDK

### ISSUE THREAD

**Issue by RachBLondon** [LiskHQ/lisk-desktop#2396]
### Steps to reproduce

1. Connect Hub to a local devnet
2. Search for an address  which is different to the account you logged-in to view

### Actual result
The balance will be that of the account you were previously viewing, not the address you should be viewing. Hard refreshing Hub `command`+ `r` OSX fixes the issue.

### Expected result
The balance should be accurate to the account you are viewing.

### Version
Version 1.19.1 (1.19.1)

**Comment by Efefefef** [comment]
Cant reproduce in 1.20.0

**Comment by reyraa** [comment]
Already resolved.
