### ISSUE TITLE
Display the list of latest blocks

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2455]
### Description
As a user I'd like to browse the blocks in an orderly list. I'd like to be able to navigate through the history of blocks and see the details of each block, including the list of transactions that each block adds to the blockchain.

 - Implement the list of blocks in a dedicated screen.
 - Implement the filters and sorting on the latest blocks.
 - Implement the details of the block on a dedicated page (excluding transactions list).
 - Implement the list of transactions of the block on the block details page.
 - Implement the _load new blocks button_.

**Comment by sridharmeganathan** [comment]
Planned work is completed and released.
