### ISSUE TITLE
Display a summary of DPoS and delegates

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2457]
### Description
As an advanced user; I'd like to get a summary of key DPoS values, such as
- Total forged LSK.
- list of next forgers.
- the last delegate who forged a block.
- Number and proportion of missed blocks.
- List of new delegates.
I'd like to see the list of latest votes, specially the ones with high LSK values in their account.
Graphs can help illustrate the concepts.

**Comment by sridharmeganathan** [comment]
Duplicated in ##2624
