### ISSUE TITLE
Implement the load new transactions button

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2513]
### Description
We'd like to display a button on top of the list when there are new transactions to be shows. In order to not distract users, we don't want to update the list automatically.

### Acceptance criteria
- The button should slide down from beneath the list header when there are new transactions.
- The button should slide up to its initial state when the user clicked on it.
- The new transactions attach to the top of the list with no animation.

**Comment by slaweet** [comment]
https://github.com/LiskHQ/lisk-desktop/issues/2510#issuecomment-551131432 is relevant also for this ticket
