### ISSUE TITLE
Login option for hardware wallet on alternative login page missing

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2564]
When Hub is already opened and you are logged into your account, then clicking "Sign Out" in the top right menu, log back in, then the login screen doesn't offer the option to login with your Hardware Wallet again.

![grafik](https://user-images.githubusercontent.com/19614645/67010881-d0f34f80-f0ee-11e9-94b2-daa4dacb2a62.png)

**Comment by reyraa** [comment]
The design is already changes. This issues is resolved.
