### ISSUE TITLE
Find a better subtitle for the wallet page

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-desktop#2566]
### Actual result
the subtitle of the wallet and the dashboard page are exactly the same.

### Expected result
Each page should have a unique subtitle that explains the functionality of the page.

**For Delegates**
Vote for who secures the network or becomes a delegate

**Wallet**
Send, request and manage your LSK tokens

**Comment by sridharmeganathan** [comment]
I received the text from Kathryn and same as been updated
