### ISSUE TITLE
Lisk Hub forgets names of Hardware Wallets (Trezor T)

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2582]
I am not sure if it is after a restart or if it also can happen after several restarts of Hub with some time between each session but I noticed this several times now. Lisk Hub forgets the names sometimes.

OS: Win 10
Lisk Hub: 1.22.0-rc.1

![grafik](https://user-images.githubusercontent.com/19614645/67504656-1208d800-f68a-11e9-83e5-5662280a57b0.png)

**Comment by ManuGowda** [comment]
This issue has been resolved with latest release.
