### ISSUE TITLE
Change default input view for verifying messages

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2608]
When signing a message you get code in one block but the default view isn't made for that. So, you should switch to "block-input-view" as default:

![grafik](https://user-images.githubusercontent.com/19614645/67967494-f8294100-fc05-11e9-8735-51f4eadca730.png)

**Comment by reyraa** [comment]
@jooltr what do you think?

**Comment by jooltr** [comment]
@reyraa makes sense. Thank you Ali!!

**Comment by reyraa** [comment]
The default button must be the raw form and its icon must be the first one from left.
