### ISSUE TITLE
Clicking lisk://-links always opens a new session / instance of Lisk Hub

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2609]
Not sure if it is wanted or not but if you click several times on `lisk://`-links (at least lisk://sign-message and lisk://verify-message) a new Lisk Hub session opens instead of using the already opened one. In my opinion this can get very messy and it should check if Lisk Hub is already running and use it instead of opening a new session / instance.

**Comment by slaweet** [comment]
I just tested it on macOS and couldn't reproduce. So I assume it's platform-specific.

Please share on which OS is this happening for you, @punkr0ck.

Thank you for your feedback.

**Comment by punkr0ck** [comment]
OS: Microsoft Windows 10 Pro
Version: 10.0.17763 Build 17763
