### ISSUE TITLE
Inform users about sign/verify message feature

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2612]
### Description
As a user; I'd like to be informed about new features. The recently released sign/verify message is a good example for this.

### Motivation
Help users make best use of existing and recently introduced features.

### Acceptance criteria
- A banner should appear after user navigates out of sign-in by signing in or exploring as a guest.
- The banner is titled: Now you can verify the validity of a sign messages directly through Lisk Desktop.
- There should be a button titled "Got it" to simply discard the banner.

**Comment by punkr0ck** [comment]
More important would be to tell users **how** they can sign and verify messages. Those features are not _directly_ accessible from Lisk Desktop.

**Comment by reyraa** [comment]
These options have been added to top menu. We concluded showing notifications for each new feature is not a good UX.
