### ISSUE TITLE
Add dark mode version of illustration to the app

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-desktop#2648]
### Description
The current set of illustrations are not ready for dark mode. the design team have provided us with new illustrations which suit both themes. we need to replace these assets and ensure everything works fine.

**Comment by slaweet** [comment]
There is already one icon implemented with dark mode here:
https://github.com/LiskHQ/lisk-desktop/blob/531f20fa4cead114595e2656ed4c84a373365187/src/components/shared/header/topBar/topBar.js#L92-L96

But I think it would be much simpler to handle the theme directly in the `Illustration` and `Icon` component, with something like:
https://github.com/LiskHQ/lisk-desktop/blob/9036a3a0e2f87cf4708f886be40a1d75a71dc574/src/components/toolbox/icon/index.js#L186-L190
