### ISSUE TITLE
Lisk Desktop doesn't recognize Ledger Nano S on firmware 1.6

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#2670]
### Expected behavior
It should detect the device with no issues
### Actual behavior
It doesn't detect the device 
### Steps to reproduce
Upgrade Ledger Nano S to 1.6, open Lisk Desktop
### Which version(s) does this affect? (Environment, OS, etc...)
Windows

![image](https://user-images.githubusercontent.com/25085095/69577302-60cdc880-0fce-11ea-9918-87d4c46802d1.png)

**Comment by pyzdra11** [comment]
I have exactly the same problem as you.

**Comment by seerMar** [comment]
I have the same problem. No access to my Lisk since the last update Ledger Nano S and Lisk Wallet :(

**Comment by univerza19** [comment]
I have the same problem.

**Comment by seerMar** [comment]
macOS Mojave + New Lisk Wallet 1.23.0 + Ledger Nano S still no access to the coins. When will be patch?

**Comment by reyraa** [comment]
This is due to the updated firmawre of Ledger Nano. We'll tackle it ASAP. Thanks for reporting.
