### ISSUE TITLE
Header alignment is incorrect in delegates page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2673]
### Expected behavior

All page headers should be aligned  properly

### Actual behavior
Header alignment is incorrect in delegates page. Please refer the attachment![Screenshot 2019-11-28 at 17.39.07.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/8443671d-0deb-4cd2-8cf5-960e1709e1cc)

**Comment by reyraa** [comment]
This is fixed by #2624
