### ISSUE TITLE
Display amount per transaction statistics

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2677]
### Description
Display statistics for amount per  transaction occurred in last 7 days, 6 months and 12 months

### Motivation
Provide users with realtime stats on amount per transaction throughput

### Acceptance Criteria
1. Amount per transaction occurred in last 7 days from the current date & time.
2. Amount per transaction occurred in last 6 months from the current date & time.
3. Amount per transaction occurred in last 12 months from the current date & time.
4. The data should support to build donut and pie graph
5. The amount rage should be 
 Between 0 and 1;  Between 1 and 10; Between 10 and 100; Between 100 and 1K; Greater than 1K
6. All the transaction details should be in UTC time zone.

### Additional Information
Refer [UI design](https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/389319981) for better information.

![Screenshot 2019-11-25 at 11 13 58](https://user-images.githubusercontent.com/1254342/69531974-27b53a00-0f75-11ea-86e6-8c3bf7c1263a.png)

**Comment by sridharmeganathan** [comment]
Addressed in #2813
