### ISSUE TITLE
Display types of transaction statistics

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2678]
### Description
Display statistics for types of transaction occurred in last 7 days, 6 months and 12 months

### Motivation
Provide users with realtime stats on types of transaction throughput

### Acceptance Criteria

1. Types of transaction occurred in last 7 days from the current date & time.
2. Types of transaction occurred in last 6 months from the current date & time.
3. Types of transaction occurred in last 12 months from the current date & time.
4. We should support 8 types of transaction as per the current system Architecture and this should be scalable enough to support new transaction types in future.
5. The data should support to build donut graph and pie graph
6. All the transaction details should be in UTC time zone

### Additional Information
Refer [UI design](https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/389319981) for better information.

![Screenshot 2019-11-25 at 11 13 50](https://user-images.githubusercontent.com/1254342/69531946-1a984b00-0f75-11ea-92f3-5adc503e0263.png)

**Comment by sridharmeganathan** [comment]
Addressed in #2813
