### ISSUE TITLE
Remove steps text from account creation

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-desktop#2684]
### Expected behavior

Show the progress without mentioning with text how many steps are left.

### Actual behavior

On the third step only, it's shown "Step 3/4" as per screenshot below:

<img width="1712" alt="Screenshot 2019-11-28 at 10 30 09" src="https://user-images.githubusercontent.com/45934100/70064042-24f7bc00-15e9-11ea-9a41-737149bb7c13.png">

### Steps to reproduce

Create an account - Choose avatar - Save passphrase - Confirm (Here)

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk Hub 1.23

**Comment by slaweet** [comment]
Done in https://github.com/LiskHQ/lisk-desktop/pull/2686
