### ISSUE TITLE
Alignment of CTAs seems off in some pages

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-desktop#2694]
### Expected behavior

The CTA has a defined padding top/bottom as per design

https://invis.io/6STGFKRXRQM#/378999036_4-1_Transaction_-_Send_LSK

### Actual behavior

The CTA is too close or not aligned with what defined in the designs (reference Invision above)

<img width="886" alt="Screenshot 2019-12-10 at 16 15 58" src="https://user-images.githubusercontent.com/45934100/70543396-9f38bb00-1b6a-11ea-946b-09a7cf37bf84.png">

<img width="889" alt="Screenshot 2019-12-10 at 16 15 50" src="https://user-images.githubusercontent.com/45934100/70543397-9f38bb00-1b6a-11ea-994b-6d11fddda711.png">

### Steps to reproduce

Navigate to Wallet -> Send LSK
Dashboard -> Add a new bookmark

### Which version(s) does this affect? (Environment, OS, etc...)

1.23.0

**Comment by reyraa** [comment]
This issue is already resolved with one of visual improvement PRs.
