### ISSUE TITLE
Sharing link field design alignment in light mode

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-desktop#2726]
### Expected behavior

The field should look inactive (not editable), as of the user is not able to edit it but just copy the link by clicking on the action below. Currently does in the dark mode but not in the light mode.

Same as above applies to BTC, as of you are not able to edit the address that is there.

![Inactive Share link field](https://user-images.githubusercontent.com/45934100/72167740-0648ca00-33cc-11ea-94bb-fa28737a721f.png)

### Actual behavior

The field looks like the ones above, so editable, when is not.

<img width="1477" alt="Screenshot 2020-01-10 at 17 10 22" src="https://user-images.githubusercontent.com/45934100/72167792-21b3d500-33cc-11ea-9248-862bd7fde620.png">

### Steps to reproduce

Log in with your account, navigate to wallet, request LSK (same applies to BTC)

### Which version(s) does this affect? (Environment, OS, etc...)

1.23.0

**Comment by sridharmeganathan** [comment]
Tested the changes. Working as expected
