### ISSUE TITLE
Lisk desktop not working (1.24.0) after successful login using Trezor hardware wallet

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2730]
### Expected behavior
Application should work after successful login using Trezor Model One wallet

### Actual behavior
After successful login using Trezor Model One wallet, Lisk desktop is not loading the dashboard page

### Steps to reproduce
Step 1: Sign in the Lisk desktop using Trezor wallet
2. Select "Select this account" button
3. Nothing happens except the pre-loader.

Now close the application and sign in again. It is working fine. This issue is occurring whenever we disconnect hardware wallet and reconnect again.

### Which version(s) does this affect? (Environment, OS, etc...)
1.24-rc

**Comment by reyraa** [comment]
Fixed by #2862
