### ISSUE TITLE
Darkmode: when user input block id information in generic search (Desktop header), the preview of search panel is not visible enough to end user

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2735]
In dark mode in generic search, when user input the block id, the preview of search panel is not visible enough to end user

**Comment by reyraa** [comment]
@sridharmeganathan Looks pretty clear to me.
![Uploading Screenshot 2020-02-06 at 11.49.55.png…]()

Could you explain the issue?
