### ISSUE TITLE
Sign message not visible when using hardware wallet

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#2757]
### Expected behavior
See the Sign Message option in the menu

### Actual behavior
The Sign message option is not visible in the menu

### Steps to reproduce
- Open Lisk Desktop
- Log in using hardware wallet 
- Click on wallet name to see options
- Notice that the option is missing

### Which version(s) does this affect? (Environment, OS, etc...)
Windows 10
Lisk Desktop 1.24.0
Nano Ledger S 1.5.5

**Comment by reyraa** [comment]
Thanks @Lemii, We'll plan to add this feature in the future.
