### ISSUE TITLE
Missing CONTRIBUTING file

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#2765]
The README has a link to a `CONTRIBUTING.md` file, but it is missing:

```
For Contributors
Please see CONTRIBUTING.md for more information.
```

**Comment by slaweet** [comment]
Thank you for pointing it out, @Lemii 👍 

We do have CONTRIBUTING_GUIDE in docs folder: https://github.com/LiskHQ/lisk-desktop/commits/development/docs/CONTRIBUTING_GUIDE.md so we should move it or update README.
