### ISSUE TITLE
Delegates Vote weight are incorrect in the delegates tab (beta version)

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2791]
Delegates Vote weights are incorrect in the delegates tab (beta version)

I unvoted someone from pool(101) and voted myself in.. the desktop shows voteweight 794 which is incorrect.. the core API shows
{
  "meta": {
    "offset": 0,
    "limit": 10
  },
  "data": [
    {
      "username": "subzero",
      "voteWeight": "9900079293400000",
      "rewards": "0",
      "producedBlocks": 0,
      "missedBlocks": 0,
      "productivity": 0,
      "account": {
        "address": "5553317242494141914L",
        "publicKey": "eb06e0a8cbb848f81f126b538794eb122ae8035917ded1da3e5c85618602f3ba",
        "secondPublicKey": ""
      },
      "approval": 98.8
    }
  ],
  "links": {}
}

**Comment by reyraa** [comment]
This issue fixed by #2777
