### ISSUE TITLE
Parts of the code that could be improved in version 1.23.0

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-desktop#2807]
Parts of the code that could be improved: ● There are 8 separate webpack configs. There is no explanation anywhere why project needs 8 config files ● There are 2 catalogs app and src which should be unified to one catalog ● Redux actions in single catalog

It’s also a good practice to add ​quality badges​ to open source projects that attract users to use Lisk projects and open source contributors to contribute.

**Comment by slaweet** [comment]
Two of the points from the description were addressed in https://github.com/LiskHQ/lisk-desktop/issues/2793 and https://github.com/LiskHQ/lisk-desktop/issues/2793
