### ISSUE TITLE
Inform user to initialize account, before registering as delegate

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-desktop#2816]
### Expected behavior
The user should be informed, that the delegate registration fails, if the account is not initialises.

### Actual behavior
It was reported that it is not possible to register as a delegate with an uninitialised account, without further information why it fails.
After initialising the account, a delegate could be registered successfully.

### Steps to reproduce
Create new testnet account.
Send at least 25 LSK to this account.
Login to Lisk Desktop with the new account and try to register a delegate.

**Comment by slaweet** [comment]
AFAIK, there is no technical limitation of why registering a delegate should fail on an uninitialized account. So I assume this is a frontend issue and the solution should be to fix delegate registration to work without account initialization.

**Comment by yarooo85** [comment]
I've checked other new testnet delegates and some of them have registered their delegates without making any outgoing transaction... Didn't notice but maybe i was trying to register a delegate when one of the "red" delegates was forging at that moment? Can this affect delegate registration process?

**Comment by slaweet** [comment]
@yarooo85 "red" delegates are no problem here. The network has a transaction pool that will keep your transaction until a forging delegate's turn. If my assumption that this is a frontend bug is right, then other delegates registered as their first transaction could be explained by this bug being introduced only in some recent version of Lisk Desktop. 

Anyway, I'm just leaving my thoughts here for when this ticket will be planned into a development sprint and assigned to someone to work on.
