### ISSUE TITLE
Make Lisk Desktop follow the system-wide dark mode setting

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2839]
### Description
We should enable users to use Lisk Desktop with their selected macOS theme.

### Motivation
Respect users' system wide settings.

### Acceptance Criteria
- I should be able to change Lisk Desktop theme by changing system theme.
- I should be able to change to a theme other than system theme.

**Comment by ManuGowda** [comment]
We are reconsidering the future wallet requirements, for time being we are not focusing on these aspect hence closing.
