### ISSUE TITLE
Display the remaing time to the end of round

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2874]
### Description
As a user; I'd like to know where in the round the network is at, and how long remains before the end of current round. 

### Motivation
This is implicitly implied by the Delegates Forging Status graph on Delegates Monitor page.
<img width="399" alt="Screenshot 2020-05-04 at 14 30 48" src="https://user-images.githubusercontent.com/666685/80965980-dfe3ea00-8e13-11ea-8538-d6810651e5c6.png">
but my proposal is to implement another graph that explicitly depicts the current state of the round. This is more useful after new changes to Network Consensus is introduced.

### Acceptance Criteria
TBD

@shuse2 and @ManuGowda I think you have more ideas here. Please use the comments to share your opinions.

**Comment by sridharmeganathan** [comment]
This issue is no more valid. We already implemented this feature.
