### ISSUE TITLE
Add multisignature transaction support

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2891]
### Description

As a user; I'd like to
- Enable users to register groups, list groups/transactions, share transactions, sign transactions, reject transactions
- Migrate users with second passphrases to the new multisignature system
- Notify users about new multisignature accounts, transactions, signatures, rejections
- Enable users to toggle the pooling of transactions on Lisk Service

### Motivation

Make multi-signature accounts more flexible, prevent spamming, and prevent signature mutability

### Action points

- Register a multisignature group
- Initiate/create a multisignature transaction
- See list of multisignature groups they created (on a dedicated page)
- See list of multisignature groups of which they are a member (on a dedicated page)
- See the list of multisignature transactions that they initiated
- Sign an already created/initiated multi-signature transaction
- Remove/ignore a multisignature transaction
- Share the initiated / signed transaction using QR code
- Broadcast a transaction which has all required signatures
- Enable users to convert an account to multisignature
- Remove second passphrase registration
- Treat second passphrase as a mandatory key
- Enable users to accept membership of a multisignature account
- Enable users to view multisignature account configuration
- Enable users to initiate a multisignature transactions

### Additional features

Users must be able to:

- Share transaction QR codes via email

### Tasks

- Support multisignature transactions #3093 
- Add multisignature transaction pool setting #2892
- Remove second passphrase support #2893
- Add multisignature transaction notifications #2894

**Comment by karmacoma** [comment]
This epic has now been split into multiple epics:

- Support multisignature transactions #3093
- Add multisignature transaction pool setting #2892
- Remove second passphrase support #2893
- Add multisignature transaction notifications #2894
