### ISSUE TITLE
Delegates List show only top 90 delegates instead of top 101

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#2950]
v1.26.0, Windows 10

When going to Delegates tab it only load 90 delegates but should load 101.

![grafik](https://user-images.githubusercontent.com/1260700/87221261-de322780-c36a-11ea-9c4c-1a068df27317.png)

**Comment by reyraa** [comment]
Does the load more button work?

**Comment by punkrock** [comment]
Yes.

**Comment by reyraa** [comment]
OK, good point. I'll add this to one of the upcoming sprints.

**Comment by sridharmeganathan** [comment]
This issue is fixed. Verified in 1.28.0
