### ISSUE TITLE
Visual issues discovered testing the beta build 1.27.0

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2957]
Description

The following visual issues are discovered in the beta build 1.27.0

- Move the loader below the top bar.
- Don’t show the bookmark button on my wallet page.
- Add a single pin on the map at the network page.
- Change the tabs appearance when switch to the dark mode.
- Sign in screen: align the labels to the left side and make the font style according to the design.
- Rename “Voting” to “Votes” (in tabs)
- Remove the description paragraph below the headings and check the heading texts. There were some changes.
- Transaction details: alignment issues
- Bookmarks: after click on the bookmark icon the modal window should close
- Votes submitted modal window: the modal window should be bigger (the same size like other modal windows), there is no "back to voting" button. 
![image](https://user-images.githubusercontent.com/51332105/88059256-e5281980-cb64-11ea-9536-ee6b7ce955a3.png)
- Transaction details, Voting summary screen: when the content is longer than the window's height the scrollbar is absent. 
![image](https://user-images.githubusercontent.com/51332105/88059303-f4a76280-cb64-11ea-8ab8-b4b124d1f98e.png)
- In delegate's wallet page, we showed delegates rank earlier but now we are not. Is that okay?
- Prev version
![image](https://user-images.githubusercontent.com/40266606/88064237-0115c600-cb39-11ea-8978-0a9458674962.png)
![image](https://user-images.githubusercontent.com/51332105/88064662-dabd4e00-cb6b-11ea-9478-982196a9982d.png)
- Request LSK functionality is missing in the new layout. ![image](https://user-images.githubusercontent.com/51332105/88066607-3d174e00-cb6e-11ea-93e5-ac69550a0c54.png)
- In delegates stats,  **Delegates since** is showing incorrect information - Done
![image](https://user-images.githubusercontent.com/51332105/88069277-8cab4900-cb71-11ea-8781-5f49b20515bb.png)
![image](https://user-images.githubusercontent.com/51332105/88081998-7a390b80-cb81-11ea-80f0-f773a95134f2.png)
- In the previous version in delegates stats, we are showing the last forger, but in the new layout last forger information is missing. Also the last forged block information is incorrect. - Invalid
![image](https://user-images.githubusercontent.com/51332105/88081087-372a6880-cb80-11ea-8372-a0daafddba81.png)
- There is a conflict in Total forged LSK in the new version and previous version - Invalid for this version
![image](https://user-images.githubusercontent.com/51332105/88081522-c5065380-cb80-11ea-938b-dc08c2e604f9.png)
![image](https://user-images.githubusercontent.com/51332105/88081674-03037780-cb81-11ea-8ccc-f036d9ad019e.png) 
- In Votes section, Inconsistency in selecting the row items.   Other grids, all cells are selectable but in Votes/Voting section only the first cells are selectable - Done
- In Windows, Auto update is not working and throwing the below error.  It is working fine when i download the latest version from Github.
![image](https://user-images.githubusercontent.com/51332105/88159567-bfa31a80-cc0d-11ea-8d00-47f2c55dc493.png)
- In windows, padding is incorrect.
![image](https://user-images.githubusercontent.com/51332105/88165035-5b845480-cc15-11ea-9e1c-3bc7953d4d15.png)

**Comment by ann-vashchenko** [comment]
Please find the following comments below: 

1. Move the loader below the top bar.
2. Don’t show the bookmark button on my wallet page.
3. Add a single pin on the map at the network page.
4. Change the tabs appearance when switch to the dark mode.
5. Sign in screen: align the labels to the left side and make the font style according to the design.
6. Rename “Voting” to “Votes” (in tabs) 
7. Remove the description paragraph below the headings and check the heading texts. There were some changes. 
8. Transaction details: alignment issues. 
9. Bookmarks: after click on the bookmark icon the modal window should close.

**Comment by gmsridhar** [comment]
> Issues 1-7 are done, thanks
> 
> Could you fix please the following issues:
> 
> 1. Change the voting icon state (it should be bold when it is active)
> 2. Filter icon is broken
> 3. Tooltip is broken (when hover on “start voting” button)
> 4. We agreed to remove tabs with transaction types (all, incoming, outgoing)
> 5. Transaction details modal window: alignment issues
> 6. Bookmarks: after second click on the bookmark icon the modal window should close.
> 7. Votes submitted modal window: the modal window should be bigger (the same size like other modal windows), there is no "back to voting" button.
>    ![image](https://user-images.githubusercontent.com/51332105/88059256-e5281980-cb64-11ea-9536-ee6b7ce955a3.png)
> 8. Transaction details, Voting summary screen: when the content is longer than the window's height the scrollbar is absent.
>    ![image](https://user-images.githubusercontent.com/51332105/88059303-f4a76280-cb64-11ea-8ab8-b4b124d1f98e.png)
9. In delegate's wallet page we showed the delegates rank earlier. Now we are not. Is that okay?
Prev version
![image](https://user-images.githubusercontent.com/40266606/88064237-0115c600-cb39-11ea-8978-0a9458674962.png)
