### ISSUE TITLE
Enable users to track unlock times and submit an unlock transaction

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2976]
### Description
As a user I like to see the details of available and locked balance. Furthermore, submit unlock transactions when possible.

### Motivation
Enable users to unlock their balances.

### Acceptance Criteria
Users must be able to:
- See available and locked balance without having to open the modal
- See the available balance.
- See the locked balance,
- See unlock count downs in separate rows displaying the funds and time remaining until unlock.
- See available funds to unlock.
- Define processing speed and submit unlock transaction.

### Additional info

- Fetch unlocking from /account and store it under /voting in Redux store.
- We suggest creating PRs to
    - Add actions, reducers and API changes for fetching data.
    - Render the modal and create Tx with basic unit tests.
    - Increase unit tests and introduce e2e tests.

**Comment by isalga** [comment]
@sridharmeganathan . I discussed with @reyraa  and as Lisk Service is not yet supplying delegate punishment information I created [this ticket](https://github.com/LiskHQ/lisk-desktop/issues/3090) to remind us to update delay availabilities when API is ready.
