### ISSUE TITLE
LSK to USD value is missing in wallet and send LSK page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2990]
LSK to USD equivalent value is missing in wallet and send LSK page

![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/a0bbf69e-17e4-4eac-bc5d-9d0c860ed3af)

**Comment by isalga** [comment]
@sridharmeganathan  I am not able to reproduce it neither on current status of 1.27.1 and on 1.27.0.

![Screenshot 2020-08-13 at 16 46 37](https://user-images.githubusercontent.com/3985124/90149252-95fc8f80-dd84-11ea-9508-fe94b4d6f90e.png)

**Comment by reyraa** [comment]
Sine the API doesn't return CHF exchange ratio, the client doesn't have the value to show. hence it hides the fiat value.
