### ISSUE TITLE
Network statistics disappears in some cases

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-desktop#2995]
### Expected behavior

Network statistics should be shown on the Network page.

### Actual behavior

In some cases no information will be visible.

### Steps to reproduce

[Sign in] page select testnet > goto [Transactions] page > [Sign in] select mainnet > goto [Network] = statistics gone

### Which version(s) does this affect? (Environment, OS, etc...)

Win10.

![image](https://user-images.githubusercontent.com/42899281/89710869-e2ac2900-d986-11ea-961b-bfe2f8e3f28f.png)

**Comment by reyraa** [comment]
Thanks for the information. This is an API issue. I'll report it.
