### ISSUE TITLE
Search for a specific account

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-desktop#2996]
Currently there's no way to search for a specific account address and display its statistics. To be able to lookup an account, the "Accounts" page could be improved with a search box.

**Comment by reyraa** [comment]
You can simply use the main search tool on the header. I don't think we need a second search bar. but if you think we can improve the search result I'm open for new ideas.

**Comment by Korben3** [comment]
Ah, I didn't noticed the search icon in the header at first. It solves this issue, thanks!
