### ISSUE TITLE
Version not signed by the application owner

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#2998]
User reported that the update process failed due to the following error:

![grafik](https://user-images.githubusercontent.com/1260700/89711463-bb575b00-d98a-11ea-9da6-fe1be0c378fe.png)

**Comment by karmacoma** [comment]
@punkrock Thanks for reporting this issue. We have now resigned the Windows package and updated the release: https://github.com/LiskHQ/lisk-desktop/releases/tag/v1.27.0
