### ISSUE TITLE
Lisk Balance graph on account page shows incorrect datapoints

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-desktop#3000]
### Expected behavior
Viewing Lisk Balance on delegate cc001 (6787154358850114730L) would have been 26,607.298 LSK on the 18th of July (viewed via Balance History tool -> https://sidechainsolutions.io/content/tools/balance-history/)

### Actual behavior
The actual datapoint on the Lisk Balance graph indicates that account 6787154358850114730L 30,601 LSK on the 18th of July. The invalid calculation can be applied for any account. 

### Steps to reproduce
It can be reproduced by viewing a delegate account via Lisk Desktop

### Which version(s) does this affect? (Environment, OS, etc...)
Mac OS  - Lisk Desktop 1.27

**Comment by tomploem** [comment]
@reyraa Can we check the issue please?

**Comment by reyraa** [comment]
Thank you for opening this issue and sorry for such a late response. This issue is already resolved.
