### ISSUE TITLE
Support unlock LSK transaction

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3054]
### Description
As user I should be able to see the details of unlock LSK transactions in transaction details screen. I should also be able to see unlock LSK transactions in transactions list.

### Motivation
Enable users to get information about all available tx types.

### Acceptance Criteria
Users must be able to:
- Distinguish unlock LSK transactions in tx lists.
- See basic tx information on tx details screen.
- See the value unlocked on tx details screen.

**Comment by punkrock** [comment]
A thought I have about this: It would be good to see all pending unlocks (maximum 20 entries) and the time/date information when the unlock will be finished, so users have nice overview when their unlocked LSK will be available for transfer.
