### ISSUE TITLE
Quality Assurance - Release 1.27.1 beta

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3057]
The purpose of this issue is to identify the bugs in 1.27.1 beta build and fix it

1. Tooltip text should be changed if the account is already added in bookmarks. (Edit bookmark)
![image](https://user-images.githubusercontent.com/51332105/92730301-dcd5a900-f373-11ea-8f60-f3217de6fb89.png)

2. Latest votes - Not working ( Delegates monitoring page)
![image](https://user-images.githubusercontent.com/51332105/93309837-4803fd00-f804-11ea-86b7-62e67ebe7605.png)

3. Delegate votes transaction details - Added votes/Edit votes are not getting loaded.
![image](https://user-images.githubusercontent.com/51332105/93310336-f27c2000-f804-11ea-956b-afa89088e9df.png)

4. Load more button is visible when i filter by delegate name ( All delegates tab & Not voted Tab)
![image](https://user-images.githubusercontent.com/51332105/93237941-1007a600-f781-11ea-8c5c-6e2daaa7c4b1.png)

5. 'Filter by name' functionality is not working as expected in the delegates page. This functionality is working well in Active delegates tab but it is not working in the Standby delegates tab.
![image](https://user-images.githubusercontent.com/51332105/93484978-d8286c00-f902-11ea-9f75-1cc223524180.png)

**Comment by ann-vashchenko** [comment]
UI Review Linux: 

* All accounts: there is no border under the table heading (visible on hover only) 
* When resizing the Lisk balance graph should decrease, but not the wallet address and balance blocks. 
* There is a horizontal scroll when resizing (wallet page)  
* There is a big margin between the light/dark mode icon and the network status (When logged out) 
* apply to the block details page and the delegate stats block the resize styles similar to other pages. 
* Make the guides tooltips smaller (when resizing at the block with the pie chart ).
