### ISSUE TITLE
Deep link builder

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-desktop#3072]
### Description

An easy way to create a link you can put on a webpage that when clicked summons Lisk Desktop to perform the intended action.

### Motivation

Adding a donation button on a lisk related repository.

### Additional Information

If you could add a set of asset to be used along those links it would be great !

**Comment by reyraa** [comment]
We already have deep linking for se sending transaction, signing a message, voting and registering a delegate.
Also for opening specific pages.

**Comment by JesusTheHun** [comment]
Is it possible to prompt for a specific transaction and not summon a generic and empty transaction page ?

Opening Lisk Desktop to send a transaction of module ID A asset ID B and a payload C ? The user just have to read, sign & send.
