### ISSUE TITLE
Send deeplink trigger an error

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-desktop#3073]
### Expected behavior

Clicking on lisk://wallet/send?recipient=123L&amount=1234&data=message should open Lisk Desktop, after prompt for a transfer after login.

### Actual behavior

Error on Lisk Desktop startup : 
```
Uncaught Exception:
TypeError: Cannot read property 'show' of null
    at App.<anonymous> (/Applications/Lisk.app/Contents/Resources/app.asar/build/main.js:173:137815)
    at App.emit (events.js:203:13)
```

### Steps to reproduce

Open the link above.

### Which version(s) does this affect? (Environment, OS, etc...)

MacOS 10.15.6 with Lisk Desktop 1.27

**Comment by reyraa** [comment]
Duplicate of #3657
