### ISSUE TITLE
What does this arrow indicate?

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3077]
I don't understand what the arrow pointing to the left (beside the account avatars) wants to tell me.
Can you explain and maybe create a tooltip for it, so people undestand what it is.

Version: lisk-win-1.27.1-beta.0

![arrow](https://user-images.githubusercontent.com/1260700/94044302-3dca9b80-fdce-11ea-966c-2718720f037e.gif)

**Comment by reyraa** [comment]
It demonstrates an incoming or outgoing transaction. Although we now think it's redundant and we'll remove it soon.
