### ISSUE TITLE
Make notifications visible

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3085]
Please make the info popup more visible. Sure, it looks nice implemented into the current design but that's not what you want for info boxes. You want to users to see it right away and put attention to it.

![grafik](https://user-images.githubusercontent.com/1260700/94801066-cad0ae80-03e5-11eb-969e-cd44a0e51e99.png)

**Comment by elitedev1314520** [comment]
I would like to help fix this issue.
Is there anyone I can help with?

**Comment by reyraa** [comment]
Thanks @punkrock @elitedev1314520 I'll inform @ann-vashchenko to review this design.

**Comment by reyraa** [comment]
Thanks for opening the issue.
The design is tweaked for better visibility of the banner.
