### ISSUE TITLE
(MacOS) "Restart now"-button not working after update

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3087]
After an Update to latest version on MacOS 10.15.6 I clicked the "Restart now"-button but nothing happens.

**Comment by reyraa** [comment]
This issue was discovered in v1.27.0 and fixed by v1.27.1. Unfortunately since the version that handles the update from v1.27.0 to v1.27.1 us the older one, it fails to restart automatically. You won't have this problem with the next update.
