### ISSUE TITLE
Update indicator

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3088]
### Description
Currently when doing auto-update, you only see a "Downloading now"-popup in the bottom right corner for a short time. After it's gone, it takes about 30 seconds or more where nothing happens and the users don't know what's going. It would be much better if there is always an indicator about what's happening, like some progress bar.

### Motivation
Inform Windows/Linux users about the download progress.

### Acceptance criteria 
- Users must be able to start to download a new version, and see the progress bar at the bottom right according to the [design](https://www.figma.com/file/bXgp4J8jsglJovqAkNVx1C/Loader?node-id=0%3A1).
- The progress bar must correspond to the percentage of the file downloaded.
- The feature must work on Mac, Win and Linux.
- User must be able to discard the download progress toast by clicking on the cross button or pulling the toast to right.
- The currently naively implemented restart/later modal should be replaced by the toast defined in the design guide.

**Comment by reyraa** [comment]
It's not completely nothing going on. Mac OS shows a download progress bar on the application icon in your dock. Although I agree with you, we can improve this by showing an additional progress bar inside the application.

**Comment by punkrock** [comment]
On Windows it shows nothing. You only see a "Downloading now"-popup in the bottom right corner for a short time. You guys really should test this application on Windows, too. We have several issues Windows-only.
