### ISSUE TITLE
Remove vote amount on edit removes all vote amount instead of the inputed amount

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3108]
### Expected behavior
It should remove the inputed vote amount

### Actual behavior
It removes all the voted amount

### Steps to reproduce
- Vote for a delegate (ex: 40)
- Confirm transaction on voting queue
- Downvote the same delegate (ex: 20)
- Open voting queue

![Screenshot 2020-10-13 at 09.40.42.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/81de9518-b903-4f3b-a0f4-65a41d2a5524)![Screenshot 2020-10-13 at 09.41.02.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/b8c1ac77-6d4e-4ced-af77-d3d9f4a34df0)![Screenshot 2020-10-13 at 09.41.22.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/7e4bb77a-4937-4bfc-8ee3-1a9bce478d2d)

**Comment by UsamaHameed** [comment]
I think this is the expected behaviour. When you click on "remove vote", it should remove the vote in its entirety. If you want to change your vote amount from lets say 40 to 20, you will type in 20 in the input field and then click on "confirm".
