### ISSUE TITLE
Create a generic component to display account info

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3142]
### Description
We have created several components to through out the time to display account address, avatar, delegate username, bookmark title and so on. To follow DRY, we should replace all of them with a unique component that preforms the same job.

### Motivation
Improve code maintainability and prevent potential visual inconsistency. 

### Presentation
In the most complex mode, the component must look the as follows:

<img width="351" alt="account-info" src="https://user-images.githubusercontent.com/666685/97842724-5c368780-1ce8-11eb-846e-04d789818949.png">

The above component consists of 5 elements:

<img width="351" alt="account-info" src="https://user-images.githubusercontent.com/666685/97844072-a7ea3080-1cea-11eb-8781-bd05fffad46b.png">

**1. Prefix**
Optional. this may be a numeric or alphabetic value. Only displayed if such a parameter is passed.
**2. Avatar**
Always displayed unless actively hidden using a parameter. 
**3. Primary value**
Sequentially:
 - Delegate username
 - Bookmark title
 - Address
Which ever is passed. 

**4. Secondary value**
Sequentially:
 - Delegate username
 - Bookmark title
 - Address
 - Public key
Which ever is passed and not used as the primary value.

**5. Postfix**
Optional. Any additional information about the account. For example, it's one of "Mandatory" and "Optional" for a multisignature group member.

### Responsiveness
The Address and public key must be truncated on small screens by default. Although we should be able to display truncated address and public key on wider screens by passing a relevant parameter.

### Data adaption
If there's only one value provided (e.g. address), the value must be vertically centered.

### Actions
If the primary value is a delegate username, the component must link to delegate profile, else if should navigate to the wallet transactions tab.

### Acceptance Criteria
All the other components performing the same job must be replaced with this component.

**Comment by ManuGowda** [comment]
https://github.com/LiskHQ/lisk-desktop/issues/4035 Epic will ensure the generic component for account display
