### ISSUE TITLE
Display PoM transactions in transaction details page

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3198]
### Description
Developing details of #3197, we need to enable users to view PoM transaction details.

### Acceptance Criteria
Display PoM transaction details. These details are shown in addition to basic transaction properties:

- Misbehaving delegate (Avatar, address and username) 
- Height
- Block Id

**Comment by sridharmeganathan** [comment]
This is issues closed as part this Github issue #3686
