### ISSUE TITLE
Resolve todo comments in the code

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3213]
### Description
We have 5 todo comments in the code as follows:

1. The [wallet component](https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/screens/wallet/index.js#L34) should not load transactions. We should move this logic to the tx tab component. Since we will remove the tabs with the next release, we can move this logic then.
2. The [table header](https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/toolbox/table/header.js#L49) component should define the default grid size based on the number of children.
3. What should the [table header](https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/toolbox/table/header.js#L80) display if the header config is not an array, nor a React component?
4. The todo in [transactioonTypes](https://github.com/LiskHQ/lisk-desktop/blob/development/src/constants/transactionTypes.js#L4) config file is already resolved but the comment is not removed.
5. Investigate the correct implementation of Lisk Client and remove the todo in [network.js](https://github.com/LiskHQ/lisk-desktop/blob/development/src/utils/api/lsk/network.js#L24).

**Comment by ManuGowda** [comment]
Suppressed by https://github.com/LiskHQ/lisk-desktop/issues/3846
