### ISSUE TITLE
Can't vote using Ledger Nano X 

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3226]
### Expected behavior
I should be able to vote using my Ledger Nano X.

### Actual behavior
The app throws error when I try to vote using my HW.

### Steps to reproduce
 - Sign in using your Ledger Nano X.
 - Vote
 - The app never activates the HW. It throws before your see any notification on your HW.

### Which version(s) does this affect? (Environment, OS, etc...)
1.27.1

**Comment by UsamaHameed** [comment]
Clsoed by #3323
