### ISSUE TITLE
Prepare 2.0.0 for beta.1

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-desktop#3251]
### Description

The purpose of this epic is to prepare version 2.0.0 for beta.1 release (#2890).

#### Sprint 39

- The balance graph has stopped working #3204

#### Sprint 40 & 41

- Missing information in different pages #3284

#### Sprint 41

- Unlock token screen display wrong times #3282
- Search feature deosn't work #3332
- Sort by rank on standby delegates is not working #3329 
- Delagate vote transaction details displays 0 as amount of transaction #3318
- Account monitor page shows only 10 accounts without a load more button #3330 
- Delegate weight is always 0 #3327 
- Cypress result on Jenkins are different than in my local #3305 
- Cypress thrown uncaught invalid or unexpected token syntax error in CI/CD #3301 
- Set up Lisk Service to run on Jenkins #3299 
- Fix broken ws connections because service url is undefined #3298 
- Crash on opening unlock transaction modal #3314

#### Sprint 41 & 42

- Wallet balance does not update its value after sending tokens #3322 
- Register as delegate is failing #3321
- Vote Item component shows delegate address but not name #3319

**Comment by reyraa** [comment]
We released this version.
