### ISSUE TITLE
The app consumes too much memory

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3265]
### Expected behavior
The app should consume a reasonable size of memory.

### Actual behavior
I keep receiving the following message on Safari. This occurs when the page is open for a while.
<img width="707" alt="Screenshot 2021-01-05 at 11 02 01" src="https://user-images.githubusercontent.com/666685/103633146-9ec54c00-4f45-11eb-938d-fc9f78a52702.png">

### Steps to reproduce
- Open the app in Safari
- Navigate to a few pages
- Leave the page open for a while

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by UsamaHameed** [comment]
I have been unable to reproduce this issue as of yet. Will continue to try.
