### ISSUE TITLE
hubdev@lisk.io email address does not exist

### ISSUE THREAD

**Issue by lukeliasi** [LiskHQ/lisk-desktop#3273]
On the error modal there is a link to "Report the error via E-Mail", mailto points to hubdev@lisk.io email address that does not exist.

![image](https://user-images.githubusercontent.com/5647695/103892395-6ce9ec00-50e3-11eb-9a00-67c7b80588ab.png)

Relevant files to update:
https://github.com/LiskHQ/lisk-desktop/search?q=hubdev%40lisk.io

**Comment by reyraa** [comment]
We have reinstated this email address.
