### ISSUE TITLE
Clipping address on delegate table at Monitor delegate page.

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3315]
![Screenshot 2021-01-29 at 15.23.19.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/77cdee56-2c7c-4ad6-9b7a-1ab82888bef8)

### Expected behavior
Should display ellipsis

### Actual behavior
Address is croped

### Steps to reproduce
- Go to monitor delegate
- Reduce screen size until it clips

### Which version(s) does this affect? (Environment, OS, etc...)
macOS, feature-forging-delegates

**Comment by UsamaHameed** [comment]
Would be fixed in #3142
