### ISSUE TITLE
Scroll overviews are visible at voting queue modal

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3317]
![Screenshot 2021-01-29 at 15.30.53.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/0823953f-bee4-4581-a473-8c65a286414b)

### Expected behavior
Scrollviews should not be visible

### Actual behavior
Scrollviews are visible

### Steps to reproduce
- Vote for a delegate
- Open Voting queue

### Which version(s) does this affect? (Environment, OS, etc...)
macOS, feature-forging-delegates

**Comment by UsamaHameed** [comment]
Unable to reproduce. 

<img width="865" alt="Screenshot 2021-02-04 at 14 29 13" src="https://user-images.githubusercontent.com/11444352/106899236-6ad07880-66f5-11eb-8e68-26b7d9f2abbd.png">
