### ISSUE TITLE
Transactions overview graphs are broken

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3342]
### Expected behavior
The following graphs must display data correctly
- Distribution of transaction types
- Amount per transaction (LSK)
- Transactions number / volume (LSK)

### Actual behavior
The graphs render empty.
<img width="1037" alt="Screenshot 2021-02-03 at 13 06 17" src="https://user-images.githubusercontent.com/666685/106744885-9f263500-6620-11eb-922b-441fcabb988e.png">

### Steps to reproduce
- Connect to Core v3
- Navigate to transaction monitor page.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-beta.1

**Comment by UsamaHameed** [comment]
Can't reproduce, working fine for me @reyraa 
![image](https://user-images.githubusercontent.com/11444352/106755428-6ab97580-662e-11eb-9898-075e66b44b74.png)

**Comment by UsamaHameed** [comment]
<img width="1338" alt="Screenshot 2021-02-03 at 14 55 19" src="https://user-images.githubusercontent.com/11444352/106756738-dea84d80-662f-11eb-9591-86cec2413b50.png">
