### ISSUE TITLE
Delegate monitor displays 3 standby delegates

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3355]
### Expected behavior
In every round 101 active delegates and 2 psudo-randomly selected sandby delegates forge the new blocks. The active delegates are the first 101 delegates ranked by their delegate weight. So the list of "Inside round" delegates should include delegates sequentially ranked from 1 - 101 and 2 delegates with ranked higher than 101.

### Actual behavior
We have 100 active delegates and 3 standby delegates.

### Steps to reproduce
Connect to betanet and navigate to delegates monitor.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-beta.2

**Comment by sridharmeganathan** [comment]
This is Lisk Service related issue.
