### ISSUE TITLE
The delegate status tooltip displays raw numbers

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3356]
### Expected behavior
- Forging and not forging delegates must have different icons.
- The number inside the tooltip must display forging time.
- icons in the design seem smaller.
-  Forging times are updated after new block is created.

### Actual behavior
<img width="199" alt="Screenshot 2021-02-09 at 09 43 04" src="https://user-images.githubusercontent.com/666685/107338372-c2872f00-6abb-11eb-897c-beb0c35bba06.png">
<img width="190" alt="Screenshot 2021-02-09 at 09 42 55" src="https://user-images.githubusercontent.com/666685/107338395-c5821f80-6abb-11eb-963b-211beb1d33fe.png">

### Steps to reproduce
Connect to  betanet and navigate to delegates monitor.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-beta.2

**Comment by isalga** [comment]
After debugging we found out that `forgingTimes` are not being updated after a new block is created. We should fix that too in order to display correct information.
