### ISSUE TITLE
Delegate registration chart displays invalid date

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3358]
### Expected behavior
The x-axis must display multiple dates. and then a "now" at the end.

### Actual behavior
It only displays two values: "now" and "invalid date".
<img width="351" alt="Screenshot 2021-02-09 at 09 59 00" src="https://user-images.githubusercontent.com/666685/107340031-940a5380-6abd-11eb-9453-7f1c56e05a13.png">

### Steps to reproduce
Connect to betanet and navigate to delegates monitor. Check the _Registered Delegates_ chart under _Delegates overview_.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-beta.2

**Comment by sridharmeganathan** [comment]
duplicated.
