### ISSUE TITLE
The forging times are empty at the end of the round

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3359]
### Expected behavior
- All delegates in _inside round_ tab must always have forging time. The time is either in the past or in the future.
- The list of _Next forgers_ under _Forging details_ section must never be empty. If we approach the end of the round, we should display the first few forgers of the next round. 

### Actual behavior
- Seems like instead of displaying the forging time in the past, we display a hyphen "-".
- When we approach to the end of the round, and the number of blocks remaining from the current round is less than 6, the slots in the list of _Next forgers_ under _Forging details_ section remain blank.

the below screenshot shows that in the last block, there is only one delegate displayed.
<img width="837" alt="Screenshot 2021-02-09 at 10 02 18" src="https://user-images.githubusercontent.com/666685/107341055-d1231580-6abe-11eb-8428-5a497fe9c122.png">

### Steps to reproduce
Connect to betanet and navigate to delegates monitor. 
1. You'll notice that every time a delegates forges, the forging time changes from _now_ to a hyphen "-".
2. Wait until the _Blocks forged_ under the _Forging details_ section is over 97. you'll see blank slots in _Next forgers_ list.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-beta.2

**Comment by UsamaHameed** [comment]
Fixed in #3380
