### ISSUE TITLE
Send transactions to other addresses are not displayed. v2.0.0-beta.1 

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3376]
### Expected behavior
It also shows sending to other addresses. (wallet page)

### Actual behavior
Send LSK from my address to other addresses.
not displayed...

### Steps to reproduce
1.  Send LSK from my address to other addresses.
![スクリーンショット 2021-02-12 110128](https://user-images.githubusercontent.com/44485074/107727928-e9e63200-6d2f-11eb-9abe-1f99069e04ac.png)

2.  Send LSK to myself
![スクリーンショット 2021-02-12 110803](https://user-images.githubusercontent.com/44485074/107727996-24e86580-6d30-11eb-88c5-1494d9c61604.png)

3. Check the transaction page
![スクリーンショット 2021-02-12 111305](https://user-images.githubusercontent.com/44485074/107728073-624cf300-6d30-11eb-902b-1779f6b36fab.png)

4. Check the wallet page
![スクリーンショット 2021-02-12 111049](https://user-images.githubusercontent.com/44485074/107728079-66791080-6d30-11eb-9b44-e147d3d3754a.png)

### Which version(s) does this affect? (Environment, OS, etc...)
- Lisk Desktop 2.0.0-beta.1
- Windows 10 20H2 19042.789

**Comment by UsamaHameed** [comment]
Thanks for reporting the issue @lisknonanika. We are aware of this issue and will fix asap.

**Comment by UsamaHameed** [comment]
Fixed in #3380
