### ISSUE TITLE
The pending loading icon will continue to appear. v2.0.0-beta.1

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3377]
### Expected behavior
Turn off the loading icon when the balance is reduced.

### Actual behavior
The pending loading icon will continue to appear..
It doesn't disappear when I move pages in my wallet.
However, it is disappear when I sign in again.

### Steps to reproduce
Send LSK.
![スクリーンショット 2021-02-12 110128](https://user-images.githubusercontent.com/44485074/107728437-6d545300-6d31-11eb-8f5e-5cc1626f7fee.png)

### Which version(s) does this affect? (Environment, OS, etc...)
- Lisk Desktop 2.0.0-beta.1
- Windows 10 20H2 19042.789

**Comment by UsamaHameed** [comment]
Thanks for reporting the issue @lisknonanika. We are aware of the issue and will fix asap.

**Comment by UsamaHameed** [comment]
Fixed in #3380
