### ISSUE TITLE
Incorrect display of network switcher. v2.0.0-beta.1

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3378]
### Expected behavior
The contents of the network switcher must be correct.

### Actual behavior
Custom node settings are not reflected correctly.

### Steps to reproduce

1. Set a URL where node is not running. and click "Connect".
![スクリーンショット 2021-02-12 104357](https://user-images.githubusercontent.com/44485074/107728723-287cec00-6d32-11eb-811f-21a7fa51f56e.png)

2. Since the connection cannot be established, the display remains at the default value (Mainnet).
![スクリーンショット 2021-02-12 104420](https://user-images.githubusercontent.com/44485074/107728768-519d7c80-6d32-11eb-918d-8b7372b97364.png)

3. When I open the list, already connected. but not connected.
![スクリーンショット 2021-02-12 104436](https://user-images.githubusercontent.com/44485074/107728851-8c9fb000-6d32-11eb-81c5-627eb101a100.png)

4. Enter the URL where the node is running. It will connect correctly and the selected value in the list will change to Custom node.
![スクリーンショット 2021-02-12 104547](https://user-images.githubusercontent.com/44485074/107728886-a3460700-6d32-11eb-99cf-a6cf7d5d30c5.png)

5. Enter the URL where the node is not working again. 
![スクリーンショット 2021-02-12 104617](https://user-images.githubusercontent.com/44485074/107729018-fa4bdc00-6d32-11eb-88de-d0d2b2d75e04.png)

6. I am able to sign in.
*However, it is actually connected to the running node that I last entered.
![スクリーンショット 2021-02-12 131021](https://user-images.githubusercontent.com/44485074/107729271-ba392900-6d33-11eb-98b6-3fbb35039f7f.png)

### Which version(s) does this affect? (Environment, OS, etc...)
- Lisk Desktop 2.0.0-beta.1
- Windows 10 20H2 19042.789

**Comment by UsamaHameed** [comment]
Thanks for reporting the issue @lisknonanika. We will fix asap. Additionally, if you are trying to connect to a custom node, you need to have an equivalent Lisk Service node running that connects to your custom node. That is the reason behind the unexpected behaviour.

**Comment by lisknonanika** [comment]
@UsamaHameed 
Thank you. It would be nice to see a message when the connection failed (e.g. because the URL is wrong).
