### ISSUE TITLE
Transactions Filter does not work properly. v2.0.0-beta.1

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3379]
### Expected behavior
The filter works properly.

### Actual behavior
The filters on the transaction page and wallet page do not work properly.

### Steps to reproduce
**Transactions page**
1. Initial display
![スクリーンショット 2021-02-12 170551](https://user-images.githubusercontent.com/44485074/107744277-c3d38880-6d55-11eb-82cc-3d938e5c42dd.png)

2. Filter by date and sender
![スクリーンショット 2021-02-12 170736](https://user-images.githubusercontent.com/44485074/107744332-d8b01c00-6d55-11eb-8098-c9af31275136.png)

There is no change in the content.

**Wallet page**
1. Initial display
![スクリーンショット 2021-02-12 170837](https://user-images.githubusercontent.com/44485074/107744394-f8474480-6d55-11eb-8b49-5ebf5040630b.png)

2. Filter by date
![スクリーンショット 2021-02-12 170918](https://user-images.githubusercontent.com/44485074/107744413-0006e900-6d56-11eb-92de-7631db38565f.png)

Other unrelated transactions will be displayed.
This account has not voted.

### Which version(s) does this affect? (Environment, OS, etc...)
- Lisk Desktop 2.0.0-beta.1
- Windows 10 20H2 19042.789

**Comment by UsamaHameed** [comment]
Thanks for reporting the issue @lisknonanika. We will fix asap.
