### ISSUE TITLE
Add snapshot tests to UI components

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3396]
### Description

Add snapshot tests to all of the UI/representational components

### Motivation

- Snapshots help us quickly identify whether a component would look differently as a result of even rudementary code changes without having to run the app and looking at that particular component
- Once every feature of the app is tested and approved, we can generate snapshots and then changes to those snapshots would quickly identify UI changes some of which might be unintentional
- Reduces time spent in QA

### Acceptance Criteria

Add snapshot tests to all the representational components 

### Additional Information
Jest has support for snapshot testing

**Comment by ManuGowda** [comment]
This issue needs to be groomed and create multiple tasks.

**Comment by ManuGowda** [comment]
We are reconsidering the future wallet requirements, for time being the requirements are not valid.
