### ISSUE TITLE
Forging details are not getting updated realtime in delegates monitoring page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3401]
### Actual behavior

Forging details are not getting updated realtime in the graph, inside round tab and watched tab

![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/3632ff37-e573-4014-bb02-d91363479882)

### Expected behavior

- Delegates forging status graph and grid (Forging time, Round state) should be updated realtime based on blocks forged
- Delegates forging status graph and grid should have only three round state i.e 1. waiting to forge block 2. forged block and 3. missed block

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0-alpha.4 , MacOS

**Comment by isalga** [comment]
The update issue was fix in #3356 . This ticket will solve only the not forging label.

**Comment by sridharmeganathan** [comment]
Reopened this ticket because, realtime values are incorrect

**Comment by UsamaHameed** [comment]
Closing this in favour of #3411.
