### ISSUE TITLE
Application is throwing session timeout message even when i'm not signed to the application

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3402]
### Actual behavior

Application is throwing session timeout message even when user not sign in to the application

### Expected behavior

Application should not send a message to user if he accessing the application without sign-in
Application should send message to user if he is not opt for the auto logout option in the setting page

### Steps to reproduce
Open the  desktop application, goto any monitoring page and be idle for 10 mins, then you will get a notification 
![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/9d1921e5-77aa-4dc9-bc46-7b4b505f1e88)

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0-alpha.4 , MacOS

**Comment by UsamaHameed** [comment]
@sridharmeganathan this is related to #3395. We will fix them together.
