### ISSUE TITLE
Add queue number in delegates monitor page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3422]
### Description
Add queue number to the forging details in the delegates monitor page. 

### Motivation
We would like to enable users to better visualize the delegates in the queue for a round.

### Acceptance Criteria
Connect to betanet and navigate to delegates monitor.

Add a queue number inside the doughnut chart.

![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/78ef8033-d6f0-45a2-bbcf-c6c83c82fd5c)

![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/339c818e-8310-4dff-a2fb-4bda3cf1870c)

**Comment by ManuGowda** [comment]
This issue is resolved in latest release of Lisk Desktop.
