### ISSUE TITLE
Enabling BTC in advanced settings triggers account initialization

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-desktop#3435]
### Expected behavior

- User enables BTC in advanced settings
- Lisk Desktop enables BTC wallet support
- User is able to continue using Lisk Desktop

### Actual behavior

- User enables BTC in advanced settings
- Lisk Desktop shows initialization summary modal
- User is forced to reload and sign in again

<img width="1392" alt="Initialization summary after enabling BTC" src="https://user-images.githubusercontent.com/8068/111917246-46e7ad00-8a7f-11eb-84fa-64888546f6b7.png">

### Steps to reproduce

When using different addresses with diffe

1. Disable BTC in `Settings -> Advanced`
2. Sign into Lisk Desktop using passphase
  - Address affected by issue, `account has BTC balance > 0`
    - https://testnet-explorer.lisk.io/address/16313739661670634666L
  - Address not affected by issue, `account has BTC balance == 0`
    - https://testnet-explorer.lisk.io/address/6938859728177635382L
3. Enable BTC in `Settings -> Advanced`

### Which version(s) does this affect? (Environment, OS, etc...)

- OS: `macOS 11.2.3`
- Version: `1.2.8`

**Comment by UsamaHameed** [comment]
Can't reproduce
