### ISSUE TITLE
Inconsistency in load more functionality throughout lisk desktop

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3441]
### Expected behavior
Load more functionality should be consistent across the application to bring standard

### Actual behavior
Load more functionality is not consistent across the application. This should be discussed and bring alignment before or after v2.0.0 production release

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop v2.0.0-beta.2

**Comment by reyraa** [comment]
Already done.
