### ISSUE TITLE
Create a seed database for development environment

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3449]
### Description

We need to create a seed database to use for development purposes. This helps us test and debug the app locally and is also required to run e2e tests. 

### Acceptance Criteria

- Create a seed database to be used for development purposes
- Should have at least a few transactions of each type
- Should have at least one account that can send an unlock transcation

### Additional information

Lisk Core v3 Snapshot https://github.com/LiskHQ/lisk-service/tree/development/jenkins/lisk-core/snapshots

**Comment by ManuGowda** [comment]
We can use the Lisk Service seed database to bootstrap the Lisk Desktop tests.
