### ISSUE TITLE
Refactor withData HOC to use the active token directly

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3461]
### Description

We should refactor the withData HOC to select/propagate the active token to our api methods instead of passing it manually which results in repitition and bugs.

### Acceptance Criteria

- `withData` should take care of passing the active token itself

**Comment by ManuGowda** [comment]
With new architecture changes this will be addressed. https://github.com/LiskHQ/lisk-desktop/issues/4033
