### ISSUE TITLE
Transaction remains pending confirmation if the block transactions API fails

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3478]
### Expected behavior
Pending transactions should be marked as confirmed as soon as they are added to a block.

### Actual behavior
We listen to blocks event, where the number of transactions are defined. Then we make API calls to receive the list of transactions of the given block, and look for the transactions that belong to host to mark them as confirmed. If this API call fails, we don't try it again. In theory this API call should never fail.

### Steps to reproduce
- Create a new transaction.
- Wait for it to get confirmed.
- Sometimes the API `ttp://service-v5.liskdev.net/api/v2/transactions?block=latest_block_id` returns 404.

**Comment by sridharmeganathan** [comment]
Fixed in rc.0 release
