### ISSUE TITLE
Update percy config

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3481]
### Expected behavior
Percy uses storybook which in turn uses webpack. Since we updated the configs for webpack and updated several build packages, we need to update the webpack config used for storybook as well and make sure percy runs correctly on jenkins. 

### Actual behavior
Percy fails due to a config error.

**Comment by sridharmeganathan** [comment]
This will be addressed in Lisk Desktop Version 3.0.0

**Comment by ManuGowda** [comment]
We need to revisit our visual testing approach, the current infrastructure is outdated for longtime and continue to patch this will take longer time and it won't be a good direction. We will analyse and introduce the visual testing for future release.
