### ISSUE TITLE
Handle loading states gracefully

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3485]
### Description

The app should handle loading states more gracefully. The UI should reflect that things are happening in the background and that the user should wait a bit more. Some parts of the code are heavily dependant on expensive network requests to be completed JIT. 

### Motivation

For better UX.

### Acceptance Criteria

- All loading states should be handled 
- Some placeholder should be shown instead when the app state is `loading`
- TBD

### Additional Information
- For example: skeleton screens: https://css-tricks.com/building-skeleton-screens-css-custom-properties/

**Comment by ManuGowda** [comment]
This issue has been address with v3 implementation
