### ISSUE TITLE
Add navigation to base modal component

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3502]
### Description
The user should have access to navigation buttons from the top bar in modals as well. Since opening and closing modals changes the history, and the user does not have access to the navigation buttons in the modals, it breaks the history stack.

### Motivation
- The user should be able to navigate back and forth between pages.
- Keep the history stack consistent

### Acceptance Criteria
Provide navigation buttons in the base modal component.

**Comment by sridharmeganathan** [comment]
The navigation is working fine. The modal case described above is not a common usecase.

**Comment by ManuGowda** [comment]
Lisk Desktop v3 redesign handles these navigation, hence closing this request.
