### ISSUE TITLE
Add tag selection feature to WithFilter

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3534]
### Description
The WithFilter HOC component should support multi-selectable tags. Users must be able select a custom number of tags from the provided list. [UI Design](https://www.figma.com/file/kNu67yxyOZCJKU21fgFvBl/Multisignature?node-id=357%3A19717)

### Acceptance Criteria
- The HOC should accept a list of options to display as multi-select tags.
- Users must be able to select and un-select each tag individually. 
- Implement according to the design files.

**Comment by ManuGowda** [comment]
We are reconsidering the future wallet requirements, for time being the requirements are not valid.
