### ISSUE TITLE
If official nodes are down, users can't connect to custom node

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3538]
Lisk Dekstop v1.28.0

If all official nodes of Lisk are down, no page is loading when clicking on "Sign in". We just had an incedent where all nodes were down and users were unable to set custom nodes to connect to due to this poor design. Users should be able to set custom nodes in any case. Also I wasn't able to get to the settings page. Nothing happens if I click "settings".

Here's the issue:
![explorer](https://user-images.githubusercontent.com/1260700/117377342-54dc7a80-aed3-11eb-8af8-c3b575f14ef3.gif)

**Comment by JesusTheHun** [comment]
An idea would be to store the latest peers we were connected to, so if the official nodes are down, we are either automatically using backup/known peers or prompted to select one.

**Comment by reyraa** [comment]
this issue is resolved and will be available for external testing with the upcoming release v2.0.0-beta.3.
