### ISSUE TITLE
Ugly error popup if starting Lisk Desktop on a disconnected computer

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3545]
I deactivated my ethernet to see how Lisk Desktop 1.28.1 reacts on it and I get this ugly popup. Maybe this can be handeld better like a message inside Lisk Desktop that says "You are offline." with some button that says "Ok, now take me to the Wallet." or something.

![grafik](https://user-images.githubusercontent.com/1260700/118016004-2cca9c80-b355-11eb-87fb-1ff116f73c66.png)

**Comment by reyraa** [comment]
Thank you @punkrock I've resolve this.
