### ISSUE TITLE
Add Upbit accounts

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3550]
Please add these two accounts from the exchange **Upbit** to Lisk Desktop:

upbit hotwallet: https://explorer.lisk.com/address/3150492547915446148L
upbit coldwallet: https://explorer.lisk.com/address/2206820005532287757L

these are transactions from hotwallet to coldwallet: https://explorer.lisk.com/address/3150492547915446148L?page=1&senderId=3150492547915446148L&recipientId=2206820005532287757L&type=0

accounts confirmed by Upbit user.

![grafik](https://user-images.githubusercontent.com/1260700/118405060-f43d0280-b675-11eb-9ed2-c5e923b2a5fb.png)

**Comment by UsamaHameed** [comment]
@punkrock Please create an issue in the lisk service repository. Lisk Desktop does not maintain the names itself; it uses the names returned by lisk service. Thank you
