### ISSUE TITLE
Add another Binance Hot Wallet

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3552]
This is another Binance Hot Wallet: https://explorer.lisk.com/address/5037006598898191401L
Confirmed by Binance's transaction from Cold Wallet to this Hot Wallet: https://explorer.lisk.com/tx/2613471665507727921

**Comment by UsamaHameed** [comment]
@punkrock Please create an issue in the lisk service repository. Lisk Desktop does not maintain the names itself; it uses the names returned by lisk service. Thank you
