### ISSUE TITLE
Provide users with an easy approach for signing transactions with their second passphrase

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3614]
### Description
The multisignature accounts which have only two mandatory members, some of which are legacy accounts with second passphrase, are commonly used by a single owner for higher security. Users would like to enter their second passphrase to sign the transaction right away. Although this is not the safest approach and we encourage users to sign such transactions on different computers/devices, we should provide a prompt to input the second passphrase for ease of use. 

The second passphrase input must not be visible by default. Users should actively choose to open the dialogue and input their second passphrase.

### Motivation
- Better usability

### Acceptance Criteria
- If an account has exactly two mandatory members, one of which is the account itself, we should consider it as an account with a second passphrase (2P).
- 2P accounts sign in similar to any other account using their primary passphrase. 
- In the summary step of transaction creation (all types) we should add a link that says "Sign using second passphrase right away".
- When clicked, it should open a modal to input the second passphrase. This modal must have a cancel and confirm button.
- Users must be able to copy/download the transaction. Or send it if the their have already inserted their second passphrase.

**Comment by ann-vashchenko** [comment]
I've prepared a design solution [https://www.figma.com/file/kNu67yxyOZCJKU21fgFvBl/Multisignature?node-id=1367%3A33650](url)
