### ISSUE TITLE
Block ID value overlaps Height information on Block details page

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-desktop#3626]
### Expected behavior

The `Block ID` value is shown in a truncated form, as shown in the `Transaction details` modal.

For example:

<img width="1391" alt="Screenshot 2021-06-20 at 14 31 45" src="https://user-images.githubusercontent.com/8068/122674302-cb5be000-d1d4-11eb-96f0-743f9c0b0003.png">

### Actual behavior

The  `Block ID` value overlaps the `Height` information that is next to it.

The following screenshot is at a resolution of: `2784 × 1640`:

<img width="1391" alt="Screenshot 2021-06-20 at 14 31 13" src="https://user-images.githubusercontent.com/8068/122674311-d151c100-d1d4-11eb-9a18-7e58771cdc38.png">

### Steps to reproduce

1. From the sidebar, click on the `Blocks` option
2. Within the `All blocks` listing, click on a block entry
3. Observe the problem described

### Which version(s) does this affect? (Environment, OS, etc...)

`v2.0.0-beta.4`

**Comment by reyraa** [comment]
This issue is already fixed.
