### ISSUE TITLE
Wrong votecast after not confirming the vote queue

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3648]
### Expected behavior

It should cast votes properly.

### Actual behavior

It casts the first vote only. Breaks after that.

### Steps to reproduce

Add a delegate vote to the voting queue, click continue in the voting queue, **DON'T** click confirm. Add another delegate vote. Try to cast the whole queue. Check how many votes were really casted. After that you can't cast more votes until you relog.

### Which version(s) does this affect? (Environment, OS, etc...)

2.0.0-rc.1, Windows 10

Thanks progcppk @ discord for reporting it.

**Comment by reyraa** [comment]
Thank you @przemerr For reporting this bug. We'll fix it with the next rc release.
