### ISSUE TITLE
Filter is not working as expected in transaction monitoring page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3652]
### Expected behavior
In transaction monitoring page, wildcard filter (AND condition) should work when we filter with more than one criteria.

### Actual behavior
In transaction monitoring page, select send transaction type and input amount range and input recipient address. When i try to filter with multiple inputs then it is not working as expected.

### Which version(s) does this affect? (Environment, OS, etc...)
Mac, v2.0.0-rc0

**Comment by isalga** [comment]
@sridharmeganathan Issue is no longer reproducible
