### ISSUE TITLE
Version 1.28.2 for Linux does not launch

### ISSUE THREAD

**Issue by mn851** [LiskHQ/lisk-desktop#3660]
### Expected behavior
Desktop app should open when double clicked or using app launcher to execute.

### Actual behavior
Nothing happens. App is not loaded.

### Steps to reproduce
Try opening the app, never works. Rolling back to 1.27.1 fixes the problem.

### Which version(s) does this affect? (Environment, OS, etc...)
Linux environment. Ubuntu 18.04 LTS.

**Comment by reyraa** [comment]
Thank you for reporting this issue. We'll look into it.

**Comment by UsamaHameed** [comment]
Issue no longer reproducible

**Comment by mn851** [comment]
> Issue no longer reproducible

Not sure what you mean. I'm using Ubuntu 18.04 LTS and I can absolutely reproduce it. I don't consider this issue closed.
