### ISSUE TITLE
Back loop

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-desktop#3672]
### Steps to reproduce

From the `Delegates` page, click on an account. Click on a transaction. It opens a modal. Close the modal. Now click on the back button.

### Expected behavior

You would expect to land on the `Delegates` page.

### Actual behavior

It opens the modal again. If you close and click on `< (back)` again, it opens the modal again.

### Which version(s) does this affect? (Environment, OS, etc...)

2.0.0 rc 2
MacOS

**Comment by UsamaHameed** [comment]
Hey @JesusTheHun, I have already reported this issue and requested a feature here https://github.com/LiskHQ/lisk-desktop/issues/3502

**Comment by JesusTheHun** [comment]
@UsamaHameed hi, nice. I searched for this issue but none of my keyword found me back ^^
