### ISSUE TITLE
Multisignature members' type is not shown correctly in tx summary

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3675]
### Expected behavior
The type of members of a multisignature group must be displayed consistently correct throughout the registration process.

### Actual behavior
Mandatory members might be displayed as optional in transaction summary.

### Steps to reproduce
- I created a multisignature account with 2 mandatory members. On the multisignature account details I see both members as mandatory.
<img width="748" alt="Screenshot 2021-06-30 at 16 45 48" src="https://user-images.githubusercontent.com/666685/124563512-60e7a880-de40-11eb-8d6d-f049969bfa6b.png">

- When I try to send a transaction I see that one of the members is optional.
<img width="741" alt="Screenshot 2021-06-30 at 16 45 20" src="https://user-images.githubusercontent.com/666685/124563531-6644f300-de40-11eb-9aa5-ef9ecf4149c2.png">

- When I sign this transaction from the second account I see both members as mandatory.
<img width="750" alt="Screenshot 2021-06-30 at 16 48 06" src="https://user-images.githubusercontent.com/666685/124563550-6c3ad400-de40-11eb-9e84-287009515494.png">

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-rc.2

**Comment by UsamaHameed** [comment]
Can not reproduce
