### ISSUE TITLE
Change auto logout feature so that it resets the timer on all user activity

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3679]
### Description
The auto logout feature logs the user out after a specific time has elapsed since the last passphrase usage. It does not care for any user activity. 

### Motivation
It should check for user activity instead. The user might be in the middle of an important task and auto logout will result in the user having to go through all the steps again.

### Additional Information
https://github.com/LiskHQ/lisk-desktop/issues/3402

**Comment by sridharmeganathan** [comment]
The current implementation is agreed and accepted.
