### ISSUE TITLE
Trezor signatures valid on Lisk network?

### ISSUE THREAD

**Issue by matejcik** [LiskHQ/lisk-desktop#3704]
Reviewing the LIPs, namely [LIP-15](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0015.md) and [LIP-27](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0027.md), and the signing code [in Lisk](https://github.com/LiskHQ/lisk-sdk/blob/d940c4d85809c39edded5b741d84003b4e0edad3/elements/lisk-chain/src/transaction.ts#L29-L69) versus what we have [in Trezor](https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/lisk/sign_tx.py#L94-L122), it seems that Trezor's code is one or more hard forks behind current Lisk network, and cannot produce valid signatures for the current transaction format.

Yet Lisk Desktop claims Trezor support, and we don't see any users complaining that anything is broken.

I tried to do some testing, but the current version of Lisk Desktop for Linux does not allow me to connect to Testnet (the option is there but selecting it does nothing), and anyway the testnet faucet is timing out so I can't get any tLSK to test with.

Can you clarify from your side the state of the network and validity of the (seemingly legacy?) transaction format that is currently supported on Trezor?

cc @prusnak, @alepop who is the original author of Lisk implementation on Trezor, @hirishh as the author of Liskish Wallet which is recommended for Trezor users

**Comment by hirishh** [comment]
@matejcik Hello,

Testnet is running the new network code. At the moment the current ledger and trezor applications are limited to mainnet only.
We are working to update ledger and trezor apps. Until then, you can't use trezor and/or ledger devices on testnet.

**Comment by matejcik** [comment]
does this mean that Testnet is running a newer version of the network (with
protobuf-like tx encoding) and Mainnet is still on the old unstructured
format?

what is the timeline for switching Mainnet?

Dne út 20. 7. 2021 16:16 uživatel hirish ***@***.***> napsal:

**Comment by hirishh** [comment]
@matejcik Yes. Testnet is running the protobuf-like version and Mainnet still don't. We did the testnet hardfork a couple of weeks ago and we are testing it and I don't know an ETA for the hard fork on mainnet. For this I will let LiskHQ answer.

**Comment by ManuGowda** [comment]
After careful considerations, we have made a conscious decision to remove support for Trezor in Lisk Desktop. 
Marketing team will do the detailed communications in coming weeks.

**Comment by hirishh** [comment]
:man_facepalming:

**Comment by alepop** [comment]
🤦‍♂️
