### ISSUE TITLE
Transactions don't refresh after selecting an account from the searchbar

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3708]
### Expected behavior

It should show transactions for a selected account.

### Actual behavior

It shows transactions from a previous account.

### Steps to reproduce

Go to any account/address page (it can't be the _Wallet_ page), use the searchbar to find a different account/address. Click it. Transactions won't refresh.

### Which version(s) does this affect? (Environment, OS, etc...)

2.0.0-rc.3

**Comment by przemerr** [comment]
While the transaction page is fixed, _Delegate profile_ suffers from the same bug.

**Comment by przemerr** [comment]
@sridharmeganathan not sure if you seen this comment ☝️ , if this require a new issue i can create one

**Comment by punkrock** [comment]
Bug visualized. Delegate infos don't update:
![bookmarkBug](https://user-images.githubusercontent.com/1260700/130681128-8cefaa32-6420-4eba-91f9-2e2c2e6ae549.gif)

**Comment by sridharmeganathan** [comment]
Hello @punkrock,

Thank you for pointing this issue. I will create a separate and fix it in the future release.
