### ISSUE TITLE
Edit vote window disappears after selecting the vote amount and hovering outside its boundaries

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3709]
### Expected behavior

It shouldn't disappear

### Actual behavior

It disappears

### Steps to reproduce

Go to _edit vote_ window, select the amount while having the left mouse button clicked, hover outsides its boundaries, release the left mouse button.
![desktop](https://user-images.githubusercontent.com/25085095/126468133-a9b4b9a5-fc6a-4dc2-ae6e-f9ac3ec8be11.gif)

### Which version(s) does this affect? (Environment, OS, etc...)

2.0.0-rc.3

**Comment by UsamaHameed** [comment]
Hey @przemerr, this is the default browser behaviour for mousedown and mouseup events. `mouseup` is considered equivalent to a `click` event at the location where you do it, so here essentially you are clicking on the backdrop of the dialog, the default behaviour of which is to close the dialog.
