### ISSUE TITLE
Voters in the Delegate profile should be clickable

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3722]
### Description
Voters in the Delegate profile should be clickable
![image](https://user-images.githubusercontent.com/25085095/127695243-d995927f-ee80-4cfb-a7f3-11b80ab648b9.png)

### Motivation

There's no fast way to get to a voter profile, addresses are truncated, also the filter doesn't seem to work.

**Comment by sridharmeganathan** [comment]
Thank you. We will validate and fix it in the future release
