### ISSUE TITLE
Wrong type of member for multi-signature.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3728]
### Expected behavior
“Mandatory” and “Optional” must be displayed correctly.

### Actual behavior
Transaction summary is displayed incorrectly.

### Steps to reproduce
Open the Transaction Summary with an account that has only two mandatory keys.

https://testnet-service.lisk.io/api/v2/accounts?address=lsky9hba8w8wc25ohkzjsj77hwnbctjukunmhwbp2

One of them will be displayed as optional.
![B14F75E6-0714-4576-8122-DBB0F62DDA98](https://user-images.githubusercontent.com/44485074/128970696-ce684773-8486-4332-ba68-b078fbe5b802.jpeg)

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop 2.0.0

**Comment by sridharmeganathan** [comment]
Thank you.  we will check this issue.

**Comment by ManuGowda** [comment]
@lisknonanika I tried to reproduce the above issue by registering multi-signature group, I was not able reproduce the issue. Could you please provide me the steps to reproduce.

**Comment by lisknonanika** [comment]
@ManuGowda Thank you for your reply.
I've also created a multi-signature account several times after this issue, but can't seem to reproduce it.

**Comment by ManuGowda** [comment]
Closing this issue as it is no longer reproducible
