### ISSUE TITLE
Apply new styles for the dark mode components

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3730]
### Description

Adapt new styles for the below dark components as per the [proposed design
](https://www.figma.com/file/6ud7losj7pgiT8rYXrb28j/Design-improvements-for-V2.0.0?node-id=0%3A1)
1. Apply new avatars and illustrations

2. Balance graph in wallet page

3. Priority component in all transaction pages

4. New Color themes  for transaction monitoring charts

5. New Color themes for delegates monitoring page

6. Apply new styles for delegates profile page

7. Apply new style for register multi-signature account pages

 ### Acceptance criteria
- Apply the changes as per the proposed design

**Comment by ann-vashchenko** [comment]
Hi @isalga I've noticed some minor issues: 

**1. Transaction icon in the sidebar shouldn't be blue** 

<img width="63" alt="Screenshot 2021-09-09 at 14 28 33" src="https://user-images.githubusercontent.com/61688877/132691723-73c78a21-5b23-4589-8ec2-f6ac46de7116.png">

**2. It seems that not all illustrations were changed. For example:** 

<img width="335" alt="Screenshot 2021-09-09 at 14 34 53" src="https://user-images.githubusercontent.com/61688877/132691906-ef5b2df9-236d-4234-9614-be87bfa9eb20.png">

**3. Slider differs from the design** 

Actual result: 
<img width="233" alt="Screenshot 2021-09-09 at 14 31 43" src="https://user-images.githubusercontent.com/61688877/132692043-b88b0d45-11e0-4356-a108-49458b79520d.png">

Design: 
<img width="385" alt="Screenshot 2021-09-09 at 15 11 47" src="https://user-images.githubusercontent.com/61688877/132692125-024dac12-3920-435b-99ec-cbe52f149923.png">

**4. Label background is grey but should be blue with opacity** 

Actual result: 
<img width="105" alt="Screenshot 2021-09-09 at 14 32 38" src="https://user-images.githubusercontent.com/61688877/132692392-6043d6fe-99a6-4dc2-9ec9-989695dbad3d.png">

Design: 
<img width="144" alt="Screenshot 2021-09-09 at 15 14 12" src="https://user-images.githubusercontent.com/61688877/132692485-c24fd1b7-2a08-4661-ac7a-8dea0fcc2934.png">

**5. Incorrect color of icons** 

Actual result: 
<img width="36" alt="Screenshot 2021-09-09 at 14 33 48" src="https://user-images.githubusercontent.com/61688877/132692648-b4479f2b-1a54-496e-8867-5b80b272e550.png">

Design: 
<img width="59" alt="Screenshot 2021-09-09 at 15 15 42" src="https://user-images.githubusercontent.com/61688877/132692761-817d76b4-758c-4131-a850-018111546652.png">

**6. Margin should be 10 px and they should be consistent across the app** 

<img width="705" alt="Screenshot 2021-09-09 at 14 35 42" src="https://user-images.githubusercontent.com/61688877/132693143-7d79677b-7716-4117-89c6-8a07f13c173b.png">
