### ISSUE TITLE
Improve e2e test suite

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3734]
### Description

The below points should be addressed to fix the unstable and failing e2e test

- We have duplicated step definitions and many step definitions are defined for a specific feature while they can be in common feature to prevent duplication
- We have step definitions that perform several assertions, increasing the chance of code duplication.
- Accounts and transactions are used in common, thus changing one feature can affect the features that run next.
- All tests run against a single machine. Parallelising can decrease the run times by about 50%
- Wallet filters and Send feature are unstable

### Acceptance Criteria

- We should move as many step definitions as possible to common steps.
- Each step should only assert one goal. We should refactor the complex step definitions down to several steps with a single assertion.
- We should create accounts specific to each feature so the result of feature don't affect the next features.
- We should determine if Cypress allows running features with parameter. If not, we should break cypress config into two and run e2e test only using Jekins parameter and against master
- We should investigate running e2e test on multiple machines in parallel.
- We check if defining feature specific accounts help, if not, we refactor these features and resolve fragile tests.

**Comment by sridharmeganathan** [comment]
@reyraa to update the title and scope of this issue.

**Comment by eniolam1000752** [comment]
Pending work

- refactoring send.feature file
- refactoring vote.feature file

**Comment by eniolam1000752** [comment]
Requirements from me

- find a way to parameterize serivceUrl in config.json for cypress
- provide snapshot DB
- provide a parameter that enables DevOps to know when lisk-service is up and running
