### ISSUE TITLE
No option available to close lisk-desktop from top menu

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3741]
### Expected behavior
User should have an option to close the application by selecting menu item from the top menu and also by pressing CMD+Q keys 

### Actual behavior
The option to exit Lisk Desktop through the top menu doesn’t exist. The command CMD+Q also doesn’t work

### Steps to reproduce
![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/e57da556-e4e0-444c-b079-419d258a4c59)

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0

**Comment by karmacoma** [comment]
@sridharmeganathan As of v2.0.1, this option is restored.

<img width="1680" alt="Screenshot 2021-09-14 at 19 04 22" src="https://user-images.githubusercontent.com/8068/133302066-0125bb19-dbdb-45d0-955f-931373d5d673.png">

**Comment by ManuGowda** [comment]
Verified the issue as Oliver mentioned, closing the issue.
