### ISSUE TITLE
Improve signing of multi-signature

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3756]
### Description

This is not about the process itself but about a minor change i suggest. many people already reported that when they sign their multi-sig transaction, they forget to click "send" at the end, because they see the green check mark and think they are done. please remove the green checkmark and make clear to users they need to click send.

![image](https://user-images.githubusercontent.com/1260700/131486417-f54b2628-0a60-424b-bac2-baccbbb0733b.png)

### Acceptance Criteria

- Should update sign multi-signature illustration according to new [designs](https://www.figma.com/file/FvOfHGyYPUclnv6FNUdumV/?node-id=12%3A4679)
- Should update confirm multi-signature illustration according to new [designs](https://www.figma.com/file/FvOfHGyYPUclnv6FNUdumV/?node-id=12%3A4679)
- Test multi-signature transaction flow and other transaction flow

**Comment by reyraa** [comment]
Good point @punkrock . I'll ask @ann-vashchenko to take a look.

**Comment by ann-vashchenko** [comment]
Good point @punkrock. I'll update the illustration.
