### ISSUE TITLE
Popup windows inside the wallet should not close when release mouse button

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3757]
A very annoying "bug" is this: You mark something inside the formular and if you are releasing the mouse button outside of the popup window, it closes tje popup window and you have to start all over again. It should not close if you started pressing the mouse button inside the popup window and release it outside. it should only close if you click outside the pop window. or it should not close at all until you click the X on top right.

![copy-issue](https://user-images.githubusercontent.com/1260700/131487371-726d1102-d91e-44c6-8d79-8fa7393a0967.gif)

**Comment by reyraa** [comment]
Thanks @punkrock . We'll take a look.

**Comment by przemerr** [comment]
https://github.com/LiskHQ/lisk-desktop/issues/3709
i've already submitted it, got this response.

**Comment by punkrock** [comment]
> #3709
> i've already submitted it, got this response.

Then there must be some other way because this happens to so often and it is always really annyoing. I would prefer to click on the [X] to close the window and not have the option to click everywhere to close the popup windows.

**Comment by przemerr** [comment]
Yeah, I agree. Haven't encounter similar behaviour or any website.
