### ISSUE TITLE
Store custom node URL permanently

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3762]
### Expected behavior
If I switch from custom node to "testnet" or "mainnet" and want to go back to custom node, the URL is gone. It should be stored and available after I was logged in on "testnet" or "mainnet".

### Actual behavior
![missing-custom-node-url](https://user-images.githubusercontent.com/1260700/131656253-45afcbb0-3cae-4ee9-bd8b-c302a1145c39.gif)

**Comment by sridharmeganathan** [comment]
Thanks the suggestion @punkrock. We will implement it in the next release v2.1.0
