### ISSUE TITLE
Pressing enter after entering passphrase should lead to sign in

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3766]
after entering the passphrase users press return and want to get logged in but preesing return opens the network switcher. please change this.

![login](https://user-images.githubusercontent.com/1260700/131881200-47b4b523-4423-4caa-af99-2db645ea2dc5.gif)

**Comment by ManuGowda** [comment]
@punkrock thank you for reporting the issue. We will address this issue in our upcoming release.

**Comment by ManuGowda** [comment]
@punkrock closing this issue in favour of https://github.com/LiskHQ/lisk-desktop/issues/3740. The requested behaviour will be fixe in 3740.
