### ISSUE TITLE
Inability to unlock other tokens, when part of the tokens is locked due to PoM.

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3767]
Since Lisk-Desktop is always trying to unlock all the available tokens at once, if part of the locked tokens are locked due to PoM, user is not able to unlock regular tokens, because the transaction gets rejected.

Steps to reproduce

Vote for a PoMed delegate on testnet (_test_face_), vote for a regular delegate. Unvote both, try to unlock after 6h.

**Comment by ManuGowda** [comment]
@przemerr thank you for reporting, this issue will be resolved once LiskHQ/lisk-service#735 addresses the issue.

**Comment by ManuGowda** [comment]
This issue is resolved with Lisk Service 0.4.5 https://github.com/LiskHQ/lisk-service/releases/tag/v0.4.5
