### ISSUE TITLE
Warn users if they are trying to cast a vote for a currently punished delegate

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3768]
If a user adds a vote to a delegate that is currently punished there should be a very clear and loud warning that the user's LSK will be locked for X days and that the vote will be counted for the delegate's vote weight AFTER this time and UNTIL then, it has no effect on the delegate's vote weight.

Regarding "X days": `put here the remaining calculated punishment time of the delegate`

### Acceptance criteria

- Meet the proposed [design]( https://www.figma.com/file/FvOfHGyYPUclnv6FNUdumV/Improvements-(September-2021)?node-id=41%3A5960)

**Comment by ann-vashchenko** [comment]
Hello @punkrock thank you for your feedback. We'll work on it.
