### ISSUE TITLE
Empty row when clicked on stakes load more button

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#3777]
### Expected behavior

Voters tab should never show empty row when clicked on Load more button.

### Actual behavior

<img width="1307" alt="Screenshot 2021-09-07 at 11 02 44" src="https://user-images.githubusercontent.com/6449871/132641394-c992fd8e-11f2-483a-bd0b-89844203d54d.png">

### Steps to reproduce

- Search for delegate `liberspirita` or any delegate who has more than 20 votes
- Navigate to delegates profile 
- Click on `voters` tab and click `Load more` (sometimes empty row might not appear, try to check with delegates having more votes to get reproduce the issue)

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.x

**Comment by sridharmeganathan** [comment]
We consider this as a low priority issue. We will address it in the later releases.

**Comment by ManuGowda** [comment]
This is no longer an issue 
![Screenshot 2023-05-02 at 12 19 44 PM](https://user-images.githubusercontent.com/6449871/235641455-0ed03278-822e-4fed-9d23-1ba027657258.png)
