### ISSUE TITLE
Unable to connect to the node

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#3788]
### Expected behavior

Desktop should allow users to login once the network is connected.

### Actual behavior

![node](https://user-images.githubusercontent.com/6449871/133319369-b749c88c-0eac-4f74-8518-5d843c8ef526.png)

### Steps to reproduce

1. Download Lisk Wallet
2. Turn off wifi
3. Enter sign in and enter passphrase
4. Turn on wifi
5. Switch network to mainnet
6. If you click on sign in then you will notice the error

### Which version(s) does this affect? (Environment, OS, etc...)
2.x.x

**Comment by swlengyel** [comment]
Hello,

I am experiencing a very similar issue unfortunately.

After I have tried to login using my Ledger I get the following error...

![image](https://user-images.githubusercontent.com/91001470/133917385-269d8a97-494e-43c5-b6b5-0169e82594be.png)

This is after I have successfully authenticated and verified the address on my Ledger hardware wallet.

**Comment by punkrock** [comment]
@swlengyel There is no  support for Ledger at the moment. You need to wait for Lisk Desktop 2.2.0 for native support. In 2.1.0 they will add a feature that allows you to use your Ledger restore seed to access your funds.

Regarding your issue, about "unable to connect to the node", you should try these steps:

1. Go to Settings
2. Enable "Network switcher"
3. Click "Sign in"
4. In the "Network" drop down menu switch to "Mainnet"
5. Add your passphrase and click "Sign in"

**Comment by ManuGowda** [comment]
This issue needs grooming and since the area of impact is higher, we need to discuss and groom the issue better before we can work on this.

**Comment by ManuGowda** [comment]
We are moving this issue to product backlog and with Lisk Desktop 3.0.0 release we will refactor the login components, as part of 3.0.0 implementation we will do login improvements.

**Comment by ManuGowda** [comment]
Lisk Desktop 3.0 no longer have login feature hence closing this issue.
