### ISSUE TITLE
Unhandled error when remaining balance below 0.05 after a vote

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3792]
### Expected behavior

User shouldn't be allowed to cast a vote if the remaining balance after the vote is lower than 0.05.

### Actual behavior

User can cast a vote, but the transaction will fail, without saying why.

### Steps to reproduce

Vote with an account with balance that will be less than 0.05 after making a vote.

### Which version(s) does this affect? (Environment, OS, etc...)

Desktop 2.0.1

**Comment by ManuGowda** [comment]
@przemerr could you please provide more inputs on the steps to reproduce. 

With current implementation in oder to case vote, you should have minimum of 10LSK and also it should be multiples of 10. I am not sure how you were able to cast vote 🤔

**Comment by przemerr** [comment]
Create an account, transfer 100.05 LSK there, vote for someone with 100 LSK.
