### ISSUE TITLE
Change bookmark accounts from old to new addresses

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3793]
Currently old bookmarks still shows the old addresses. It should automatically switch to new address system. Otherwise people have to remove their bookmarks and add them new. Not a drama, but would be nice to have this done automatically.

**Comment by ManuGowda** [comment]
Lisk Service does not provide legacy address for all the accounts, due to this lack of information availability its harder to migrated all the bookmarks from legacy to new address.

**Comment by reyraa** [comment]
The logic is implemented but there is an style issue which we have to resolve. The tooltip is not visible.

**Comment by ManuGowda** [comment]
@ann-vashchenko can you please share the screenshot

**Comment by ann-vashchenko** [comment]
![Bookmarks uninitialized accounts tooltip](https://user-images.githubusercontent.com/61688877/153579938-a489f828-adf6-4761-b44e-57a92d608f80.png)

**Comment by reyraa** [comment]
Currently we can not extract the new address from the old one, and the Service account endpoint doesn't provide such a functionality. 
Given the above, the current implementation is all we can do. I think we should limit this ticket to "Add a tooltip according to the design" .
