### ISSUE TITLE
Improve transaction failed reporting

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#3799]
### Description

Improve transaction failed reporting for better error reporting which intern helps with addressing the issue

### Motivation

Whenever a user fail to create a transaction, the error report sent to `hubdev@lisk.io` does not contain useful information with regards to error. Having a useful information with regards to error is key to resolving the issue. 

### Additional information

**Current bug report**

![Email bug](https://user-images.githubusercontent.com/6449871/133596736-c9e10826-b37b-4858-9c45-b61bae392204.png)

- Include error message along with error code

**Comment by JesusTheHun** [comment]
Maybe you should allow the collection of such errors instead of asking to send an email.
A modal with a button `send the error report`  and a collapsed block that contains the data to be sent would be great from a UX perspective but also from security/transparency perspective

**Comment by reyraa** [comment]
@JesusTheHun Good idea. We'll consider this for v3.0.0. For now, I'll try to add some more info the the email so we can better help users.
