### ISSUE TITLE
Warn voters about the risk of voting.

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3812]
Voters want to get infos about the risks of voting. Like how long their LSK will be locked if a delegate they vote for gets punished. Read from here: https://discord.com/channels/405002561775599619/885169534066118716/890269169398976602

**Comment by sameersubudhi** [comment]
Also, as suggested by the user, consider adding a warning footnote below the Unlock screen in Lisk Desktop:
```
Unlock timers may vary when Lisk-BFT protocol is applied
```

Ref: https://discord.com/channels/405002561775599619/885169534066118716/890287602165510254

**Comment by ManuGowda** [comment]
This issue is addressed with https://github.com/LiskHQ/lisk-desktop/issues/3768
