### ISSUE TITLE
Design issue in create new account page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3813]
### Expected behavior
Design should aligned with the approved design 

### Actual behavior
The design is not aligned with the approved design
![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/1a27c8c8-0fd9-4a08-865f-e062b6cc1f90)
### Steps to reproduce
- select sign in button
- select 'create it now' link button in Sign in with a Passphrase page

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.2

**Comment by reyraa** [comment]
@sridharmeganathan I can't reproduce this issue against `development` or `v2.0.2`. Which OS did you tested?

**Comment by sridharmeganathan** [comment]
@reyraa I noticed when i was testing it in Mac OS
