### ISSUE TITLE
Fix issues identinied by DeepScan

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3819]
[DeepScan](https://deepscan.io/dashboard#view=project&tid=6759&pid=8871&bid=113511) has identified code quality issues categorized as follows:

Number of issues found: 1 (Q1 1). 
- High impact: 0 (Q1 0) 
- Medium impact: 0 (Q1 0) 
- Low impact: 1 (Q1 1)

Issues by DeepScan categories: 
- Error: 0 
- Code quality: 1 
- ESLint: 0

Type of errors found by DeepScan: 
- React useless property types

To maintain our code quality and prevent bugs, we'd like to fix the above issues in a timely manner.

**Comment by ManuGowda** [comment]
@gadjacobs  there seem to be no more deep scan issues, please cross check branches, development, main and release/2.2.0 and if we have nothing to fix we can close this ticket.

**Comment by gadjacobs** [comment]
There are no more deepscan issues and this ticked can be safely closed.
