### ISSUE TITLE
Newsfeed source URL

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-desktop#3839]
### Description

Update the newsfeed source URL to use the same source that Lisk Service used for blockchain data, broadcasting transactions, etc.

### Acceptance Criteria

- Lisk Desktop uses the same relative URL `/api/v2/...` for newsfeed and the same host
- Lisk Cloud references are removed from the project

**Comment by reyraa** [comment]
Resolved by #3839
