### ISSUE TITLE
Can't send tokens using public key

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3864]
### Expected behavior
According to the placeholder, The recipient input in the send screen should accept public keys.
If we technically can't accept public keys, we should fix the placeholder.

### Actual behavior
If you paste a public key in the recipient field it will display the following error:
> Provide a correct wallet address or the name of a bookmarked account 

### Which version(s) does this affect? (Environment, OS, etc...)
Development

**Comment by ManuGowda** [comment]
Resolved

![Screenshot 2022-04-28 at 7 25 28 PM](https://user-images.githubusercontent.com/6449871/165811918-d606b165-d789-4d81-a7c4-c368c506c057.png)
