### ISSUE TITLE
Two delegates marked as "forging now" at the same time 

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3866]
### Expected behavior
If you navigate to the delegates monitor page and look at the in round delegates, there should always be maximum one delegates whose forging time is "Now".

### Actual behavior
Occasionally two delegates are marked as (forging) "Now". This is because one of them is has started forging 5 seconds ago, and the other will forge in 5 seconds. Therefore the current logic marks both of them as (forging) now. This wouldn't happen if the forging times were 4 seconds ago and 6 seconds later. It only happens if the times are 5 second ago and 5 seconds later.

### Steps to reproduce
Open delegates page and watch the in round delegates for a couple of minutes.

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0-beta.0

**Comment by ManuGowda** [comment]
This domain endpoint and implantation is updated in v3 and we will retest this behaviour during beta phase and create issue if still exits, for now this issue is no longer reproducible.
