### ISSUE TITLE
Search for delegates username should navigate to delegate profile

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3868]
### Expected behavior
If I search for a delegate username, I expect that
- The search input displays the username.
- If I click on a result, it takes me to the delegate profile tab of the given account.

### Actual behavior
- The address of the searched delegate is displayed in the search box.
- If I click on it, it takes me to the transactions tab of said account.

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0-beta.0

**Comment by ManuGowda** [comment]
This is a duplicate issue https://github.com/LiskHQ/lisk-desktop/issues/4023
