### ISSUE TITLE
Custom node URL typing bugged

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#3878]
### Expected behavior
It should not try to connect while I am typing.

### Actual behavior
![bug](https://user-images.githubusercontent.com/1260700/138245144-b9176347-6175-47ad-a0b2-c9fdce7d8b8e.gif)

### Which version(s) does this affect? (Environment, OS, etc...)
Windows 10
Lisk Desktop 2.1.0-beta.1

**Comment by eniolam1000752** [comment]
Unable to replicate this issue as it seems this [PR](https://github.com/LiskHQ/lisk-desktop/pull/4052#issue-1097727536) already resolves it.
