### ISSUE TITLE
Make more columns sortable

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#3879]
### Description
It would be nice if all columns on the Transactions, Blocks, Accounts and Delegates pages are sortable. Currently only specific columns are sortable.

### Motivation
Even though there are two dedicated explorers now, a lot of users will only be using Lisk Desktop. The sorting functionality was there before in the old explorer, and now that it moved to Lisk Desktop it feels like a regression.

**Comment by ManuGowda** [comment]
Due to recent changes to protocol and the way we index the data, this will not be feasible hence closing. If possible in the future we can improve these minor improvements based on service improvements.
