### ISSUE TITLE
Make it possible to open multiple Lisk Desktop instances simultaneously 

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#3880]
### Description

Make it possible to open multiple Lisk Desktop instances simultaneously. Currently you can only have one instance open at a time.

### Motivation

There are multiple reasons for wanting this feature, but the biggest one is probably the signing of multiple multisig transactions at the same time. Let me explain what the current workflow is for signing 5 multisig txs:

1. Open Lisk Desktop
2. Sign in with passphrase A
3. Create transaction and save it locally
4. Sign out
5. Sign in with passphrase B
6. Load the multisig tx, sign and then send it
7. Log out
8. **Repeat the whole process another 4 times....** 👎

If you create them all at the same time, and then sign / send them all in sequence afterwards, the last 4 txs will be rejected because they contain the same nonce as the first. As you can see this is quite troublesome.

#### Solution: multiple instance

It would be great if a user could have two instances open, both logged in with their own passphrase, and then just go through the workflow without having to sign in and out all of the time.

### Additional Information
Lisk Desktop (version 2.0.2)
MacBook Pro (13-inch, M1, 2020)
MacOs Big Sur (version 11.6)

**Comment by ManuGowda** [comment]
With the introduction of objective https://github.com/LiskHQ/lisk-desktop/issues/4035, users will be able to add multiple accounts to the wallet and easily switch between them efficiently. Lisk Desktop 3.0 release will address this problem, so closing this issue for now.
