### ISSUE TITLE
Make the whole process of un-voting and unlocking more clear UX wise.

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#3881]
### Description

Make the whole process of un-voting and unlocking more clear UX wise.

### Motivation

It is currently not clear enough how to unlock your LSK tokens. There are users coming into the chat almost daily asking about how to do this. Even I found it a bit confusing at first, while I am a pretty experienced user.

One of the biggest problems is that the Unlock button does not look like an actual button. It would greatly help if this component got a restyle, with potentially some more highlighting on the moment where a user can submit an unlock tx (6 hours after the unvote tx). Perhaps some shiny outline, designed to grab their attention.

Also, the fact that the unlock tx is necessary in the first place should be made more clear. Users are often not aware this exists.

**Comment by ann-vashchenko** [comment]
Hello @Lemii thank you for your feedback. We'll work on this improvement.

**Comment by ManuGowda** [comment]
This issue will be addressed by
https://github.com/LiskHQ/lisk-desktop/issues/4466
https://github.com/LiskHQ/lisk-desktop/issues/4425
