### ISSUE TITLE
Transaction API does not support publickey filter parameter

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3892]
### Description
The transaction API does not support public key filter parameter. Once called by this filter, it throws the following error which is anticipated:
> getTransactions: Dropped recipientAddress parameter, it’s invalid. 0792fecbbecf6e7370f7a7b217a9d159f380d3ecd0f2760d7a55dd3e27e97184

### Motivation
Enable filtering transactions by sender or recipient public key.

### Acceptance criteria
- The `publicKey` must be added to the API valid parameters list.
- Values must be validated before sent to Service.
- The Transactions monitor page should accept public keys to filter transactions.

Nice to have:
- The send page should accept public keys in the recipient field.

**Comment by soroushm** [comment]
now its working with address it may invalid issues we will test it later

**Comment by ManuGowda** [comment]
Lisk Service transaction endpoint no longer supports filtering by publickey hence closing this issue.
