### ISSUE TITLE
Go To Confirmation button cropped off on small screens

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#3893]
### Expected behavior
When creating a transaction, while using a small screen, I should be able to scroll down to the bottom of the modal to use the Go To Confirmation button.

### Actual behavior
Due to the small screen the button is cropped off and there is no scroll bar, making it impossible to send the transaction.

### Steps to reproduce
- Open Lisk Desktop
- Sign in
- Press send LSK
- Decrease the height of the window to hide the button
- Try to navigate to the bottom :)

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop (version 2.0.2)
MacBook Pro (13-inch, M1, 2020)
MacOs Big Sur (version 11.6)

**Comment by przemerr** [comment]
Other modals are also affected.
From one of the users from discord:


<img width="1280" alt="Screenshot_2022-12-04_at_10 23 33" src="https://user-images.githubusercontent.com/25085095/205661075-58d1f982-59a3-4f67-b20a-ce585fd673c7.png">

```
Hello, I'm using a macbook 13" and I can't scroll down below the "or"
In order to validate vote change right away with 2nd passphrase
Instead, since I can't zoom out I need to connect 2nd account, import ans validate json
Takes longer 😐
(and all good with output throught extra screen, all elements displayed and accessible 🤙)

**Comment by soroushm** [comment]
design is changed need to revolution the ticket
