### ISSUE TITLE
Update news feed response format

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-desktop#3894]
### Description

Lisk Service `0.5.0-rc.0` introduces a new JSON response format.

Please make sure it works with the client and follow the official [documentation](https://github.com/LiskHQ/lisk-service/blob/v0.5.0-rc.0/docs/api/version2.md#news-feed-aggregator).

### Acceptance Criteria

- Client uses the right format

### Additional Information

Please use the staging environment for testing.

https://mainnet-service-staging.lisk.io/api/v2/newsfeed

**Comment by reyraa** [comment]
Resolved by #3839
