### ISSUE TITLE
Resolve API and network related todos

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3902]
### Description

Resolve todos regarding API params, responses and Network configurations. Create tickets if a dependency is found and mention the ticket in the todo.

- src/store/actions/bookmarks.js
- src/components/screens/wallet/delegateProfile/index.js
- src/store/middlewares/network.js

### Acceptance Criteria

- Should resolve all the todos from the above list
- Should add unit/e2e for resolving the todos

**Comment by ManuGowda** [comment]
please speak to @reyraa and get more inputs before start working on this issue, re-esimate if required.
