### ISSUE TITLE
Resolve HW todos

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3903]
src/components/screens/lockedBalance/transactionStatus/transactionStatus.js
src/components/screens/votingQueue/result/result.js
src/components/screens/multiSignature/result/result.js
src/components/screens/reclaimBalance/modal/status/status.js
libs/hwManager/index.js

**Comment by ManuGowda** [comment]
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/3661
