### ISSUE TITLE
Windows opens a new instance of the Lisk application every time a custom protocol link is opened.

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#3923]
### Expected behavior
If there is an already existing window, if a custom protocol link is opened, it should restore the window and navigate to the link.

### Actual behavior
Every time the link is visited, it opens a new instance of the application.

### Steps to reproduce
- Visit a custom protocol link (e.g [lisk://wallet/send?recipient=lsktd3opwn38pbcqb2fg2tjnzux3psw85e7va557q&amount=25&reference=thanks](lisk://wallet/send?recipient=lsktd3opwn38pbcqb2fg2tjnzux3psw85e7va557q&amount=25&reference=thanks).
- Visit the same link above (or another) without closing the first window.

### Which version(s) does this affect? (Environment, OS, etc...)
Windows 10, v2.1.0

**Comment by ManuGowda** [comment]
Unable to reproduce this issue in v2.3.0
