### ISSUE TITLE
Users unable to vote more than 2 delegates at same time

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#3940]
### Expected behavior

At any given point in time users can vote 10 unique address/account.

For a given vote transaction users should be able to:

 - Upvote upto 10
 - Downvote upto 10
 
Info: https://github.com/LiskHQ/lisk-sdk/blob/2593d1fe70154a9209b713994a252c494cad7123/framework/src/modules/dpos/transaction_assets/vote_transaction_asset.ts#L81

Note: `Delegate address must be unique` among Upvote and Downvote

### Actual behavior

Unable to vote more than 2 delegates in one transaction. Error `You can't vote for more than 10 delegates.`

<img width="634" alt="Screenshot 2021-11-19 at 23 09 48" src="https://user-images.githubusercontent.com/6449871/142698036-f0f7f680-3bea-4e04-8843-b32be64717ed.png">

### Steps to reproduce

- Add votes to more than 2 delegates
- Open `Voting queue modal`
- Observe the error `You can't vote for more than 10 delegates.`

### Which version(s) does this affect? (Environment, OS, etc...)

2.1.0

**Comment by reyraa** [comment]
I suspect you have already voted 8 or 9 delegates. Therefore you see this error. Although I must agree there's a UX issue with the current error handling which we must resolve. 

@ann-vashchenko many of our users seem to make this mistake. They think they should be able to vote for up to 10 delegates here, while they can't. Cause they've already voted for some other delegates.
I think we should display the current/used number of votes, and the make the remaining votes clear.
