### ISSUE TITLE
Improve register multisignature group transaction validation

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3978]
### Description
Lisk Desktop accepts the following configurations for a multisignature group which cause broken or confusing user experience as explained below:

- A. The required signatures number is equal to the number of mandatory members, but there are optional members too.
    - In this case the optional members never get to sign.
    - If an optional member signs the transaction before at least one mandatory member, the transaction becomes invalid.
- B. The required signatures number is equal to the number of mandatory and optional members.
    - The transactions need to be signed by every single member, practically turning optional members into mandatory. 
    - This is not a blocking bug. But it leads to a confusing UX. 
    - I believe we should make sure users set all members as mandatory in this case.

### Additional Information
Lisk Core currently accepts transactions that leading to above issues, but Lisk Desktop should add an additional validation layer to prevent registration of such groups.

### Acceptance criteria
Assuming:
- `mm` -> number of mandatory members 
- `om` -> number of optional members 
- `rq` -> number of required signatures

Validations:
**If `mm == 0` and `om > 0`**
Throw an error that the optional members are essentially mandatory members with the current configurations. Users have to mark all of them as mandatory to proceed. Otherwise we will end up with case B.

**If `mm > 0` and `om > 0`**
We should have `mm < rq < mm + om`. Otherwise we will end up with case A.

**If `mm > 0` and `om == 0`**
We should have `rq == mm`.

**Comment by AndreasKendziorra** [comment]
> If `mm == 0` and `om > 0`
> Throw an error that the optional members are essentially mandatory members with the current configurations. Users have to mark all of them as mandatory to proceed. Otherwise we will end up with case B.

But that should only be the case if `om==rm`, right?
