### ISSUE TITLE
Lisk Desktop quits unexpectedly when closing it on the MacOS

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#3985]
### Expected behavior
Lisk Desktop should close without any errors when you close the app.

### Actual behavior
Lisk Desktop throws the error 'Lisk quit unexpectedly' when you close the app.

### Steps to reproduce
- Open Lisk Desktop
- Close Lisk Desktop (File > Quit or Command + Q shortcut)

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop (version 2.2.0 beta)
MacBook Pro (13-inch, M1, 2020)
MacOs Big Sur (version 11.6)

**Comment by reyraa** [comment]
The solution is described here:
https://www.electronjs.org/blog/apple-silicon/
