### ISSUE TITLE
Users should be able to see their balance info

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4006]
### Description
In the sprint of blockchain transparency, users should be able to see the full information about their balance. At the moment we show the available balance for all account, but the locked balance info only for the account with which the user is logged in.
We should show this information for all accounts. Although we should make sure the view is not confusing.

### Motivation
Display all useful information of the account

### Acceptance criteria
Users should be able to see:
- The available balance of all accounts (the active account and other ones)
- The total locked balance of the active and other accounts.
- The details of locked balance in a dedicated space.
Users should only be able to send unlock transactions from the wallet page for the active account. For all other account, they should only be able to see the locked balance info.

**Comment by ManuGowda** [comment]
The design is ready.
