### ISSUE TITLE
Dark mode issues in 2.2.0-beta1

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4010]
### Which version(s) does this affect? (Environment, OS, etc...)

Mac, 2.2.0-beta.1

1- Tooltip guides colors don't match with chart (High priority, it will be done in https://github.com/LiskHQ/lisk-desktop/issues/4015)
![Screenshot 2021-12-14 at 11.26.04.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/175b1ba9-91d0-4b7e-8abf-b704e74d579f)

2- Inconsistent border color in inputs and buttons

![Screenshot 2021-12-14 at 11 19 37](https://user-images.githubusercontent.com/3985124/145997267-325a3ebb-1086-4465-bd58-8ccaabdde887.png)
![Screenshot 2021-12-14 at 11 19 59](https://user-images.githubusercontent.com/3985124/145997272-1f2b38e2-b392-49ab-8edf-8a37c4e8d250.png)
![Screenshot 2021-12-14 at 11 20 31](https://user-images.githubusercontent.com/3985124/145997278-b43aa83a-eac9-4d36-9ce2-49cc211e907e.png)
![Screenshot 2021-12-14 at 11 20 51](https://user-images.githubusercontent.com/3985124/145997279-1384af59-0033-4c9d-a9a1-b4575622fad7.png)
![Screenshot 2021-12-14 at 11 21 36](https://user-images.githubusercontent.com/3985124/145997284-e8d60881-8808-424f-b460-5dc773b81428.png)
![Screenshot 2021-12-14 at 11 22 17](https://user-images.githubusercontent.com/3985124/145997285-0fca3d57-4562-4435-8af3-20e20bee5b58.png)

**Comment by ManuGowda** [comment]
We are re-implementing the new design, so this issue is no longer valid
