### ISSUE TITLE
HW can not create new account because there is always a non-initialised one

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4012]
The current design of the HW login page seems to confuse some users. We should consider improving the user experience and resolve the following issues:

- Users must be able to create only one new account. A new account is not an account with balance = 0LSK, but an account that has no incoming or outgoing transaction.
- Users must notice that they have to take immediate action about their reclaimable balance.
- Users must be able to filter out the accounts with balance = 0LSK. This is not the new account, but the legacy accounts that could have empty balance. With Core v3, this is not possible since an account should have at least 0.5LSK after making a transaction.
- A new account must be easily distinguishable. 
- Users must have only one way to create a new account.

### Which version(s) does this affect? (Environment, OS, etc...)

Mac, 2.2.0-beta.1

**Comment by ManuGowda** [comment]
This is not a bug, it requires UI/UX changes, since we are getting closer to the release we do not intend to fix this now but improve the UI/UX in next release.
