### ISSUE TITLE
Network monitor issues in 2.2.0-beta.1

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4013]
### Which version(s) does this affect? (Environment, OS, etc...)

Mac, 2.2.0-beta.1

1- Number of connected peers in chart and map don't match

![Screenshot 2021-12-14 at 14.06.00.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/c09ba6f3-d481-48d1-ad08-8baa08169096)

2- No margin between end of table and windows

![1.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/3ab0e5dc-56f6-45ca-933e-13529b13f6b8)

3- Information missing in table

![2.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/c8b528b2-799c-40ab-a50a-0131931da73e)

**Comment by ManuGowda** [comment]
We are re-implementing the network page with new design, so this issue should be resolved along with the corresponding task
