### ISSUE TITLE
Design and functionality refinements identified in 2.2.0-beta.1

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4014]
1- With the new account management, the session timeout feature should be removed.

![Sign in with a Passphrase.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/9795d8c7-7b38-4600-b547-ff9c6b281d0e)

2- Pending reclaim accounts are 0 (displaying 'Pending reclaim(0)'). Should we remove that '(0)' or the tab when there are no accounts?

3- Below connected peers map(Network monitor) there is a table with both connected and unconnected peers, which is confusing because one can see much less peers in the map than in the table and makes it seem like information does not match or correlate.

![Screenshot 2021-12-14 at 14.06.56.png](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/a4da3f85-ced5-470b-95c8-9883fab88949)

**Comment by soroushm** [comment]
feature is removed in v3.0.0
