### ISSUE TITLE
Sorting a list by a property it doesn't have

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#4021]
### Expected behavior
When you filter a list and try to sort it by a property it doesn't have, it shouldn't return 404

### Actual behavior
When you sort the filtered list by a property it doesn't have, it returns a 404 (Not found)
![Screenshot 2021-12-14 at 17 15 11](https://user-images.githubusercontent.com/13969732/146182950-5b8943c7-b9e7-4336-81ea-b640a8f4c89a.png)

### Steps to reproduce

- Navigate to transactions
- Filter all transactions by type and select 'Register multisignature group'
- Try to filter the returned list by amount

### Which version(s) does this affect? (Environment, OS, etc...)
2.2.0-Beta.1

**Comment by ManuGowda** [comment]
This issue is no longer reproducible in v3
