### ISSUE TITLE
Adapt hardware wallet integration for Lisk Core v4

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4041]
### Description

Adapt hardware wallet integration for Lisk Core v4

- Enable users to continue using hardware wallets for account sign-in and transaction signing

<img width="1099" alt="Screenshot 2023-02-08 at 17 56 45" src="https://user-images.githubusercontent.com/1031663/217602897-845fa088-6c54-4ba7-9dac-808cbe354667.png">

### Tasks

- [x] #4271
- [x] #4311
- [x] #4766
- [x] #4767
- [x] #4768
- [x] #4769
- [x] #4770
- [x] #4772
- [x] #4773
- [x] #4774
- [x] #4775
- [x] #4776
- [x] #4777
- [x] #4803
- [x] #4797
- [x] #4832
- [x] #4790
- [x] #4791

**Comment by clemente-xyz** [comment]
Hmmm why not to manage the HW state in a React Context instead of Redux?

**Comment by ManuGowda** [comment]
## Architecture overview

![Hardware wallet integration - Architecture overview](https://user-images.githubusercontent.com/6449871/224037643-aa1317a4-fc9a-42f2-a8c7-1531bf73c32d.jpg)

## Hardware wallet devices

![Hardware wallet integration - Hardware wallet devices](https://user-images.githubusercontent.com/6449871/224037633-8ec90cd7-7ef3-4269-8ef5-7567043bb1e1.jpg)

## Hardware wallet accounts

![Hardware wallet integration - Hardware wallet accounts](https://user-images.githubusercontent.com/6449871/224037640-2f8623d0-a2cc-4b85-bd83-d02dcb8a2e53.jpg)
