### ISSUE TITLE
Restart app button doesn't work after an update

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#4062]
### Expected behavior
It should work
### Actual behavior
It doesn't work
### Steps to reproduce
Update the wallet from 2.0.0-beta.0 to 2.0.0-beta.1 click the restart app button
![image](https://user-images.githubusercontent.com/25085095/148930663-eca3f79f-9d42-4507-9359-7d4f161a640d.png)

### Which version(s) does this affect? (Environment, OS, etc...)
Windows 2.0.0-beta.1

**Comment by ManuGowda** [comment]
@przemerr can you please add the environment details? I was able to reproduce this issue on both M1 and Intel

@reyraa Related issue https://github.com/Squirrel/Squirrel.Mac/issues/182

**Comment by przemerr** [comment]
Not sure what you mean by environment details, I'm currently on Windows 10 Home, Compilation 19043.1415

**Comment by ManuGowda** [comment]
<img width="1050" alt="Screenshot 2022-01-11 at 12 06 44 PM" src="https://user-images.githubusercontent.com/6449871/148933874-1698aab1-976b-4da3-9f8a-ae6bb36394e7.png">

**Comment by reyraa** [comment]
@ManuGowda As I said, this READ-ONLY more is a different thing. and it's a valid error that we do not need to resolve. Although we can replace this view with a React toaster, but the behavior remains the same. 
But regarding the restart issue, we should tackle the bug.
