### ISSUE TITLE
Prepare 2.2.0 for production

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4078]
### Description

The purpose of this epic is to prepare version 2.2.0 for production release.

### Sprint 66

- [x] #4077
- [x] #4076
- [x] #4080
- [x] #4084
- [x] #4106 
- [x] #4115 
- [x] #4089
- [x] #4124
- [x] #4127

**Comment by reyraa** [comment]
All the issues are completed.
