### ISSUE TITLE
Filtering and sorting by amount on vote transactions returns  empty results

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4118]
### Expected behavior
- The recipient filter input should be active only for the transfer type.
- The amount from/to range should be active only for the transfer, unlock and reclaim types.
- Once a tx types are selected
   - The recipient and amount rage inputs must be disabled according to the above criteria.
   - The previously selected recipient and amount range filters must be removed if irrelevant.
- You should make the above changes dynamically based on the existing module asset schemas.
- The above criteria should also work for sorting.

### Actual behavior
- Sorting vote transactions by amount doesn't render any vote transactions.
- Filtering vote transactions  by amount doesn't render any vote transactions.

### Steps to reproduce
- Navigate to the transactions page.
- Filter transactions by vote type and by a given minimum and maximum amount (no vote transaction is rendered even for a valid amount range).
- Clear minimum and maximum amount filter values (all list of votes should be rendered)
- Sort the list by amount (no vote transaction is rendered)

### Which version(s) does this affect? (Environment, OS, etc...)
- v2.2.0 
- all OS

**Comment by ManuGowda** [comment]
@eniolam1000752 please comment on why its blocker, so that we can resolve it with context.
