### ISSUE TITLE
Filter voters does not work

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4126]
### Expected behavior

Should filter voters

### Actual behavior

Does not filter properly

### Steps to reproduce

- Go to wallet and open voting tab
- Use voters filter and observe

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.0-linux

![Screenshot from 2022-01-31 13-06-30](https://user-images.githubusercontent.com/3985124/151811481-0d841dbc-6ba0-40c1-9651-ec440887bff0.png)

**Comment by sameersubudhi** [comment]
Steps to reproduce:
1. Open the `Delegate profile` page/view for any delegate account
2. Try searching for a voter in the search bar in the `Voters` subsection next to the title
3. No results are returned, no matter whatever the search term is (valid/invalid)
