### ISSUE TITLE
Signs on transactions page wrong

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#4136]
On transactions page these signs make no sense. It should be `-`. I also suggest to add LSK to make it more clear what those number indicate. Also the formatting looks not good. Should be aligned better in a clear way.

`      0 - 10 LSK`
`    10 - 100 LSK` 
`  100 - 1,000 LSK`
`1,000 - 10,000 LSK`

![image](https://user-images.githubusercontent.com/1260700/151993662-6fc79dd1-ed8f-44c3-ae70-6ea088b04c9c.png)

![image](https://user-images.githubusercontent.com/1260700/151997844-66a14842-54f4-450c-b0ac-e3de18db439b.png)

**Comment by ann-vashchenko** [comment]
Hi, @gadjacobs could you move guides to the top, please?
<img width="1347" alt="Screenshot 2022-02-21 at 11 41 28" src="https://user-images.githubusercontent.com/61688877/154942408-a7d2e397-d449-471d-9290-1277f331c3c5.png">
