### ISSUE TITLE
Unable to send a transaction from a specific multisignature account

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#4141]
### Expected behavior
User should be able to send a transaction from any multisignature account
### Actual behavior
User is unable to send a transfer transaction from a multisingature account that has one required key that doesn't belong to senders account (example of the account https://testnet-service.lisk.io/api/v2/accounts?address=lsko3qy92jx8g9h4zhghdbey6n753k434wmpeoeaw)
### Steps to reproduce
Create a multisignature account with one required key that doesn't belong to senders account (example https://testnet-service.lisk.io/api/v2/accounts?address=lsko3qy92jx8g9h4zhghdbey6n753k434wmpeoeaw). After creating it, try sending a transfer transaction with the account
### Which version(s) does this affect? (Environment, OS, etc...)
Windows Lisk Desktop 2.2.0, doesn't affect 2.1.0.

**Comment by ManuGowda** [comment]
While sign and send, the below screen appears.

<img width="1110" alt="Screenshot 2022-02-03 at 2 04 06 PM" src="https://user-images.githubusercontent.com/6449871/152348285-94d35e78-5d60-4036-b9e0-bcececf7a2c7.png">

**Comment by przemerr** [comment]
There are users that have this type of account (mainly by mistake), and you can register those type of accounts in 2.2.0
![image](https://user-images.githubusercontent.com/25085095/152761548-94cc5644-caa4-43d5-a7c7-77e18b9cb878.png)

**Comment by przemerr** [comment]
they are still somewhat useful if you're a delegate, since you sign blocks with you delegate account, and send tokens with the other signature.

**Comment by reyraa** [comment]
Yes, this is a limited yet valid use case. Thanks.
