### ISSUE TITLE
FIAT balance equivalent does not display for CHF

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#4177]
### Expected behavior

When the CHF currency is selected in settings, every users lisk balance should show the CHF approximate beside it.

### Actual behavior

When CHF is selected, there is no CHF approximate beside it

### Steps to reproduce

- Login to Lisk Desktop
- Go to settings and switch currency to CHF
- Try to view your balance or any other users.

### Which version(s) does this affect? (Environment, OS, etc...)

v2.3.0 beta.0

**Comment by sridharmeganathan** [comment]
This is addressed by the service team as part of [#979](https://github.com/LiskHQ/lisk-service/issues/979)
