### ISSUE TITLE
You should be able to search for blocks by block height

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#4178]
### Description

Currently, you can only find blocks by their block id. It would be nice to find them by their height too.

### Acceptance Criteria

You should be able to search for a block by its height

**Comment by ManuGowda** [comment]
@gadjacobs at the moment global search doesn't provide that feature, we have the ability for searching block by height in blocks page using filter. 

We can close this issue for emerald phase and see how to improve searching in sapphire phase

Here is the screen shoot 
<img width="1382" alt="Screenshot 2022-02-28 at 10 32 31 AM" src="https://user-images.githubusercontent.com/6449871/155926986-5e200fec-d657-485f-b4f1-9119c9173d42.png">
