### ISSUE TITLE
Inconsistency in filtering delegates in delegate profile

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#4180]
### Expected behavior

You should be able to filter delegate votes by either their usernames alone or both username and addresses. It's different in the two pages and should be consistent.

### Actual behavior

Delegate profile -> Voters search box allows you to filter voters by username and address meanwhile you can only filter by username in the accounts -> votes page.

### Steps to reproduce

Attempt to filter delegates in both `delegate profile -> Voters search box` and `accounts -> votes`

### Which version(s) does this affect? (Environment, OS, etc...)
v2.3.0

**Comment by ManuGowda** [comment]
Closing this issue as this feature will be updated in 3.0 release
