### ISSUE TITLE
Minutes passed doesn't match with the total number of blocks

### ISSUE THREAD

**Issue by gadjacobs** [LiskHQ/lisk-desktop#4183]
### Expected behavior

Minutes passed should be equal to `(blocks forged + missed blocks) * 10`

### Actual behavior

Minutes passed is not equal to `(blocks forged + missed blocks) * 10`

### Steps to reproduce

Check the forging details on the delegates page

### Which version(s) does this affect? (Environment, OS, etc...)
v2.3.0 beta.0

**Comment by vibratious** [comment]
I check the `getPassedMinutes` function, I think it's correct because it doesn't need to calculate based on missed and forged blocks. we have the first block forging time and the current time and the function just subtracts the two numbers. It does not seem wrong to me, please provide more info.

**Comment by ManuGowda** [comment]
Closing this issue as we will revisit this in 3.0 release
