### ISSUE TITLE
Refactor the DPoS domain to match the proposed architecture

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4211]
### Description

As a part of the Make Lisk Desktop blockchain agnostic, we should create a domain for user DPoS. We’ll have a dedicated domain for each consensus algorithm that Lisk Desktop is supposed to support, starting with DPoS. 
Said domain is responsible for:
- Implementing consensus specific views.
- Implementing consensus specific configuration that are used by this and other domains.

### Acceptance Criteria

According to the TECH proposal document, this domain should have components to:
- List all in-round delegates.
    - Apply sorting by forging time.
    - Apply filter by username.
- List all outside-round delegates.
    - Apply sorting by status.
    - Apply filter by username.
- List all sanctioned delegates.
    - Apply sorting by status.
    - Apply filter by username.
- List latest votes on the network
- Display delegate profile.
    - Display basic information about a delegate’s activity status on the network.
    - Display list of voters.
        - Apply filter by username and address.
- List account sent votes.
    - Add edit capability.
    - Apply filter by username and address.
- Enable users to edit their vote for a given delegate.
- Support vote transaction creation.
    - Add vote management form.
    - Note: The VoteQueue view from the View domain is responsible for consuming the above form alongside the transaction form composer components to create the complete voting transaction creation experience.
- Display delegate overview.
- Display forging details.

**Comment by sridharmeganathan** [comment]
Sliced into #4250, #4251 and #4252
