### ISSUE TITLE
Account details should be blurred when rendered in discreet mode

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4216]
### Description
On initiating a  global search on my own account, I am navigated to the account page showing my credentials but on toggling discrete mode, my balance and locked tokens aren't blurred out.

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/32064769/158989665-6402d35c-9d58-4c1b-8943-752e8f9aab51.png">

### Motivation

Since on discrete mode, user account details are blurred if accessed via the wallet page, then it would make sense that when in discrete mode, the user's account detail is blurred if accessed by doing a global search of the account's public address.

**Comment by ManuGowda** [comment]
Also, after searching and navigating to your own account the toggling the `discrete mode` doesn't work.

**Comment by ManuGowda** [comment]
Closing this issue as we will revisit the design in 3.0 release
