### ISSUE TITLE
Edit mode warning message does not match design in dark mode

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4220]
### Expected behavior

Warning message should match design

### Actual behavior

Warning message does not match design

### Which version(s) does this affect? (Environment, OS, etc...)

2.3.0 rc dark mode

![2.3.0rc.1-1.PNG](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/eb0d3289-ee6c-4aac-9c92-1db6a13b49c0)

**Comment by ManuGowda** [comment]
@ann-vashchenko closing this issue as we will revisit the voting flow in 3.0 release
