### ISSUE TITLE
Transactions filters form display oddly

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#4221]
### Expected behavior

Should display according to design

### Actual behavior

When transaction type filter name is long the filter is displaced to first column

### Which version(s) does this affect? (Environment, OS, etc...)

2.3.0 rc.1

![2.3.0rc.1-2.PNG](https://images.zenhubusercontent.com/5f2935e8356b6061dae17665/bdb720d7-40d4-4e3d-9fef-24313b1093d8)

**Comment by ManuGowda** [comment]
After updating the design this issue becomes invalid
