### ISSUE TITLE
Voting tab glitches after using it with different addresses 

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#4231]
### Expected behavior
Voting tab should always work and show proper data
### Actual behavior
After browsing couple of accounts the voting tab, shows wrong data
### Steps to reproduce
Open lisk desktop, use mainnet, don't log in, search for delegate `przemer` and open the voting tab (should show proper data), search for delegate `spirita3` and open the voting tab (the data should be wrong). If the votes don't show `0` try browsing few more delegates, eventually it should show incorrect data
![image](https://user-images.githubusercontent.com/25085095/159899627-9422b8e8-8888-46a6-8152-9550115ee4a8.png)

### Which version(s) does this affect? (Environment, OS, etc...)
Windows, Lisk desktop 2.3.0-rc.1

**Comment by ManuGowda** [comment]
@przemerr this is due to failed websocket connection, which should be resolved by service, if you reload the page at times it succeed to connect.

**Comment by ManuGowda** [comment]
Currently this issue no longer exists on Lisk Desktop 3.0.0, hence closing.
