### ISSUE TITLE
Enable/Adapt E2E with MSW

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4236]
### Description
To ensure maximum reliability, we should enable all E2E tests that are commented. If a new test requires changes to adapt to the current implementation, we should apply required changes.  

### Acceptance Criteria

- Enable all commented e2e tests.
- Cover all happy path scenario with e2e test

**Comment by ManuGowda** [comment]
This issue will be addressed by https://github.com/LiskHQ/lisk-desktop/issues/4509
