### ISSUE TITLE
Display the list of remaining reclaimable legacy accounts

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4242]
### Description

In order to prepare Lisk Desktop to work with various blockchain applications, we should make the token domain adapt to

- he remaining reclaimable legacy accounts

### Acceptance Criteria

- Users should be able to see the list of reclaimable legacy accounts
- The owners should be warned that they have to take immediate action
- Add unit test
- Add e2e test

**Comment by sridharmeganathan** [comment]
Team need more details. @ManuGowda will provide more information in the future grooming meeting

**Comment by ManuGowda** [comment]
Maxime clarified that we will only have one account to reclaim at a time, so we do the same approach as 2.x reclaiming one account at a time.

**Comment by soroushm** [comment]
as we discussed with Manu this issues is invalid the legacy domain refactor handled by #4204
