### ISSUE TITLE
Issues discovered after migrating Lisk Desktop to the new scaffolding

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4287]
- Sign in
   - There are two custom node options in the network selector.
- Dashboard
   - App throws `ncaught (in promise) TypeError: token is undefined
    _callee$ middleware.js:46`
- Wallet
   - Doesn't populate the delates of voted delegates (not persistent) .
   - Doesn't open tx details page.
   - The descreet mode causes style issues in the token info card.
   - Duplicate error message when there are no transactions with the selected filters.
   - Error thrown when finalizing delegate profile creation `Uncaught (in promise) TypeError: Cannot destructure property 'eligibleURLPatterns' of 'Jt' as it is null. at companion-bubble.js:1436:11909 at Generator.next (<anonymous>) at tn (companion-bubble.js:1436:11431)`
   - Vote transactions that have more than 1 delegate are visually misaligned.
- Explorer
   - The page crashes if you refresh (network config error).
   - The page crashes if you are not signed in (navigate via links or search).
   - Error thrown when trying to add to votes `Uncaught TypeError: Cannot read properties of undefined (reading 'info') at index.js:65:26`
- Delegates
   - If the page remains open, the forgers sequence goes crazy.
- Transfer
   - The token transfer works but the wallet page crashes under the modal. 
- Edit vote
   - The modal is looking for `account` which renamed to `wallet`, hence crashes.
- Register delegate
   - The modal is looking for `account` which renamed to `wallet`, hence crashes.
- Bookmarks
   - Adding bookmarks fails due to some error in the reducer
- Unlock token
   - Send unlock transaction modal step does not display.
- Generic
   - Page crashes after the auto sign out.
   - Error thrown on click actions `Uncaught (in promise) TypeError: Cannot destructure property 'eligibleURLPatterns' of 'Jt' as it is null. at companion-bubble.js:1436:11909 at Generator.next (<anonymous>) at tn (companion-bubble.js:1436:11431)`

**Comment by ManuGowda** [comment]
@soroushm we need to revisit these issues and split them into smaller issues.

**Comment by ManuGowda** [comment]
None of these issues exists as we fixed several bugs over the period of time.
