### ISSUE TITLE
Update sign transaction flow include password step

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4301]
### Description
Allow user to sign a transaction/messages while they review the transaction to enter the account password to decrypt the recovery phrase and use it to sign transaction

### Acceptance Criteria

- Enable users to enter the password for singing any tx type at the time of creation the transaction.
    - Send
    - Vote
    - Register delegate
    - Reclaim Balance
    - Unlock tokens
    - Register mutlsig.
- Enable users to enter the password to sign a multisig tx that doesn't belong to their account.
- Enable users to enter the password to sign a message
- Adopt unit test and e2e test

### Additional Information
 - Reuse the EnterPasswordForm component.
 - Ensure secret recovery phrase and privateKey are removed (never stored) from the Redux store.
 - Ensure the decryption is done at the time of tx creation / message signature / multisg tx signature.

**Comment by reyraa** [comment]
Existing signature scenarios to handle:

- User logs in using HW: You don't have access to the privateKey. The HW takes care of signing the tx. The process is async. The `sign` function already takes care of this.
- User logs in using secret recovery: You have the private key stored in the Redux store. You don't need to show the password modal.
- User logs in using secret recovery (with 2nd pass): You have the private key stored in the Redux store. You don't need to show the password modal. But we should show the second pass input. Once the first signature is done, we should double sign the tx using second pass.
- User logs in using a stored account: You should show the password input. get the private key from the encrypted file.  Pass it to the `sign` function (through the action). and sign the tx. 
- User logs in using a stored account (with second pass) After doing the above, show the second pass input, and double sign the tx.
- User tries to sign a multisig that doesn't belong to them. There are more scenarios here:
   -  If the user signs in using HW
   - If the user signs in using secret recovery
   - If the user signs in using a stored account
