### ISSUE TITLE
[Ledger Hardware Wallet] Unable to create new accounts

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#4311]
With Lisk Desktop v2.3.0 you can not create a new Lisk account when logged in to the Ledger Hardware Wallet.

**Comment by ManuGowda** [comment]
@punkrock thank you for reporting the issue, are you sure you can not create an account? the UI/UX is changed a bit now, the create account has been removed and if you want to initialise a new account then you can use the very first account shown as "unnamed account", once you use that account a new "unnamed account" will be initialised. 

Please see this image for reference
![Screenshot 2022-05-13 at 12 40 37 PM](https://user-images.githubusercontent.com/6449871/168267633-a9a59a79-6152-40dc-adde-f7ed5a70f754.png)

**Comment by punkrock** [comment]
Ok, you are right. The first account is a new, unused account but I thought it is an old account. This is confusing to me. Creating a new account should be done pro-active by the user and not automatically without any notice, in my opinion.

**Comment by ManuGowda** [comment]
The "unnamed account" can be confusing, currently we do not have any plans for future releases for desktop version as we are focusing on 3.0 release, however we will consider to change the name to "new account" for uninitialised first account.

**Comment by ManuGowda** [comment]
This design flaw has been addressed in the Lisk Desktop 3.0 version, since we are not going to address this for 2.x I am closing this issue for now.
