### ISSUE TITLE
Fetch account data for account management

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4334]
### Description
we introduce login by encryption JSON and remove the recovery phrase from the redux we need to update the redux and API call to match with a new structure

### Acceptance Criteria

- on add /switch account, data should be fetched
  - data from the dashboard should fetch
  - data from the wallet should fetch
  - sign multi-signature/message and votes should be available 
- adopt unit test

**Comment by ManuGowda** [comment]
@soroushm the issue is not upto date, we need to add all the RPC endpoints required for account management

**Comment by soroushm** [comment]
we will integrate the endpoint on #4424, #4429, #4400 tickets
