### ISSUE TITLE
Delegate weights are displayed wrong

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4343]
### Expected behavior
We should display the delegate weight as the minimum of sum of received votes' amount and 10 x self vote amount.

### Actual behavior
It appears that we only take the sum of received votes' amount into account.
For example, if the total votes received to a delegates is 25,000 LSK, and the delegate has voted to themselves in the amount of 1000 LSK, the delegate weight is only 10,000 LSK. But we display 25,000 LSK.

### Steps to reproduce
1. Take a look at the votes in the wallet page. The vote weight is wrong.
2. Take a look at the inside-round delegates tab in the delegates page, the delegates weights are wrong.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3.0

**Comment by ManuGowda** [comment]
This issue will no longer exists in Lisk Desktop 3.0 as the weights are calculated in backend.
