### ISSUE TITLE
Users shouldn't see the edit vote button in the votes of another account

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4344]
### Expected behavior
When I navigate to anther user's account, and active the votes tab. I see the votes of said user. These are not my votes, I'm not able to edit them, therefore I shouldn't see the edit button.

### Actual behavior
I see the edit button, and when I click on it, the `editVote` modal opens, although the values are disaplyed correctly according to my own votes. I think we should simply hide the edit button.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3.0

**Comment by ricott1** [comment]
Just to clarify, I could edit the votes because I was currently voted for that delegate. I do not think this is an issue.

**Comment by ManuGowda** [comment]
Based on comments from Alessandro and new voting queue implantation https://github.com/LiskHQ/lisk-desktop/issues/4466 this issue is now invalid.
