### ISSUE TITLE
Create a component for exploring applications statistics

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4358]
### Description

Create a component to show number of applications by status, Total LSK Supply/Staked

### Acceptance Criteria

- Allow users to see application status by pie chart
- Allow users to see total supply of LSK
- Allow users to see staked LSK
- Ensure [UI/UX design](https://www.figma.com/file/uStjr4eQ37wPm9bDt8JyXP/Applications-management?node-id=2%3A1351) requirements are met
- Add required unit tests
- Add required new e2e tests

	
### Additional Information

- Suggested component name `blockchainApplicationStatistics`, 
- Suggested function name for mapping data `?`,
- Suggested component name for each type and list `?`, 
- Create a function to map data and render the right component by type
- Existing pic chart component can be used (DPoS Delegation status)
- Fetch data from the given [endpoint](https://docs.google.com/document/d/1I8d6nM2wI0pWeuPbTllztpAO63e0A_7eeMjcElv1A8g/edit#heading=h.kxdluqihmxoh)
 
```
const mapApplicationStatistics = (data) => {
 return [
   {
     type: 'pieChart',
     label: null,
     chartData
   },
   {
     type: 'cart',
     label: t('total supply'),
     value: '500,000 LSK',
     icon,
   }
 ]
}

```

**Comment by soroushm** [comment]
@isalga I just add the end point to the ticket, please use it for the manager and mock the response
