### ISSUE TITLE
Create a page for exploring blockchain application

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4359]
### Description
Create a page to explore a list of blockchain applications and statistics details

### Acceptance Criteria

- Enable users to navigate to applications exploring page
- Page should be responsive
- Add banner, application exploring list and application statistics as per [UI/UX design](https://www.figma.com/file/uStjr4eQ37wPm9bDt8JyXP/Applications-management?node-id=2%3A1351)
- Ensure [UI/UX design](https://www.figma.com/file/uStjr4eQ37wPm9bDt8JyXP/Applications-management?node-id=2%3A1351) requirements are met
- Hide banner * 
- Add required unit tests

	
### Additional Information

- Suggested Route: “/applications”
- Suggested component name `BlockchainApplications`
- Sync with UI/UX team for the banner details
- Reuse BlockchainApplicationsList, Blockchain Application Statistics, BannerInfo
- Create a page component and add styles for two columns as suggested below

```
const BlockchainApplications = () => {
 return (
   <div className="wrapper">
     <InfoBanner />
     <div>
       <div className="content" >
         <BlockchainApplicationsList />
       </div>
       <div className="sideBar" >
         <BlockchainApplicationStatistics />
       </div>
     </div>
   </div>
 );
};
```

**Comment by soroushm** [comment]
@isalga and @eniolam1000752  be aware the route name is changed to /applications
