### ISSUE TITLE
Signing a transaction using second passphrase forces the active account change

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4376]
### Expected behavior
I should be able to send transactions using my second passphrase without an issue.

### Actual behavior
When I want to send a transactions, and I use the second passphrase input, when the transaction is confirmed, the active account changes.

### Steps to reproduce
- Sign in using a mutlsignature account with only two mandatory members, no optional.
- Initiate a transaction of any type
- In the summary step, inset the second secret recovery key
- Proceed to broadcast the tx
- Get back to the wallet page
- Wait until the tx is confirmed
- The active account is now changed to the second member

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by ManuGowda** [comment]
Lisk Desktop 3.0 enables users with multi account features, this way users can add all the required account in the wallet and switch between them easily to sign and braodcast the transaction from second passphrase accounts.
