### ISSUE TITLE
Introduce blockchain application exploring and management features using banner

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4390]
### Description

Introduce Blockchain application exploring and management features to end users using banners and its content.

### Acceptance Criteria

- Text content needs to be update
- Banner image needs to be update

### Additional Information
The text and banner image needs to be worked on

**Comment by ManuGowda** [comment]
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5055
