### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4396]
### Description

We should apply the code formatter to maintain the standards

- Add `prettierignore` and `.prettierrc.json`
- Apply the format to codebase
- Configure git hooks to format for all commits

### Motivation

- Maintain standards across projects
- Well formatted codebase

### Additional Information
- https://prettier.io/
- Reference configuration https://github.com/LiskHQ/lisk-core/blob/development/.prettierrc.json
- External reference: https://www.aleksandrhovhannisyan.com/blog/format-code-on-save-vs-code-eslint/

**Comment by soroushm** [comment]
here is my prefrence for the preittier
### .prettierrc.js
```javascript
module.exports = {
  printWidth: 120,
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  bracketSpacing: true,
  arrowParens: 'always',
  trailingComma: 'es5',
}
```
most the difrence is
- [tabWith: 2 - default](https://prettier.io/docs/en/options.html#tab-width) (prefer use space over tab)
- [arrowParens: 'always' - default](https://eslint.org/docs/latest/rules/arrow-parens) ( prefer parantes always for arrow function )
- [bracketSpacing: true - default](https://prettier.io/docs/en/options.html#bracket-spacing)
- [trailing-commas: 'es5' - default](https://prettier.io/docs/en/options.html#trailing-commas)
- [semi: false - custom](https://prettier.io/docs/en/options.html#semicolons) semicolon less - [read this article](https://www.freecodecamp.org/news/lets-talk-about-semicolons-in-javascript-f1fe08ab4e53/) 


### .eslintrc

```javascript
 module.exports = {
 "parser": "babel-eslint",
  env: {
    jest: true,
    browser: true,
    node: true,
    es6: true,
  },
  settings: {
    react: {
      version: 'detect',
    },
    import/resolver : {}
  },
  plugins: [
    'react',  
    'prettier', 
    'jsx-a11y', 
    'react-hooks',
  ],
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:prettier/recommended',
    'prettier',
    'prettier/react',
    'prettier/standard',
  ],
  rules: {
    // overrides rules
    'no-case-declarations': 'off',
    'react/prop-types': 'off',
    'react-hooks/rules-of-hooks': 'warn', //avoid resolve tons of issues
    'react-hooks/exhaustive-deps': 'warn',  //avoid resolve tons of issues
    'prettier/prettier': [
      'error',
      {
        printWidth: 120,
        tabWidth: 2,
        semi: false,
        singleQuote: true,
        bracketSpacing: true,
        arrowParens: 'always',
        trailingComma: 'es5',
      },
    ],
    'no-console': 0,
  },
}

```

[pre commit hooks](https://prettier.io/docs/en/precommit.html) - [documents](https://typicode.github.io/husky/#/?id=articles)
### package.json
```

  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  ```
