### ISSUE TITLE
Adding votes (use maximum amount): Wrong warning text

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#4407]
If you add a vote and click "Use maximum amount", the warning text that pops up says "Caution! You are about to **send** the majority of your balance" which is the text for sending tx. You need to add a new class for voting and change the text to sth. like "Caution! You are about to **lock** the majority of your balance."

![image](https://user-images.githubusercontent.com/1260700/180990192-a9fe31ea-ad32-4954-87fe-60c0b23bef69.png)

**Comment by ManuGowda** [comment]
The design and text has been updated in Lisk Desktop 3.0, hence closing.

![Screenshot 2023-05-02 at 12 30 52 PM](https://user-images.githubusercontent.com/6449871/235643491-de55048b-cf6d-4d5e-999c-87eef00850ca.png)
