### ISSUE TITLE
Incorrect number of blocks on the chart

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-desktop#4445]
### Expected behavior
The number of blocks displayed in the chart should match the number of blocks selected (and stated in the x-axis label).

### Actual behavior
![Screenshot 2022-08-17 at 10 02 40](https://user-images.githubusercontent.com/21265252/185067356-47add26b-9ba4-4332-903e-2fa34681d163.png)

On selecting the `Blocks` screen, the chart initially displays 20 blocks while the label on the X-axis and the count selector (on the top right) show 10 blocks. However, switching back to `Last 10 blocks` after choosing `Last 50/100 blocks` lists the correct number of blocks on the chart.

### Steps to reproduce
- Visit the `Blocks` page on Lisk Desktop Wallet

### Which version(s) does this affect? (Environment, OS, etc...)
`v2.3.0`

**Comment by soroushm** [comment]
it should be resolve by merge #4419  issue, we will check it on beta phase
