### ISSUE TITLE
Rename Total Fee to Network Fee

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-desktop#4446]
### Description

`Total fee` displayed on the block details page seems misleading. Please consider renaming it to `Network fee` or something more meaningful and self-intuitive.

![Screenshot 2022-08-17 at 10 03 08](https://user-images.githubusercontent.com/21265252/185068439-d2e004b1-7714-42ae-8d35-02c086576ef6.png)

### Motivation

The amount displayed against the `Total fee` field seems misleading.
The value presented under `Total fee` is actually the net fees that the forgers (block generators) make (are assigned) after burning the minimum fees from all the transaction fees for the transactions contained within any given block.

**Comment by soroushm** [comment]
@Ade-kola FYI

**Comment by soroushm** [comment]
@ManuGowda this issue is valid? should we change it?

**Comment by sameersubudhi** [comment]
@ManuGowda As per our last discussions, I've updated the issue to reflect the property name to be `Network Fees` instead of `Net Fees`. The corresponding PR in Lisk Service that addresses the change is https://github.com/LiskHQ/lisk-service/pull/1251.
CC: @soroushm
