### ISSUE TITLE
Allow users to enter custom node URL

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-desktop#4503]
### Acceptance criteria

- Enable users to switch between supported networks (e.g Main, Test, Alpha, Beta)
- Enable developers to input custom node URL, so that developers can test during development
   - When users select `Custom Node` from the Network Switcher, an input should appear where users can input a custom node url
   - This input should have validation for valid and invalid urls
   - Show indication of valid and invalid status via icons or other form of indication

**Comment by ManuGowda** [comment]
This feature was implemented already.
