### ISSUE TITLE
Integrate initial fee

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4523]
### Description
First transaction to recipient address for the first time it has additional fee called initial fee, this fee needs to be add on top of the regular fee

### Acceptance Criteria
- Check status of the recipient address by fetching data from services (needs to check nonce === 0) from auth endpoit
- Get the initial fee from service `HTTP GET /api/v3/dpos/constants`
- Update transaction object with Initial fee
- Consider legacy account 

### Additional Information
It's required to get the contract from devices currently, SDK doesn't provide the fee

**Comment by soroushm** [comment]
@sameersubudhi let us know what is the api response while you get the information about it

**Comment by soroushm** [comment]
@ManuGowda how we going to find the recipient is new and  initial fee needs to be charge?
I was thinking about fetching the transaction by recipient address if doesn't have any its count as fresh account, also as in v3 we fetching transaction with the address and legacy account has new address, do we should charge init fee for them as well?

**Comment by ManuGowda** [comment]
> @ManuGowda how we going to find the recipient is new and initial fee needs to be charge? I was thinking about fetching the transaction by recipient address if doesn't have any its count as fresh account, also as in v3 we fetching transaction with the address and legacy account has new address, do we should charge init fee for them as well?

@soroushm yes thats one options to query transactions to know if an account has been initialised.

**Comment by sameersubudhi** [comment]
I'd instead recommend to query the `/tokens` endpoint to determine the same. Any uninitialised address would return empty response (`data: []`).

**Comment by ManuGowda** [comment]
This is an invalid issue, we have implemented the account initialisation and delegate registration fee
