### ISSUE TITLE
Adjust event tab ui

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4536]
### Expected behavior
Table column should have own place by hide data column should stay in own place

### Actual behavior
Adjust condition over length to avoid return zero `!smt.lenght ? null : Component`
while data is unavailable column also remove and cause an ugly ui check the screen shot
<img width="799" alt="Screenshot 2022-10-12 at 16 49 47" src="https://user-images.githubusercontent.com/1031663/196968181-cc4fde6b-f1aa-4ca3-86bf-881ddc6a8c49.png">

### Steps to reproduce
just check the page

### Which version(s) does this affect? (Environment, OS, etc...)
V3.0.0

**Comment by ManuGowda** [comment]
![Screenshot 2023-01-29 at 10 30 51 PM](https://user-images.githubusercontent.com/6449871/215356722-254c3ae9-d4cd-4082-84b8-7a7bc7d8897b.png)

UI is implemented as proposed, hence closing.
