### ISSUE TITLE
Refactor private route rerouting logic

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4537]
### Description

There is a functionality for handling redirect to private routes for unauthenticated accounts as shown below:
```<Redirect to={`${routes.manageAccounts.path}?referrer=${path.replace(
          /\/(send|vote)/,
          ''
        )}&${search.replace(/^\?/, '')}`}
      />```

The current implementation is rigid as it is tied to the send and vote modals but the implementation can be made more flexible for any other private route, based on the Redirect API

**Comment by eniolam1000752** [comment]
We need to also consider redirection of modals that are to be private (i.e only show when an account is selected).
@soroushm
