### ISSUE TITLE
Refactor custom queries for multiple chain IDs support

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4545]
### Description

`useCustomQuery` and `useCustomInfiniteQuery` use the chain ID from the current application as part of their configuration. The configuration needs to be updated to allow for chain IDs from other applications

### Acceptance Criteria

Both custom queries should support the use of multiple chain IDs

**Comment by soroushm** [comment]
api should support multichainId csv or react-queries is the feature
