### ISSUE TITLE
Voting queue icon is displayed in the wrong position in top bar

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4555]
### Expected behavior
Since the UI redesign, the voting queue icon is displayed in between the dark mode and discreet mode icons in the top bar
<img width="366" alt="Screenshot 2022-11-03 at 15 17 56" src="https://user-images.githubusercontent.com/31376203/199745102-ef7a9760-12e3-4008-b102-97e743217418.png">

### Actual behavior
Voting queue icon is displayed in the wrong position in top bar
<img width="617" alt="Screenshot 2022-11-03 at 15 15 41" src="https://user-images.githubusercontent.com/31376203/199744758-a5723246-af34-4efd-89bb-1f1ec994f49c.png">

### Steps to reproduce
- Vote for a delegate to add votes to the voting queue

**Comment by ManuGowda** [comment]
Will be resolved with issue https://github.com/LiskHQ/lisk-desktop/issues/4598
