### ISSUE TITLE
Adopt/Remove block middleware/reducer 

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4558]
### Descriptions
looks like block middleware was responsible to fetch block data and refetch data based on changes on the network, it has several API calls old method http (witch look like its unnecessary as we aren't use it any more, also its has socket connection to receive pushes on the block and this logic should implement or adopt with new structure

### Acceptance Criteria
- Deep understanding on what logic its handled and looking for usage
- Remove unused utiles and api calls
- Adopt/integrate logic to hooks/components
- adopt unit test
- make sure websocket logic working correctly (update blocks)

**Comment by reyraa** [comment]
Said modules are already removed by #4625.
I searched through the app and couldn't find any leftovers from the legacy code. I think we can close this ticket now.

**Comment by ManuGowda** [comment]
Based on above inputs from Ali we are considering this issue as invalid.
