### ISSUE TITLE
Adapt delegateMonitorView with react query

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4559]
### Description
getRegisteredDelegates function are using getDelegates and getTransactions to fetch data with old method, it use on delegateMonitorView its need adopt with react query

### Acceptance Criteria
- Remove withData from delegate page
- Make sure all functionality working
- remove unused tools 
- adopt unit test

### Additional information 

API change https://github.com/LiskHQ/lisk-service/issues/1438

**Comment by oskarleonard** [comment]
This one was solved in https://github.com/LiskHQ/lisk-desktop/pull/4888
