### ISSUE TITLE
Audit vulnerability node-fetch caused by trezor.js

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4577]
### Description
node-fetch  <=2.6.6
Severity: high
The `size` option isn't honored after following a redirect in node-fetch - https://github.com/advisories/GHSA-w7rc-rwvf-8q5r
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g

### Acceptance Criteria
Migrate away from [trezor.js](https://github.com/trezor/trezor.js)

### Additional Information
We are using an archived package trezor.js which is using an old version of node-fetch which has a high severity vulnerability.

Information on migration can be found on [trezor.js](https://github.com/trezor/trezor.js)

**Comment by ManuGowda** [comment]
We no longer support trezor in v3 version, so we have to remove the dependency as part of this issue https://github.com/LiskHQ/lisk-desktop/issues/4233
