### ISSUE TITLE
Audit vulnerability html-parse-stringify2

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4578]
### Description
html-parse-stringify2  *
Severity: moderate
Regular expression denial of service (ReDoS) - https://github.com/advisories/GHSA-545q-3fg6-48m7

### Acceptance Criteria
Upgrade to react-i18next@12.0.0

### Additional Information
N/A

**Comment by ManuGowda** [comment]
#4663
