### ISSUE TITLE
Audit vulnerability ws 

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4579]
### Description
ws  6.0.0 - 6.2.1
Severity: moderate
ReDoS in Sec-Websocket-Protocol header - https://github.com/advisories/GHSA-6fc8-4gx4-v693

### Acceptance Criteria
Upgrade to socket.io-client@2.5.0

### Additional Information
N/A

**Comment by ManuGowda** [comment]
#4663
