### ISSUE TITLE
Audit vulnerability jsdom

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4580]
### Description
jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98

This vulnerability comes from the latest version of jest-enzyme. 
![image](https://user-images.githubusercontent.com/8784876/201142072-8e9ece89-5af4-4e0a-b2a5-ee3f11955b63.png)

### Acceptance Criteria
N/A

### Additional Information
N/A

**Comment by ManuGowda** [comment]
#4663
