### ISSUE TITLE
Failed websocket connection

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4592]
### Expected behavior

websocket connection should be successful and application should be able to listen to events and make RPC calls successfully.

### Actual behavior
<img width="1658" alt="Screenshot 2022-11-23 at 11 59 47 AM" src="https://user-images.githubusercontent.com/6449871/203484772-ef53f81a-49bd-4b82-ba27-137970b6fa97.png">

### Steps to reproduce

- Navigate to console tab in browser

### Which version(s) does this affect? (Environment, OS, etc...)
v3

**Comment by soroushm** [comment]
duplicated #4724
