### ISSUE TITLE
Transactions filters doesn't work as expected

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4594]
### Expected behavior

Users should be able to use the filters and application should render the transactions based on applied filters without errors.

### Actual behavior

<img width="1668" alt="Screenshot 2022-11-23 at 12 07 45 PM" src="https://user-images.githubusercontent.com/6449871/203485677-6d4d7738-371b-4124-8e83-7c648735c5aa.png">

### Steps to reproduce

- Use all the filters supported

### Which version(s) does this affect? (Environment, OS, etc...)
v3

**Comment by oskarleonard** [comment]
This is not an issue anymore. Filters for dates have been updated  to correspond with the new API in this PR. https://github.com/LiskHQ/lisk-desktop/pull/4618
