### ISSUE TITLE
Not making a change to the custom derivation when creating an account give you an error

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4616]
### Expected behavior
When user adds a new account and make no change to the pre filled derivation path the default should be used.

### Actual behavior
Making no change to the pre filled value will try to create the account with an undefined derivation path and lead to error
![image](https://user-images.githubusercontent.com/8784876/204768084-1274051f-f6e6-4fd2-8221-164a4249ba68.png)

### Steps to reproduce
- Enable custom derivation path in settings
- Add an account
- Dont change custom derivation path
- Try do continue adding the account
- After trying to setup a password you will see the toast "Failed to setup password"

### Which version(s) does this affect? (Environment, OS, etc...)
v3

**Comment by soroushm** [comment]
@oskarleonard then why you think its about drivition path? if you turn off the custom drivition path is passing?

**Comment by oskarleonard** [comment]
> @oskarleonard then why you think its about drivition path? if you turn off the custom drivition path is passing?

Yes, works if i turn off derivation path. We are using two sources of truth for this and never initialize redux with the default value when setting it to true. Which means that 
![image](https://user-images.githubusercontent.com/8784876/204770068-b5fcd377-cfa8-4f38-83f6-cc6ba2d78385.png)
`customDerivationPath` will be undefined. And why it works for Manu in [issue](https://github.com/LiskHQ/lisk-desktop/issues/4591) is because he is triggering the onChange here 
![image](https://user-images.githubusercontent.com/8784876/204770391-4bc6002c-e5e4-4ca9-9214-c2be1d63d7e0.png)

So this issue is very related to [this](https://github.com/LiskHQ/lisk-desktop/issues/4591), and both need to be kept in mind when fixing this.

**Comment by soroushm** [comment]
Similar issues #4591
