### ISSUE TITLE
Adapt fee computation for all transactions

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#4632]
### Description

Adapt the Lisk protocol fee calculation.

##### Compute minimum fee 

All transactions in Lisk has minimum fee, calculate the [minFee](https://github.com/LiskHQ/lisk-sdk/blob/f6641aca002a563b8cd8c19729b3f3479a36c0d8/elements/lisk-transactions/src/fee.ts#L28) using following function by passing the valid input parameter based transaction (e.g for multisignature registration/transaction from multsig account requires particular options to be passed to work properly)

##### Token transfer

- call token_getInitializationFees to get the set fees
e.g 
```
/api/v3/invoke

{
 "endpoint": "token_getInitializationFees",
  "params": {}
}
```
- check if recipientAddress exists on the chain by token_userAccountExists
- if recipientAddress does not exist, add userAccount fee to the fee
- Use `Fees` subtitle [`Account initialization`](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=111%3A81733&t=3px49TNHq2uSvQZf-4)
  - Once an account has been initialised do not show Initialisation fee

##### Transfer CrossChain

- call token_getInitializationFees to get the set fees
- check if receivingChainID exists on the chain by token_escrowAccountExists
- if receivingChainID does not exist, add escrowAccount fee to the fee
- Use `Fees` subtitle [`Account initialization`](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=111%3A81733&t=3px49TNHq2uSvQZf-4)
 - Once an account has been initialised do not show Initialisation fee

##### Register Validator

- call pos_getRegistrationFee to get the fee
- when calling registerValidator command, add the fee
- Use `Fees` subtitle `Registration`

### Additional Information

- Use `invoke` endpoint with `endpoint` name and `params` to call below mentioned endpoints
- Show additional fee where required (e.g do not show initialisation fee on register validator flow, rather show registration fee)
  - Use correct title for following transactions:
    -  Token transfer, Transfer CrossChain, Reclaim, Register Multisignature: `Account initialization`
    - Register Validator: `Registration`
    - Transactions that do not have extra command fees: `Stake, Unstake, Unlock`
  - Ensure the UI and logic are updated to handle the above cases
- Consider caching the fee related endpoints as they wont change
  - Clear cache after blockchain switch (this is done already i guess) 
- Update MSW mocks
- Adopt unit test

**Comment by ManuGowda** [comment]
@soroushm I think there was no changes to fees endpoint `api/v3/fees` probably you are referring to this fee changes https://github.com/LiskHQ/discussions/discussions/64?

Please update the issue details to address the same.

CC: @sameersubudhi in case if @soroushm has a different understanding of `api/v3/fees` endpoint changes.

**Comment by ManuGowda** [comment]
This issue needs detailing, @ManuGowda will add more context before being worked.

**Comment by reyraa** [comment]
The current code base requires extensive changes. I'd suggest we break this ticket intro the following:
- Create a hook to calculate the tx fee using given parameters (Account for command fee and tiebreaker)
- Fetch command fee and tiebreaker and incorporate in the above hook
- Use the tx fee hook to calculate min fee, the fee corresponding to max transferrable balance, and the fee corresponding the selected priority.
- Use above fee to display fees in tx forms (Update React components to work with new data schema)
- Use above hook to create txs and broadcast them (Update utilities to work with new data schema)

**Comment by ManuGowda** [comment]
https://github.com/LiskHQ/lisk-desktop/issues/4720
https://github.com/LiskHQ/lisk-desktop/issues/4716
