### ISSUE TITLE
Visual issues detected in transactions list

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4677]
### Expected behavior
1. The date should show "time" only if the transaction was submitted within the past 24 hours. 
2. The horizontal space between the transaction row and the box borders should be only 20px.
3. There shouldn't be any horizontal white spaces when you hover over the transaction row.

### Actual behavior
1. The date shows "time" even for transactions of 2 days ago.
2. Mentioned horizontal space is 20px + 15px.
3. There is a 20px white space between the grey background of the transaction row and the box edges.

<img width="898" alt="Screenshot 2022-12-20 at 10 55 13" src="https://user-images.githubusercontent.com/666685/208638656-329fb017-d009-4fe5-a19d-85d33edccc45.png">

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0 (development)

**Comment by ikem-legend** [comment]
Fixed in https://github.com/LiskHQ/lisk-desktop/issues/4593
