### ISSUE TITLE
Implement network selection and remove hardcoded IPs

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4682]
### Description

We have hard coded Lisk Service IP in 10 different places, yet most hooks dynamically retrieve and use it. We should drop the hardcoded ones in favour of the dynamically retrieved and stored value. 
Additionally, said process is quite hard to follow. It appears that we have technical debt to pay.

### Acceptance criteria

- Should able to select supported networks
- Should handle multiple service URLs supported for same application
- Should handle the application and network error gracefully
- Implement the proposed UI, [Light mode](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=3643%3A249687&t=tr6ynawLvEWJNpga-4) and Dark mode

- The application should bootstrap from the selected network (default network is mainnet)
  - Use `settings` and add field `mainchainNetwork`, default it will be `undefined` once the user selects a network update the settings `mainchainNetwork` to selected value.

- Hardcode the list of known networks and its ips
  - On bootstrapping and network selection, filter the networks that are unavailable i.e not 200

- Implement the [UI changes](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=3643%3A253175&t=tr6ynawLvEWJNpga-4) to network selection
- The bootstrap flow:
    - Initially the application will fetch the settings value `mainchainNetwork`, the default mainchain name is `Lisk` and hardcode the `Lisk` logo.
    - Probe the mainchain status URL, `baseURL/network/status` and continue user to `dashboard` based on success. i.e `http://devnet-service.liskdev.net:9901/api/v3/network/status`
    - Once user lands on dashboard, fetch the selected mainchain onchain data i.e `https://alphanet-service.liskdev.net/api/v3/blockchain/apps` and also fetch metadata for all the onchain apps by passing chainID `https://alphanet-service.liskdev.net/api/v3/blockchain/apps/meta?chainID`
    - Update the redux by merging both onchain and offchain information

#### Switching network when on sidechain/lisk app
- When switching the network when on sidechain, the user should be redirected to the select network flow.
- When switching the network when on mainchain, i.e Application is `Lisk` and network is `Mainnet` and switching to `Testnet` doesn't require to redirect

### Additional information

With regards to environment configurations, we should consider the following:

Lisk supports following networks, devnet, alphanet, betanet, testnet and mainnet. For all of these Lisk Service provides following URLs:

https://devnet-service.liskdev.net:9901
https://alphanet-service.liskdev.net
https://betanet-service.lisk.com
https://testnet-service.lisk.com
https://mainnet-service.lisk.com

Based on the above base URL, we can fetch application metadata and corresponding application specific service URLs.

So in env config file, we should use appropriate network name e.g `devnet` during development, `alphanet` once we tag alpha and release it for testing, `betanet` once we tag beta and release it for testing, etc.

**Comment by ManuGowda** [comment]
### Acceptance criteria

- Implement the proposed UI, [Light mode](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=3643%3A249687&t=tr6ynawLvEWJNpga-4) and Dark mode

- The application should bootstrap from the selected network (default network is mainnet)
  - Use `settings` and add field `mainchainNetwork`, default it will be `undefined` once the user selects a network update the settings `mainchainNetwork` to selected value.

- Hardcode the list of known networks and its ips
  - On bootstrapping and network selection, filter the networks that are unavailable i.e not 200

- Implement the [UI changes](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=3643%3A253175&t=tr6ynawLvEWJNpga-4) to network selection
- The bootstrap flow:
    - Initially the application will fetch the settings value `mainchainNetwork`, the default mainchain name is `Lisk` and hardcode the `Lisk` logo.
    - Probe the mainchain status URL, `baseURL/network/status` and continue user to `dashboard` based on success. i.e `http://devnet-service.liskdev.net:9901/api/v3/network/status`
    - Once user lands on dashboard, fetch the selected mainchain onchain data i.e `https://alphanet-service.liskdev.net/api/v3/blockchain/apps` and also fetch metadata for all the onchain apps by passing chainID `https://alphanet-service.liskdev.net/api/v3/blockchain/apps/meta?chainID`
    - Update the redux by merging both onchain and offchain information

#### Switching network when on sidechain/lisk app
-
