### ISSUE TITLE
Lisk Desktop 2.3 fails due to libfuse.so.2 dependency on Ubuntu 22.04

### ISSUE THREAD

**Issue by janhack** [LiskHQ/lisk-desktop#4704]
### Description

I noticed that running Lisk Desktop 2.3 failed for me after upgrading to Ubuntu 22.04:
```
./lisk-linux-x86_64-2.3.0.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
```

This can be easily fixed by installing libfuse2. Note that Ubuntu 22.04 has libfuse3 installed by default that could be possibly used. Here is a related GitHub issue that could be helpful https://github.com/AppImageCommunity/libappimage/issues/168.

### Motivation

It would be nice if the Lisk Desktop AppImage would run out of the box in the most common Linux distribution.

**Comment by reyraa** [comment]
I built the app on Linux and did not encounter this issue. It appears that the issue was resolved by updating the dependencies to the latest versions.
I'm closing this issue as outdated.
