### ISSUE TITLE
Adapt is default application with metadata service

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4708]
### Description
Since the service behaviour is changed and isDefault argument is now part of the application meta data, this change needs to update

### Acceptance Criteria
- BaseUrl of meta service should be configured in the env
- Split MetaData Client from application Client in order to always call meta data from the ENV BaseURL
- First call `/api/v3/blockchain/apps` with query string of isDefault: true and network Mainnet 
- Fetch the rest of information from `api/v3/blockchain` and merge it by using `transformResult` from Client
- Select first index default application(LISK) check for application status  and  set the current application with Lisk
- These logic should be part of custom hooks and used in [bootstrap](https://github.com/LiskHQ/lisk-desktop/issues/4707) component 

### Additional Information
#4707

**Comment by ManuGowda** [comment]
With regards to environment configurations, we should consider the following:

Lisk supports following networks, devnet, alphanet, betanet, testnet and mainnet. for all of these Lisk Service provides following URLs:

https://devnet-service.lisk.com
https://alphanet-service.lisk.com
https://betanet-service.lisk.com
https://testnet-service.lisk.com
https://mainnet-service.lisk.com

Based on the above base URL we can fetch application metadata and corresponding application specific service URLs.

So in env config file, we should use appropriate network name e.g `devnet` during development, `alphanet` once we tag alpha and release it for testing, `betanet` once we tag beta and release it for testing, etc..
