### ISSUE TITLE
Calculate minFee, currentFee, and max amount fee

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4718]
### Description
Following our efforts in #4717, we should use the hook to calculate the fee in for different situations:

- The minimum fee a user may pay for broadcasting a given transaction.
- The fee based on currently selected priority option.
- The fee corresponding the maximum amount the user can transfer from their account. Needless to say, this fee is only required for the token transfer command.

There are two options
- Either the hook calculates and returns these values by default
- Or the component should demand on in the command form component. 

Either way, the result is 3 arrays of fee as explained in #4717.

### Acceptance criteria
- The fee calculation should take selected priority into account 
- Each fee array should be calculated individually
- Reasonably sufficient unit tests are desired.
- Add unit tests for verifying the fee array

**Comment by eniolam1000752** [comment]
##### Each transactions on Lisk Mainchain or other blockchain applications (sidechains) have the following fees:

- Byte Based Fee [GENERIC]: Computed based on transaction bytes length (refer token transfer example) 

- Extra command Fee [SPECIFIC TO COMMAND]: Each command can have extra fee that will be burned and assigned to block generator, this fee can be fixed or conditional, e.g 
   - `validator registration` has `10LSK` as fixed on mainchain, it can be same on other sidechains and can be different, we should call `invoke` command to get these fees
   - `token transfer` to an uninitialized account can have `account initialization fee` i.e `0.005 LSK`

- Minimum Fee [COMPUTED] = `Byte Based Fee` + `Extra command Fee`

- Priority Fee [GENERIC]: = fee based on the selected network priority, i.e `transaction fee - minimum fee`

- Transaction fee[COMPUTED] = `Minimum fee ` + `Priority Fee` 

- Message Fee [SPECIFIC TO COMMAND] = Cross chain messages are the objects containing the cross-chain commands, in the same way in which transactions contain commands. They have a [fee property](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0049.md#cross-chain-message-schema) also called message fee to distinguish from transaction fees.


### Sample Data
#### Token transfer(Without command fee)
```
{
  "module": "token",
  "command": "transfer",
  "nonce": "2",
  "fee": "12345678910", ==>> `Transaction fee = Minimum fee  + Priority Fee` 
  "senderPublicKey": "bfbef2a36e17ca75b66fd56adea8dd04ed234cd4188aca42fc8a7299d8eaadd8",
  "params": {
	  "tokenID": "0000000200000001",
	  "amount": "18446744073709551615",
	  "recipientAddress": "lskzv2yu6ay86x7477pkqzyttertjos4mef7zvoao",
	  "data": "we have some information is here"
 }
}
```

#### Token cross chain transfer(with command fee)
```
{
  "module": "token",
  "command": "crossChainTransfer",
  "nonce": "99",
  "fee": "1234567891077",
  "senderPublicKey": "bfbef2a36e17ca75b66fd56adea8dd04ed234cd4188aca42fc8a7299d8eaadd8",
  "params": {
	  "tokenID": "0000000200000001",
	  "amount": "18446744073709551615",
	  "receivingChainID": "00000002",
	  "recipientAddress": "lskzv2yu6ay86x7477pkqzyttertjos4mef7zvoao",
	  "messageFee": "50000000",
	  "data": "we have some information is here"
   }
}
```

**Comment by eniolam1000752** [comment]
`<FeeViewer />` would render the following updated fee values

Transactions fee: `byte fee + priority fee + extra command fee`
Message fee: `message fee`
