### ISSUE TITLE
Use transaction hook to create and broadcast transaction to network

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4720]
### Description

Following #4718, we should use the updated fee value in composition, signature and broadcasting the transaction. This means we should update all utility functions involved in said actions to adapt to the new fee data.

### Acceptance criteria
Users should be able to
- Sign transactions of any module-commands
- Dry run said transactions successfully 
- Broadcast said transactions successfully (Changes should be applied)
- Add relevant unit tests should be updated.

**Comment by ManuGowda** [comment]
This issue was working as intended with the completion of https://github.com/LiskHQ/lisk-desktop/issues/4719
