### ISSUE TITLE
Remove account modal does not match designs

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4726]
### Expected behavior
- Remove account modal should match the designs from [figma](https://www.figma.com/file/ihhPUgR0OpZqQjj0zT7VSY/Account-management-improvements?node-id=1%3A3462&t=qcBrQbF7GsFpMpX1-4) 

### Actual behavior
- Modal does not match the designs from figma.
<img width="1139" alt="Remove Account" src="https://user-images.githubusercontent.com/32064769/213216338-cf676013-da4b-46f9-a2f0-0b184a2025f2.png">

### Steps to reproduce
- Switch to an account
- initiate the remove account flow
- click on the delete button on any of the account
- A remove step modal is shown which does not match designs.

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by ManuGowda** [comment]
This is duplicate issue, resolved as part of https://github.com/LiskHQ/lisk-desktop/pull/4855
