### ISSUE TITLE
  Enter Password modal on add account by file flow does not match designs

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4727]
### Expected behavior
Enter Password modal step on the `add account by file` flow should match [designs](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=111%3A80135&t=Clb18r6uQ4m3SzAt-4)

### Actual behavior
- On the add `account by file` flow, the enter password modal does not match [designs](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=111%3A80135&t=Clb18r6uQ4m3SzAt-4)
<img width="701" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/32064769/213220068-d8a06c38-f63b-4b0f-a3b4-e72e967292fa.png">

### Steps to reproduce
- initiate the process of adding account by file
- on the second step of the flow the enter password modal is rendered which does not match designs.

### Which version(s) does this affect? (Environment, OS, etc...)
all

**Comment by soroushm** [comment]
only the width is lower than should be

**Comment by ManuGowda** [comment]
Duplicate, resolved in https://github.com/LiskHQ/lisk-desktop/pull/4855
