### ISSUE TITLE
A group account should indicate its a multi sig account in its popover menu list

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4729]
### Expected behavior
A multi signature account should not display `Register Multisignature` in its popover list if it has already been registered as a group account.

### Actual behavior
A multi signature account still displays `Register Multisignature` in its popover list if it has already been registered as a group account.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/32064769/213226406-41a064f8-5360-4681-b5c8-14284fc4cfc6.png">

### Steps to reproduce
- switch to a multi sig account
- click on the account menu at the top left conner of the application
- would would still see that popover has the menu item called `Register Multisignature`

### Which version(s) does this affect? (Environment, OS, etc...)
all

**Comment by soroushm** [comment]
if Auth endpont return number of account more than 0 is a multisign account

**Comment by ManuGowda** [comment]
![Screenshot 2023-01-26 at 7 38 05 PM](https://user-images.githubusercontent.com/6449871/214921370-f62cdc83-e3ad-4483-89da-6b481659f3d5.png)
Fixed
