### ISSUE TITLE
Switching between network crashes the application

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4730]
### Expected behavior

Switching network to mainnet or testnet should work properly or display an error message if there are errors

### Actual behavior

Switching network to mainnet or testnet fails due to the empty response from `/blockchain/apps/meta?limit=20&network=mainnet`. The response looks like `{"data":[],"meta":{"count":0,"offset":0,"total":3}}`. The page still crashes on reload because the network config has been updated in the local storage

### Steps to reproduce
- Select network switcher from top bar
- Select Mainnet or Testnet or any other network from the list
- Observe the application is crashing/not loading properly

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by ManuGowda** [comment]
This issue will be addressed as part of https://github.com/LiskHQ/lisk-desktop/issues/4682
