### ISSUE TITLE
Events list has some styling issues

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4732]
### Expected behavior
Events list should match [design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=209%3A95478&t=XppbGl1Q2sx3fvGS-0)

### Actual behavior
There are some styling issues in the event table display
<img width="1020" alt="Screenshot 2023-01-18 at 02 55 31" src="https://user-images.githubusercontent.com/31376203/213240888-2112a1c8-5206-4b86-a55e-a1ad173bbfa6.png">

### Steps to reproduce
- Select the Wallets page
- Click on the Events tab

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by soroushm** [comment]
duplicated #4735
