### ISSUE TITLE
Accounts page displays 404 error on load

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4733]
### Expected behavior
Accounts page should load properly

### Actual behavior
Accounts page displays 404 error on load because the endpoint `/tokens/lsk/top` has been removed

<img width="1378" alt="Screenshot 2023-01-18 at 17 57 20" src="https://user-images.githubusercontent.com/31376203/213245705-9d70650c-e912-4bc8-af57-587d2bc62340.png">

### Steps to reproduce
- Select Accounts from the side menu

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by ManuGowda** [comment]
This requirement will be fulfilled with issue https://github.com/LiskHQ/lisk-desktop/issues/4674
