### ISSUE TITLE
The direction of a transition is wrongly rendered

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4734]
### Expected behavior
Direction of transaction should be properly rendered based on the direction of a given transaction.

### Actual behavior
The direction of a transition is wrongly rendered (I think we planned on removing it). When an account sends a token, to another address. The arrow's direction signifies it as an inflow.
<img width="1029" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/32064769/213246029-3305af22-2067-408a-ac41-433adc26f758.png">

### Steps to reproduce
- Complete a send transaction
- navigate to the transaction table in the wallets page
- You would see the transaction but the direction of flow is wrong

### Which version(s) does this affect? (Environment, OS, etc...)
all

**Comment by soroushm** [comment]
@ManuGowda we remove this direction arrow right? should we remove it from here?

**Comment by ManuGowda** [comment]
> @ManuGowda we remove this direction arrow right? should we remove it from here?

Yes we should, please remove it from everywhere, its not possible to know incoming or outgoing in straight forward manner
