### ISSUE TITLE
Issues with table filter popover 

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4736]
### Expected behavior
- Popover filter button should have the right `Apply filter` button
- Filter popover should be layered properly on the blocks monitor page.
- Filter popover for the `Events` table  on the `wallet page` should contain the right filter parameters
-  Transactions filter popover should contain the correct filter paramters

### Actual behavior

- Transactions filter popover in the `wallets page` has incomplete filter parameters implemented
<img width="362" alt="Date range" src="https://user-images.githubusercontent.com/32064769/213303515-c4e0be8d-ff7d-4b93-bd0b-ce03294f1b8b.png">

- The filter popover for the `Events` table within the `wallet page` doesn't contain the right filter parameters as described on [figma](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=209%3A95478&t=tKiTcNzqzAmJ5qNH-4)
<img width="613" alt="image" src="https://user-images.githubusercontent.com/32064769/213302683-8c456c66-5013-4ca9-a42a-e79c37a078ef.png">

- Filter popover isn’t layered properly on the blocks monitor page.
<img width="496" alt="Transactions Status" src="https://user-images.githubusercontent.com/32064769/213301789-c027eb80-9ef0-45f3-bef8-ae91d40ef3ed.png">

### Steps to reproduce
- Visit the blocks monitor, wallet page and transaction monitor
- You would observe the above reported issues on the filter pop over 

### Which version(s) does this affect? (Environment, OS, etc...)
all

**Comment by soroushm** [comment]
filter by modules is look like is missing
