### ISSUE TITLE
Blocks table header has visual issues when the new blocks button appears

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4739]
### Expected behavior
Blocks table header should display properly when the new blocks button appears

### Actual behavior
The **Status** header of the Blocks table moves to the left when the new blocks button appears

<img width="1344" alt="Screenshot 2023-01-18 at 03 16 04" src="https://user-images.githubusercontent.com/31376203/213340939-68934e0d-a609-41a2-a224-768bfafa20f9.png">

### Steps to reproduce
- Select the Blocks page from the side bar
- Wait a few seconds for the new blocks button to appear

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by soroushm** [comment]
@ikem-legend could you please prove more information

**Comment by ManuGowda** [comment]
![Screenshot 2023-04-04 at 10 22 08 AM](https://user-images.githubusercontent.com/6449871/229732383-94ecf733-8cab-4539-8ec3-3a8888d11110.png)

This issue is no longer valid.
