### ISSUE TITLE
Block details overview has some visual issues

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4741]
### Expected behavior
Block details overview should display properly according to the [design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=38%3A36160&t=LTGW3x3Km2Rc6iFQ-0)

### Actual behavior
The **Reward** and **Net fee** headers are not properly aligned
<img width="1014" alt="Screenshot 2023-01-18 at 03 22 59" src="https://user-images.githubusercontent.com/31376203/213342568-4771ac0d-3fc1-444d-9930-48d742f4c1cf.png">

### Steps to reproduce
- Select Blocks from the side menu
- Select a row to display the block details page

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by ManuGowda** [comment]
![Screenshot 2023-04-04 at 10 18 14 AM](https://user-images.githubusercontent.com/6449871/229731477-33ba77b1-e2b5-4da9-b7e6-2d4998cb6885.png)
Issues is resolved
