### ISSUE TITLE
Validators watched list fails to load and returns a 400 error

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4742]
### Expected behavior
Validators watched list should display a list of watched validators

### Actual behavior
Validators watched list fails to load, makes an API call and returns a 400 error

### Steps to reproduce
- Select Validators from the side menu
- Click the watch button on a few validators
- Click on the **Watched** tab

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by soroushm** [comment]
so api behaviour gonna be change by this issue from service
https://github.com/LiskHQ/lisk-service/issues/1438

**Comment by ManuGowda** [comment]
This issue will be resolved with https://github.com/LiskHQ/lisk-desktop/issues/4559
