### ISSUE TITLE
Loading more of a validator's stakes leads to a HTTP 400 error

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4744]
### Expected behavior
Loading more of a validator's stakes should display more stakes

### Actual behavior
Loading more of a validator's stakes leads to a HTTP 400 error due to the fact that `offset` is an unknown parameter for the `/pos/stakes` endpoint

### Steps to reproduce
- Select Validators from side menu
- Click the Stakes button
- Click **Load More**

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by soroushm** [comment]
we have only 10 stakes so the api dosn't have pagination
