### ISSUE TITLE
Update HW Manager

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4766]
### Description
The HW Manager is a singleton class responsible for communicating with a hardware wallet (HW) and providing functionality that the application needs. All communication is event based and working with `window.ipc`.

Users may connect more than one HW on their PC, Lisk Desktop should provide an ability to select/switch between connected hardware wallet devices .

### Acceptance Criteria

- [ ] Add required methods to detect, updated, and return the list of connected devices
- [ ] Once the HW is selected/connected, we should start reading addresses from HW, make API calls to determine if the account is used, and store used accounts in an array on the HWManager class. Stored account include `publicKey`, `address`, `deviceID`, `accountIndex`. Store the accounts in the format similar to locally resisted accounts (this part is done in #4767).
- [ ] Create `getAccounts` method to return the list of accounts as generated by the above criteria.
- [ ] Selecting/switching between multiple HWs by device ID
- [ ] Create `GetDeviceList` method to return the list of connected devices. 
- [ ] Retrieve, store and update the list of connected devices on a member in the HWManager class. We should subscribe to `HW_CONNECTED` and `HW_DISCONNECTED` events and update the list of connected devices.
- [ ] Create a method to sign transactions. Collect all normalizations, and crypto calculation into a utility function. Then use in HWManager.
- [ ] Create `GetCurrentDeviceInfo` which returns HW informations such as `brand`, `model`, `ID`, `status` (`connected`, `standBy`, 'isLoading'). The `isLoading` state is used to determine if the HWManager is pending a response from the HWManager right after connecting to it.
- [ ] Add unit tests

### Additional info
The HWManager class should expose the following methods:
- CreateAccount
- GetAccounts
- GetDeviceList
- SelectDevice
- GetDeviceByID
- SignTransaction
- SignMessage
- PresistConnection
- GetCurrentDeviceInfo

**Comment by reyraa** [comment]
Breaking the ticket into three sections: 

Create HWClient class
-   Detecting and connecting to the HW
-   Reading the status and accounts of the HW
 -  Creating new accounts on the HW
 -   Returning list of Devices
-   Signing transactions
-   Updating the device status
-   Add unit tests


Create HWServer class
-  Opening and managing communication channels with the HW
-  Detecting and connecting to the HW
-   Selecting/switching between multiple HWs by device ID
-   Returning list of Devices
-   Displaying toast messages when the HW is connected or disconnected
-   Add unit tests

Third ticket
 -  Mapping the transaction signing process based on the module and command
-   If more than one HW is detected, navigating the user to a switch HW dialog
-   Returning the loading state during the connection process and confirming the firmware
-   application should check if the HW is compatible before opening a connection.
-   Update unit tests
