### ISSUE TITLE
Add HW Status to top bar

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4769]
### Description
HW Status is a feature that displays the status of a connected hardware wallet (HW) on the top bar of the application. It allows users to see the device ID, model, brand, and status of the HW by clicking on an icon on the top bar.

### Acceptance Criteria

Displaying an HW icon on the top bar of the application
Allowing users to view the device ID, model, brand, and status of the HW by clicking on the icon [design](https://www.figma.com/file/b1cfkpheF65f4aYjX2wl7u/Adapt-Hardware-Wallet-Integration-for-Lisk-Core-v4?node-id=79%3A16963&t=wzqebLW0FD9UwjPn-4)
Removing the HW Icon in top bar when HW is disconnected [design](https://www.figma.com/file/b1cfkpheF65f4aYjX2wl7u/Adapt-Hardware-Wallet-Integration-for-Lisk-Core-v4?node-id=79%3A16520&t=wzqebLW0FD9UwjPn-4)
Adding a badge to the icon to indicate the status of the HW
green for connected, 
red for standby, 
no badge for disconnected
Allowing users to switch between connected HWs if multiple are detected
Make sure the status is updated
Add unit test

### Additional information
The status information displayed by HW Status should match the structure of the object returned by the UseHWStatus hook:

```
{
  deviceId: "",
  model: "",
  brand: "",
  status: "", // connected, disconnected, standby
}
```
It's important to keep in mind that when the status is standby, the framework channel is closed and needs to be reconfirmed by the user. HW Status should be used in conjunction with the UseHWStatus hook to ensure accurate and up-to-date information about the status of the HW is displayed on the top bar of the application

**Comment by eniolam1000752** [comment]
This issue was closed by https://github.com/LiskHQ/lisk-desktop/pull/4793
