### ISSUE TITLE
Enable users to create multiple new accounts on HW 

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4771]
### Description
Creating an account on HW is a feature that allows users to create a new account on a connected hardware wallet (HW).
The drop-down menu should have two options: "Create account on Lisk Wallet" and "Create account on Hardware Wallet". If the user selects "Create account on Hardware Wallet", the application should check the status of the connected HW. If the HW is disconnected, the option to create an account on the HW should be disabled and a message should be displayed to the user to connect the HW. If the HW is in standby mode, a tooltip should be displayed to the user to reconnect the HW.

### Acceptance Criteria

- Adding a drop-down menu to the "Create new account" feature in the application, allowing the user to select between creating an account on the Lisk Wallet or on the connected HW [design](https://www.figma.com/file/b1cfkpheF65f4aYjX2wl7u/Adapt-Hardware-Wallet-Integration-for-Lisk-Core-v4?node-id=286%3A46679&t=wzqebLW0FD9UwjPn-4)
- Adding a drop-down menu to the "Getting started" feature in the application, allowing the user to select between creating an account on the Lisk Wallet or on the connected HW
- Disabling the option to create an account on the HW if the HW is disconnected
- In case the HW is in standby mode, showing a tooltip to the user to reconnect the HW
- After create an needs to be set as current account and move to dashboard
- Add unit test

### Additional information
Once the user selects "Create account on Hardware Wallet" the application should connect to the HW and create the account on it.

**Comment by soroushm** [comment]
[discussion](https://github.com/LiskHQ/discussions/discussions/99) going on  here for now we will follow the prevouse implementation witch always showing new account in the list

**Comment by ManuGowda** [comment]
We do not plan to enhance the hardware wallet feature until we have roadmap objective prioritised, hence closing.
