### ISSUE TITLE
Remove auto sign out feature and codebase

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4778]
### Description

With the introduction of new account management, we no longer require the auto sign out feature

### Acceptance criteria

- Remove unwanted feature https://github.com/LiskHQ/lisk-desktop/tree/development/src/modules/common/components/bars/sideBar/autoSignOut
- Remove tests, and other unwanted code

**Comment by soroushm** [comment]
the feature is already removed but still we have unused component about it in the source code
https://github.com/LiskHQ/lisk-desktop/commit/17a79522f5ef0e20fc44d9cbbd12f65f8d4e6914
