### ISSUE TITLE
Integrate Blog/Twiter post

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4794]
### Description
since service will intgrate new blog api with current [api/v3/newsfeed?source=drupal_lisk_general](http://165.227.246.146:9901/api/v3/newsfeed?source=drupal_lisk_general) in rc phase on the [Update newsfeed microservice](https://github.com/LiskHQ/lisk-service/issues/1444) we expect no breaking changes in the response expect the removal of image_url property from the response, and renaming imageUrl to imageURL and sourceId to sourceID. by the way we need to wait till that moment

### Acceptance Criteria
- [ ] make sure blog and twiter posts shows currectly in dashboard
- [ ] fix unit test

**Comment by ManuGowda** [comment]
This issue is no longer valid as we are removing dashboard.
