### ISSUE TITLE
Use BigInt for handling large numbers

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4812]
### Expected behavior

We must use `BigInt` for handling large numbers i.e unit32 and unit64 values

### Actual behavior

We use `Number` and other non `BigInt` methods to handle unit32 and unit64 values

Large numbers in JavaScript are automatically rounded. To be precise, the Number type in JavaScript can only safely represent integers between -9007199254740991 (-(253-1)) and 9007199254740991 (253-1). Any integer value that falls out of this range may lose precision.

### Steps to reproduce

- All transactions (e.g token transfer to pos transactions) should have BigInt for any calculations
  - For conversion we can codec to encode and decode or toJSON and fromJSON as well
  - For string representation we can convert from `BigInt` to `toStriing`
- Some references
  - https://github.com/LiskHQ/lisk-desktop/blob/001019a2f5f6bae12c24887f575dba841c677702/src/modules/legacy/components/AccountsComparison/index.js
  - https://github.com/LiskHQ/lisk-desktop/blob/001019a2f5f6bae12c24887f575dba841c677702/src/modules/legacy/components/MigrationDetails/index.js 
### Which version(s) does this affect? (Environment, OS, etc...)
3.0

**Comment by reyraa** [comment]
- We are using uint32 for the amount value in the send form which should be converted to bigInt. This means the max amount calculation, and therefore the fee calculations should be all converted to BigInt. arithmetic calculations should follow the BigInt syntax.
- The are using number for the stake amount. Similar to above the max stake calculations should be handled using BigInt. The validateStakes is a function that uses some uint32 comparisons.
- Same goes for the total unlockable calculations. This is limited in the useUnlockableCalculator hook.
- We do not define the legacy balance, we simply consume it. but the value is taken as a number not a BigInt. For example in account comparison we compare the value as a uint32 number.
- We also have converter which displays the fiat equivalent, and it performs calculations as uint32 numbers.
- There's the AmountFieldGroup component in filters which has a fair bit of arithmetic calculations based on uint32.
- We're also using numeral  (in useAmountField and validateAmountFormat) which is another library for handling numbers. We might as well get ride of it.
- I think this is almost all of it. Updating unit tests as always is a considerable work. Overall I think it's a day or two's job.
