### ISSUE TITLE
Remove account crashes the application

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4860]
### Expected behavior
When i delete my current account it should be deleted and not crash the application

### Actual behavior
Application crashes. 
![image](https://user-images.githubusercontent.com/8784876/226292544-c522115a-4c43-45ee-b28b-bbfc18504d62.png)

### Steps to reproduce
1. Add an account
2. Remove that account

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

**Comment by ManuGowda** [comment]
Fixed as part of PR https://github.com/LiskHQ/lisk-desktop/pull/4855
