### ISSUE TITLE
Recent transactions doesn't display transaction amount properly

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4862]
### Expected behavior
In the list of recent transactions, each transaction should properly display the sender details and amount

### Actual behavior
In the list of recent transactions, each transaction displays the sender details improperly sometimes and 0 or -0 as amount
<img width="1728" alt="Screenshot 2023-03-20 at 17 29 04" src="https://user-images.githubusercontent.com/31376203/226417346-76cd289d-8913-4efa-bb58-a4d802549d98.png">
<img width="446" alt="Screenshot 2023-03-20 at 18 10 53" src="https://user-images.githubusercontent.com/31376203/226417453-45a6c264-7b23-4ca2-8ef5-a88d61511ba7.png">

### Steps to reproduce
- Make a transaction (for example, send tokens) to an account
- Login to the account and view the Recent Transactions widget of the Dashboard

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by ManuGowda** [comment]
We are removing dashboard functionality with 3.0, so this issue becomes invalid.
