### ISSUE TITLE
Resolve pending TODOs

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4865]
### Description

Currently we have 91 TODOs https://github.com/LiskHQ/lisk-desktop/search?q=todo
We should resolve all possible TODOs before the production release.

### Motivation

- Ensure feature completion
- Address open problems

**Comment by ManuGowda** [comment]
we need to group the TODOs into several issues to resolve.

**Comment by eniolam1000752** [comment]
This issue has been grouped and broken into smaller issues

- https://github.com/LiskHQ/lisk-desktop/issues/5179#issue-1807942378
- https://github.com/LiskHQ/lisk-desktop/issues/5180#issue-1807947429
- https://github.com/LiskHQ/lisk-desktop/issues/5178#issue-1807925417

**Comment by ManuGowda** [comment]
Closing this issue, as we have created multiple issues as described above.
