### ISSUE TITLE
Unable to unlock tokens using hardware wallet

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4894]
### Expected behavior

Users should be able to unlock tokens

### Actual behavior

I have a wallet with Ledger and everything works fine, voting, unvoting, sending, receiving, etc. However, unlocking tokens does not work, and I always receive an error message that the Transaction aborted on device. 

You have cancelled the transaction on your hardware wallet.( I go on locked balance > press unlock > Confirm > Error message)
However, as with the other transactions mentioned above, the ledger is not showing me the unlocking transaction on the ledger to confirm and I just receive the error message stated above.

### Steps to reproduce

All the actions should be done using hardware wallet account

- Vote a delegate
- Unvote a delegate
- Unlock tokens

### Which version(s) does this affect? (Environment, OS, etc...)
2.3.0

**Comment by przemerr** [comment]
Might not be related with the Hardware Wallet, does the account have enough balance to do the unlock transaction (>0.05 LSK)?

**Comment by ManuGowda** [comment]
> Might not be related with the Hardware Wallet, does the account have enough balance to do the unlock transaction (>0.05 LSK)?

True, I will check with the reporter. Meanwhile I am testing the flow to see if the bug exists, i should be able to unlock in few hourse.

**Comment by ManuGowda** [comment]
successfully unlocked using hardware wallet, https://testnet.liskscan.com/transaction/7daf5fe6f7f63b6ea9bda842d1e66acfdd1bf6efd60a175694b10ba8030cee26

maybe the reporter account dint had balance or something.

**Comment by ManuGowda** [comment]
For now closing this issue as invalid as I was able to successfully unlock tokens.
