### ISSUE TITLE
Updated illustrations on all empty domain states

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#4916]
### Description

- Presently, we have all the tables or lists in every domain having the same illustration images when they are in empty states.
![image](https://user-images.githubusercontent.com/32064769/231789727-184d21e1-5c85-486f-9de2-632d019e7e91.png). This should not be the case.

- Presently, when there are no nodes, the network monitor page looks weird and needs to be refactored to have a better UI when its in an empty state .
![image](https://user-images.githubusercontent.com/32064769/231791049-c83b2aac-d405-4c45-b84d-ab697588bfbd.png)

### Acceptance Criteria

- Change empty state illustrations on all domains
- Change empty state on network monitor page

### Additional Information
- All empty state illustrations would be provided by the UI/UX team.

**Comment by ManuGowda** [comment]
@eniolam1000752 can you please fix this issues as well 🙏🏼 

![Screenshot 2023-05-10 at 3 47 00 PM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/06f62410-a219-4b33-a4bc-c01a57627b5e)
