### ISSUE TITLE
The multisignature tx details view doesn't show the  tx illustration

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4932]
### Expected behavior
The details view should show the transaction illustration. It appears that the transaction moduleCommand is not calculated correctly. therefore the illustration and title are not shown correctly. 
Bear in mind that the Sender component works well because of this bug. Once the bug is fixed, we anticipate the Sender and Recipient components to have two titles (a redundant one).

### Steps to reproduce
- Add a multisig account
- Create a transaction
- Try signing the transaction as a member
- Check the details view
<img width="756" alt="Screenshot 2023-04-24 at 08 57 23" src="https://user-images.githubusercontent.com/666685/233922554-34e46983-406e-48bc-bd1f-0155e12a502e.png">

**Comment by ManuGowda** [comment]
Working as intended with latest fix

![Screenshot 2023-05-04 at 5 14 17 PM](https://user-images.githubusercontent.com/6449871/236251535-e4d1ec7b-866e-495c-ae02-aedbbaea41ce.png)
