### ISSUE TITLE
Default values when network fails

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4948]
### Expected behavior
Use - , NaN or simply show an error screen asking user to refresh.

### Actual behavior
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/8784876/234873792-fcf86460-bfcf-45ca-830e-378884e2acf2.png">

**Comment by eniolam1000752** [comment]
issue was resolved by https://github.com/LiskHQ/lisk-desktop/pull/4980#issue-1697304333
