### ISSUE TITLE
Public key doesn't show up on hover for some accounts

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#4962]
### Expected behavior

- Also enable publickey copy feature on other account page

Public key should be displayed in tooltip on hover for all accounts
![lisk-app-test-fdbk-9-a](https://user-images.githubusercontent.com/31376203/235015565-0370d78f-aa22-4fcf-85f8-344a36f072af.png)

### Actual behavior
Public key doesn't show up on hover for some accounts
![lisk-app-test-fdbk-9-b](https://user-images.githubusercontent.com/31376203/235015578-26c17905-8d14-427b-8484-b666b66e10fd.png)

 and is not returned from auth endpoint
<img width="422" alt="Screenshot 2023-04-28 at 01 07 52" src="https://user-images.githubusercontent.com/31376203/235015862-6d9062f4-ae0c-4f19-9c51-389bd88eefd8.png">

### Steps to reproduce
- Open wallet page
- Hover on account visual icon

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by eniolam1000752** [comment]
closed by PR #4956
