### ISSUE TITLE
Distorted UI on multi signature views

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5015]
### Actual behavior
- The checkmark icon is broken.
![image](https://github.com/LiskHQ/lisk-desktop/assets/32064769/8f33fda0-8926-4082-a2f1-7e98d0d5fa67)

- Distorted UI on multi signature summary page. This was observed during a staking transaction from a multi signature account.
![image](https://github.com/LiskHQ/lisk-desktop/assets/32064769/f38f6a08-2c9a-420a-8425-e3e6599d1a80)

- On staking a validator from a multi sig account. On signing the transaction and coping the transaction object, the staking queue was not cleared and because of this, switching to the other account in order to complete the transaction had the pending stakes confirmation modal shown up. Which resulted to a poor UX

### Steps to reproduce
- Click on any copy text button (the checkmark icon would be broken)
- Initiate the signing process of a staking transaction from a multi-signature account
- Try to sign the account as a member of the multi-sig group (its observe the summary page is broken and you get the confirm modal before when you try switching account to another)

**Comment by ManuGowda** [comment]
The copy action should release back to its previous state after copied.
