### ISSUE TITLE
cannot connect to the network, when not be able to do anything.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#5018]
### Expected behavior
can nott connect to the network, when should be able to select or add network.

### Actual behavior
can not do anything except try to reconnect.
![issue](https://github.com/LiskHQ/lisk-desktop/assets/44485074/ea7c724f-ccc6-4a49-b3ff-06202130c157)

### Steps to reproduce

1. Add my Lisk Service URL to the network. (e.g. http://127.0.0.1:9901)
2. Select the added network.
3. Close Lisk Desktop.
4. Stop my Lisk Service.
5. Open Lisk Desktop.

### Which version(s) does this affect? (Environment, OS, etc...)
Windows 11
v3.0.0-beta.0

**Comment by ManuGowda** [comment]
@lisknonanika you need to setup Lisk Core and Service locally for the wallet to work, otherwise it wont be able to connect.

**Comment by lisknonanika** [comment]
Of course I understand, but if a Lisk Service becomes disconnected due to a failure, I cannot even switch to another Lisk Service because this screen always opens when I open Lisk Desktop.

It is desirable to have a procedure to connect to another Lisk Service when this screen is displayed.
