### ISSUE TITLE
Unable to Add Account by Dragging & Dropping

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-desktop#5035]
![image](https://github.com/LiskHQ/lisk-desktop/assets/42899281/ba994af6-4ab9-4b57-9580-aedabfbe4a55)

### Expected behavior

Able to drag & drop the account JSON file, for example lskmz2...hggfg_personal_k3_lisk_account.json, to the desktop wallet and import it.

### Actual behavior

Unable to import an account when trying to drag & drop an account JSON file to the wallet. No response on drop action. 

### Steps to reproduce

Goto "Add new account" > "Restore from backup" > drag a .json account file to the area on the wallet and drop it.

### Which version(s) does this affect? (Environment, OS, etc...)
Tested on Windows

**Comment by ManuGowda** [comment]
Since this is a reusable component we need to check the same bug in other domains like sign multi-signature and any other places we use drag and drop
