### ISSUE TITLE
Sender in the transaction page should be clickable

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5044]
### Description

Sender in the transaction page should be clickable and navigate to senders account page
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/175c8fd2-60f3-4116-be7d-8c3715ac8a02)

### Motivation

Quality of life, the address is half hidden, you need to click through events to get the full address

### Additional Information
Currently the search bar doesn't even allow to search for regular addresses, so navigating to a specific address page is very hard

**Comment by ManuGowda** [comment]
Few more places make them clickable:

- Stakes page
- Also check `claim rewards` and `unlock stakes` pages
