### ISSUE TITLE
Unable to send transactions bigger than 100k

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5046]
### Expected behavior
User should be able to send transactions bigger than 100k
### Actual behavior
![desktop_amount](https://github.com/LiskHQ/lisk-desktop/assets/25085095/777c8f78-9feb-4e22-85be-1169fb7a4560)
### Steps to reproduce
Try sending 100k+ transaction

### Which version(s) does this affect? (Environment, OS, etc...)
Desktop 3.0-beta

**Comment by ManuGowda** [comment]
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5020
