### ISSUE TITLE
Create account (12 - 24 recovery phrase)

### ISSUE THREAD

**Issue by Ade-kola** [LiskHQ/lisk-desktop#5053]
### Description

Requesting the users to choose if they want to create a 12 phrase account or 24 phrase account at the point of account creation.

### Motivation

Please describe why it is needed

### Additional Information

Link to [figma](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=38%3A39674&t=GZGmNIDJjGPabotU-1) file.

**Comment by ManuGowda** [comment]
We have already implemented this, hence closing.
