### ISSUE TITLE
Enable Legacy account design

### ISSUE THREAD

**Issue by Ade-kola** [LiskHQ/lisk-desktop#5054]
### Description

Users should be able to enable or disable the legacy account on the "add account page", to be able to either enter the custom path or not.

### Acceptance Criteria

Please describe the conditions which must be met for this issue to close

### Additional Information
Link to [figma](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=39%3A47558&t=GZGmNIDJjGPabotU-1) file.

**Comment by ManuGowda** [comment]
This is a duplicate issue.https://github.com/LiskHQ/lisk-desktop/issues/5021
