### ISSUE TITLE
Review desktop UI designs and fix

### ISSUE THREAD

**Issue by Ade-kola** [LiskHQ/lisk-desktop#5057]
### Expected behavior

The desktop app is expected to follow the design on the figma like the spacing, font sizes , colors e.t.c

### Actual behavior

Some of the pages are looking a little off because they're not following the design on the figma file.

### Steps to reproduce

Review this task with a desktop member and fix on the go.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

**Comment by ManuGowda** [comment]
@Ade-kola please attach the screen shots of bugs for reference

**Comment by sridharmeganathan** [comment]
This issue is very generic. We will create separate issues in the future.
