### ISSUE TITLE
"See breakdown" of rewards on validator profile doesn't work

### ISSUE THREAD

**Issue by endro42** [LiskHQ/lisk-desktop#5068]
### Expected behavior

There is a rewards tile where a user has the ability to view a breakdown of these rewards.

### Actual behavior

Clicking "See breakdown" does not work

<img width="439" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/12698415/70acff7f-0724-4fb4-83d9-ac2b959a24f7">

**Comment by ManuGowda** [comment]
The /pos/validators endpoint returns the necessary information (totalCommission, totalSelfStakeRewards and earnedRewards) to show in the breakdown.

Ref: [Swagger UI](https://petstore.swagger.io/?url=https://betanet-service.lisk.com/api/v3/spec#/PoS/get_pos_validators)

Ref: [UI design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=1570-202503&t=09q4lbWy5Ya5eRNM-4)

Acceptance criteria:

- When rewards are `0`, do not show the `See breakdown >` option.
