### ISSUE TITLE
Introduce one click staking

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#5070]
### Motivation

Introduce a simple one-click staking feautre which allows users to stake their tokens with a Foundation owned validator. The exact details of the validator (i.e. the sharing percentage) are yet to be defined - community feedback appreciated.

### Tasks

TBD

**Comment by endro42** [comment]
Hi @ManuGowda, Can you give more clarification on this epic? This issue triggered quite the discussion as it will affect all validators.

**Comment by stellardynamic** [comment]
I would like to suggest a few options for one-click staking:

- Official respository system for Validator campaigns, and a way to explore it in the wallet.

- Option to one-click stake the most profitable staker. Since earning is guaranteed by the protocol now, this can be reliable.

**Comment by stellardynamic** [comment]
I would like to suggest a few options for one-click staking:

Official github repository system for Validator campaigns, and a way to explore it in the wallet.

Option to one-click stake the most profitable staker. Since earning is guaranteed by the protocol now, this can be reliable.

**Comment by stellardynamic** [comment]
I would like to suggest a few options for one-click staking:

- Official repository system for Validator campaigns, and a way to explore it in the wallet.

- Option to one-click stake the most profitable staker. Since earning is guaranteed by the protocol now, this can be reliable.

**Comment by ManuGowda** [comment]
> Hi @ManuGowda, Can you give more clarification on this epic? This issue triggered quite the discussion as it will affect all validators.

@tomploem the description is now updated for bit more clarity, meanwhile please feel free to share your feedback. This objective is for Diamond phase and not for the platform launch just so you are aware.
