### ISSUE TITLE
Stakes page should update by itself

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5074]
The "Stakes" page doesn't update itself and is not showing votes users just made. The page should update itself if a vote was removed or added. 

Reproduce: Add or remove a vote and click immediately on "Show all your stakes". You will notice that nothing changes. Users would have to go to another page and then go to their Stakes page to see the changes. It should update by itself.

Lisk Desktop 3.0.0-beta.0
Where? Validators -> Stakes

**Comment by ManuGowda** [comment]
@punkrock is this because the stake was not yet included in the block? and maybe after 10s or depending on when its included it should show?
