### ISSUE TITLE
Action buttons "edit" and "delete" lead to the same action page

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5075]
On the Stakes page: No matter if you click on the "edit" or "trash/delete" button it opens the edit button. I think you should only use the edit button and remove the trash icon or create different pop ups for each action. Why am I suggesting this? Because I clicked on the trash button and then on "confirm" because I thought the vote will be removed. Instead I just got the info that nothing is in the queue.

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/e7d18245-c8d4-44e8-af7e-6ebf4e01b5fb)

**Comment by ManuGowda** [comment]
Thanks for the suggestion @punkrock. I think we will simplify this to following

- Edit -> users can increase or decrease the stake and actions will be confirm and cancel
- Delete -> when user clicks on delete then the stake will be removed and show this view

![Screenshot 2023-06-12 at 9 05 14 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/39e110df-b73e-48b3-8355-43f63e8c3118)

What do you think?

**Comment by ManuGowda** [comment]
Since the current edit flow ensures both edit and remove stake feature, we decided to remove the trash icon to avoid the duplication.
