### ISSUE TITLE
Staking balance error should account for edit stake

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5122]
### Expected behavior
When editing a stake higher than account balance we should only show below error if the edit stake difference is higher.
In the image below i edited the stake from 220 to 230, which is only a 10 LSK difference, and my account balance contains 225 LSK which means that i can afford to edit my stake 10 LSK higher.

### Actual behavior
<img width="437" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/8784876/b03256f6-7a30-46fb-9b69-993eeab3fa05">

### Steps to reproduce
1. Have an account with for example 100 LSK
2. Stake 50 LSK with validator X
3. Send 30 LSK to random address (not this accounts address)
4. Try to edit stake with validator X to 60 LSK

**Comment by punkrock** [comment]
It's not fixed for me (for others it works). Using 3.0.0-rc.1 on Windows 11.
300,000 are already on stake, 19k+ are available. If I set stake to 310k, it shows the error.

Solution (you can thank **przemer**): Fix the issue for the page located at "Validators -> My validator profile -> Edit stake"

**Question**: Why do you have two sites? You should only have one site, no matter how I land there. It just doubles your work, or?

![bug](https://github.com/LiskHQ/lisk-desktop/assets/1260700/9c38e6aa-8a0b-49f1-bfc1-b589d8d28a73)

**Comment by ManuGowda** [comment]
The modal are same, we do not have two implementation. The data passed is wrong in profile mode, so thats the reason it's working from stakes and not in profile, it should be fixed.
