### ISSUE TITLE
Implement/reinstate missing test coverages

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5180]
### Acceptance criteria

The following files below requires some of their tests reinstated or coverage not ignored.

- src/modules/message/components/signatureCollector/index.test.js
- src/modules/token/fungible/store/actions.test.js
- src/modules/transaction/store/actions.test.js
- src/modules/transaction/utils/transaction.test.js
- src/modules/auth/components/ChooseAvatar/chooseAvatar.js
- src/modules/token/fungible/components/SendStatus/status.test.js
- src/modules/transaction/utils/hwManager/hwManager.test.js
- src/modules/wallet/components/RegisterMultisigStatus/status.test.js
- src/modules/wallet/components/signMultisigStatus/share.test.js

**Comment by ManuGowda** [comment]
We are implementing e2e tests which will improve the coverage, hence we will not handle the coverage for unit test.
