### ISSUE TITLE
Wrong tool tip description for CLI command

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5219]
There is a wrong description a CLI command. It has to be CREATE instead of GENERATE.

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/daa2a13c-2b15-4865-b5e8-721dc1f5e111)

**Comment by ManuGowda** [comment]
This bug has been resolved in beta.1 version
![Screenshot 2023-08-07 at 9 37 13 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/cff3dc28-b889-49f9-aaaa-613e5c6700ef)
