### ISSUE TITLE
Small bug findings from release v3.0

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5229]
### Expected behavior
1. ![Screenshot 2023-08-08 at 10 59 09 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/80db78e5-2317-4b0e-b6fb-c192c25f747c)
2. Allowed modals should open
3. Use metadata endpoint to search for token. Also do not show the search option when we have less than 10 token balances.
4. Do not show decimals
5. Extend the search to address and name
6. Fix the typo

### Actual behavior
1. Wallet page some items in table have duplicate dates
4. Cannot open request token modal if Lisk application is closed/open. Try to open this link when Lisk app is closed,  lisk://wallet?modal=send&recipient=lskyxq3carbt6ev86k2v2th9js5qbuewzezkz8gtv&amount=10&recipientChain=04000000. 
8. Wallet page / View all token/ Search token not working
9. Validators reporting page. Validators information graph show half validators. Show only integers.
![Screenshot 2023-08-08 at 11 12 27 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/0de33bea-bf9d-4020-8ed2-501a31881472)

10. Generators/ Validors search. Extend placeholder to be "Search for name or address"
11. Transaction monitoring page, Should be PoS Staking not Pos Staking.

**Comment by ManuGowda** [comment]
![Screenshot 2023-08-08 at 10 59 09 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/abfb2518-54a4-4d91-ab52-60f3a25b741f)

**Comment by ManuGowda** [comment]
4. Wallet page / Event section. Transaction id based filter is not working, should only show the transaction ID i filtered for (Service issue)
