### ISSUE TITLE
Update clears previous accounts in app

### ISSUE THREAD

**Issue by Ade-kola** [LiskHQ/lisk-desktop#5230]
### Expected behavior

- Copy state information while updating the app (Use electron feature to migrate the data)
- Inform user if a particular state information can not be copied

### Actual behavior

My previous account at the time of updating from version to version should remain and not cleared. If we need to clear due to protocol changes then we must inform user.

**Comment by ManuGowda** [comment]
<img width="1549" alt="Screenshot 2023-09-01 at 11 26 39 AM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/0dd6aec5-0991-4dd8-b024-252fb9c3f409">
The issues is not reproducible, following are the screen shot.
<img width="1653" alt="Screenshot 2023-09-01 at 11 24 07 AM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/5f21daf1-fdd0-4148-815b-906c91b077cf">
<img width="1655" alt="Screenshot 2023-09-01 at 11 24 19 AM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/63801002-1f21-40dc-a1ff-149606dd187f">

But we have one issue in dark mode, the update button is white colour and the text is not visible.
