### ISSUE TITLE
Misleading network description

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5233]
![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/2b5bf038-d897-4b16-8a18-37096280ac27)

This is misleading. Desktop 3.0 beta.1

**Comment by ManuGowda** [comment]
@punkrock the name of the chain was decided based on protocol and its not specified in desktop or service, so its rather based on protocol and we have to keep the chain name as it is. For all network types the lisk will be called `lisk_mainchain`.

if you have suggestions please share with us.

**Comment by punkrock** [comment]
Why isn't it just called "Lisk"? Other applications would not be called "Lisk" so there shouldn't be any duplicates.

**Comment by ManuGowda** [comment]
> Why isn't it just called "Lisk"? Other applications would not be called "Lisk" so there shouldn't be any duplicates.

It was just to make it more explicit and avoid confusion to end user to know which chain is mainchain easily, its already specified in LIP and we can't change it actually... https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#specification

**Comment by ManuGowda** [comment]
Closing the issue based on above comments.

**Comment by punkrock** [comment]
But why does it have to be this ugly? Just hardcode it as "Lisk" in Lisk Desktop. I know you grab it like lisk_mainchain from the code (or how ever it is called) but does it have to look like this in Lisk Desktop? Pretty sure there are ways to show it like "Lisk" instead of "lisk_mainchain" without really changing anythink in the codebase.
