### ISSUE TITLE
Punished delegates don't show up in the sanctioned section

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5243]
### Expected behavior
A punished delegate should be shown in the sanctioned section
### Actual behavior
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/01f7bd02-a018-4dd9-adfd-fe3447973005)
delegate named `pom` should be visible there

### Steps to reproduce
Go to Lisk Desktop, connect with betanet, go to validators page and sanctioned section
### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop-beta.1

**Comment by przemerr** [comment]
probably due to https://github.com/LiskHQ/lisk-service/issues/1786

**Comment by ManuGowda** [comment]
> 

Yes, from desktop side the query and logic exists to show the punished or banned validators.. so I will close this issue in favour of service issue.

**Comment by ManuGowda** [comment]
Lisk Desktop handles the filtering logic, since service returns status of `pom` validator as `standby` the results are not appeared in `sanctioned` https://github.com/LiskHQ/lisk-service/issues/1786
