### ISSUE TITLE
Fee estimate UI/UX modification

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5247]
### Description

There is a need to modify the user experience and user interface of the fee viewer.

## Acceptance criteria
- On all transaction forms(i.e TxComposer), the fee viewer section should be collapsable (shrunk by default) and the fee estimate endpoint should only be invoked when the user decides to shrink it.

- On clicking the `Continue to summary` button on the transaction form page, the fee estimate endpoint should be invoked and the fee computed. This means, the fee value should be displayable on the summary page but this time, it should not be collapsable.

- When a user returns to the form modal from the summary page, the fee viewer should still be shrunk.

**Comment by ManuGowda** [comment]
Resolve by https://github.com/LiskHQ/lisk-desktop/issues/5241
