### ISSUE TITLE
Link navigation creates new instance of application

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#5294]
### Expected behavior

Link navigation should not create new instance of application

### Actual behavior

<img width="1631" alt="Screenshot 2023-09-05 at 10 44 14 AM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/518710e1-c1a7-41d9-b1ae-d74f69f01219">

### Steps to reproduce

- Click on any links i.e transaction row, blocks row, etc..
- Observe a new window is created

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

**Comment by oskarleonard** [comment]
Closing this since this is default behaviour of electron, some users might use it to open two instances.
