### ISSUE TITLE
Cannot request token on betanet

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5313]
### Expected behavior
Should be able to request token. Strangely enough it seems to work on devnet

### Actual behavior
<img width="775" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/8784876/145a7194-2427-49bd-a21a-ffc71216c938">

**Comment by ManuGowda** [comment]
Lisk service latest fix were not deployed on betanet, hence we have the issue, however on devnet you can cross check the issue is resolved.
