### ISSUE TITLE
Wrong delegate under staking button

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5323]
### Actual behavior

![wrong_delegate](https://github.com/LiskHQ/lisk-desktop/assets/25085095/127ab37f-fe8d-4c90-9d2b-0b33c236f020)

Desktop 3.0.0-rc.0

**Comment by ManuGowda** [comment]
![Screenshot 2023-09-18 at 3 23 27 PM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/6b60e15a-1bec-4c35-bd7c-9357d4f42f2f)


@przemerr I am unable to reproduce this issue, can you share me steps?

**Comment by ManuGowda** [comment]
![Screenshot 2023-09-18 at 3 24 21 PM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/ec709437-21c0-47b5-aa12-0935eb044d3c)

Reference from betanet as well.

**Comment by ManuGowda** [comment]
![Screenshot 2023-09-18 at 3 31 04 PM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/b121ca28-e9f8-45a9-ad56-592862084a59)

**Comment by przemerr** [comment]
Hi @ManuGowda ,
It only applies to betanet,
you need to have a delegate of your own
you need to explicitly go to Validators Tab, and My Validator profile (don't search for a delegate) and stake from there
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/f6774bb3-809e-4cc8-87f7-1cd90ff5e19f)

**Comment by przemerr** [comment]
@ManuGowda can you reproduce it?

**Comment by ManuGowda** [comment]
> @ManuGowda can you reproduce it?

Yes was able to reproduce 👍🏼
