### ISSUE TITLE
Transaction signing regression

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-desktop#5340]
### Expected behavior
Being given the ability to immediately sign a transaction with a second multisig passphrase, just like in the current version (v2.3.0).

### Actual behavior
A window is shown to download the transaction, without an option to sign it with another passphrase instead.

### Steps to reproduce
1. Create a transaction
2. Sign it with your password

### Which version(s) does this affect? (Environment, OS, etc...)
Version 3.0.0-rc.1

**Comment by ManuGowda** [comment]
@Lemii we removed the overall ability to have second passphrase as it was a legacy feature.. with new account management you can add as many accounts in account management as it involves encryption etc..

- Add both accounts
- Initiate from account 1, download
- Switch to account2 and sign and broadcast

This should help?

**Comment by Lemii** [comment]
> @Lemii we removed the overall ability to have second passphrase as it was a legacy feature.. with new account management you can add as many accounts in account management as it involves encryption etc..
> 
> * Add both accounts
> * Initiate from account 1, download
> * Switch to account2 and sign and broadcast
> 
> This should help?

I'm familiar with the workflow of signing a multisig transaction with multiple accounts using the download function, however it is much less user-friendly than being able to sign it immediately. 

Even though it is considered a 'legacy feature' now, please bare in mind that there are a great number of users coming from the old version that are using a multisig account. It might be worth reconsidering reverting the removal of this feature.

**Comment by lisknonanika** [comment]
Can you have the following flow only if the user required to sign is added in the wallet?
![image](https://github.com/LiskHQ/lisk-desktop/assets/44485074/3c967490-f736-48b2-aba8-52a5667e6c7b)

**Comment by oskarleonard** [comment]
# Continuous flow for signing a multi-signature transaction

When this state is true:
1. Wallet: [MultiSigAccount1, MultiSigAccount2]
2. MultiSigAccount1 requires signature from MultiSigAccount2

And a user tries to sign a transaction from MultiSigAccount1 there should be a continuous flow to signing with MultiSigAccount2. Refer to [this design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=8127%3A323656&mode=design&t=miMR5nZGwBfIm8fp-1) for the flow.
