### ISSUE TITLE
Terminology consistency

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5344]
The terminology on the validators page is a bit confusing and not consistent.

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/42d3af50-6cb3-4ad4-a03e-a5d6709e516e)

**Comment by ManuGowda** [comment]
IMO the current terminology is valid? not all validators are generators, but all generators are validators?

so we use consistently validators everywhere and then the tabs are only a representation of that subset.

Maybe for the generators tab table header we can rename `Validator => Generator` and `Validator weight => Generator weight`?
