### ISSUE TITLE
Give "claim rewards" an additional prominent positioning

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5346]
I opened Lisk Desktop 3.0.0-rc.1 and had no clue where I can claim my rewards. I found it at "Validators -> Stake -> Claim rewards" after asking people on Discord. If people who are here since many years have a hard time to find how to claim rewards, the regular user will it have even harder.

I think that for the most users sending LSK and claiming rewards are the most important things they will do with the Wallet, so please make "claim rewards" easily accessible.

My suggestion: Add the button also to the "Wallet" page right beside "Request" and "Send".

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/99c8d464-f592-46a6-a02a-92594305fc1b)

**Comment by punkrock** [comment]
I just downloaded 3.0.0-rc.2
Where is the button?!

**Comment by przemerr** [comment]
it's not included in this release
it's in this sprint https://github.com/LiskHQ/lisk-desktop/milestone/142
