### ISSUE TITLE
Add tooltip for multi-signature symbol

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5363]
Please add a tooltip for the two-keys-symbol.

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/8dd2ab39-3b73-474b-8745-a7b185e7755c)

Also consider the same for:
- Hardware wallet icon
- Validator icon

**Comment by ManuGowda** [comment]
@punkrock I think adding tooltip icon defeats the purpose of icon? ideally the icon should give users an idea about what it is? we can also check if there is a better icon to use for multisig, not sure about tooltip though.

@ann-vashchenko @Ade-kola what do you guys think about this suggestion?

**Comment by punkrock** [comment]
@ManuGowda You should not change the icon. You should add a tooltip (description) to it if a user hovers with the mouse that explains what the icon means.

**Comment by ann-vashchenko** [comment]
@ManuGowda It's a good point to add the tooltip here. We use tooltips for the icons at the top menu because they don't have labels, so the same should be done with the multisignature icon.

**Comment by Ade-kola** [comment]
@ManuGowda we can use the hover effect for the key like we use in showing public keys before. So when users hover on the key, we can show what it means.

**Comment by ManuGowda** [comment]
Thanks for all the inputs @punkrock @ann-vashchenko @Ade-kola , then lets add necessary tooltips for all the icons 🙏🏼
