### ISSUE TITLE
Claim rewards button issue if nothing is claimable

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5382]
3.0.0-rc.2

If no rewards to claim it shows this:

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/a4ef18fe-3efd-41c1-8cf0-a93959e852f2)

**Comment by ManuGowda** [comment]
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5377, hence closing
