### ISSUE TITLE
Upgrade react-query to V5

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5402]
### Description

Upgrade react-query to version 5. A lot of breaking changes has been introduced, but also a lot of improvements. Fortunately they have also realsed an [eslint](https://tanstack.com/query/v4/docs/react/eslint/prefer-query-object-syntax) tool to help with this migration. 

TODO:
1. [Read overview notes](https://tanstack.com/blog/announcing-tanstack-query-v5)
2. Install Eslint tool
3. Replace all renamed variables, for us the most used on is probably the rename of `loading` to `pending`
4. Verify that useQuery and Infinite Queries are working. Infinite Queries has received a major upgrade which lets us fetch multiple pages at once. 

### Motivation

- React-query is one of our core tools so we need to make sure to not fall behind react-query upgrades to much. 

### Additional Information

[Quick Migration overview](https://tanstack.com/blog/announcing-tanstack-query-v5)

**Comment by ManuGowda** [comment]
This is huge breaking change and at this point we wont be able to include for the major release, hence closing.
