### ISSUE TITLE
Sender/Recipient logic in the transaction page

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5419]
### Expected behavior
The transactions table should show a correct recipient/sender
### Actual behavior
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/0aaada34-fbbe-4cdf-80f4-5b78fa4c7302)
It seems like the recipient column (`lskw7488a9nqy6m3zkg68x6ynsp6ohg4y7wazs3mw`) always shows a sender, for the best UI experience:

- in case of an outgoing transaction it should show the recipient,
- in case of an incoming transaction it should show the sender

or just show both in any case.

Additionally (I don't want to create a new github issue) it would be nice if the transaction detail page would show the recipient if there's any, currently you need to expand the parameters to see it.

![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/ce86e719-be88-4399-9fbf-696bba4ccd0a)

**Comment by ManuGowda** [comment]
Thank you @przemerr for the feedback.. in the wallet page we can show the `Sender` but adding `Recipient` would make the table congested and on a small screen it would look bad.

However, for the details page we will add the `Recipient` that should be good enough?

Also note, not all transactions have `Recipient` and we wanted this table to be generic for all types of sidechain applications.

If lets say a sidechain ABC has different types of modules with different properties then the wallet wont be able to show them generically, hence balancing the fields to display.

**Comment by przemerr** [comment]
Hi @ManuGowda my point for the transaction list is that, if i browse for example my account.. i want to quickly see from were the transaction is coming from or were was it sent

Lisk Desktop v2 does exactly this:

- in case of an outgoing transaction it shows the recipient,
- in case of an incoming transaction it shows show the sender

and v3 always shows the sender (and obviously I'm the sender if I'm browsing my account), so you have to pretty much always click the transaction to see were you sent it, I understand the wallet has to be compatible with different chains, but still it's a regression. If there's no recipient just leave it empty, or have `N/A` graphic If nothing can be done about it, it's fine, I'm just pointing out that Desktop v2 had the correct logic.

As for the details page adding `Recipient` is fine :), but i see it also misses the `amount/value` so if it's not a problem it would be good to have it also there.

Thanks for taking the feedback into consideration 🙏
