### ISSUE TITLE
Update progress bar reaching 100% and goes back and repeats

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5420]
Lisk Desktop 3.0.0-rc3

I just updated from Lisk Desktop 3.0.0-rc2 to Lisk Desktop 3.0.0-rc3 and I noticed that the "download in progress" bar once it reached 100% it went back to 30% or something and then up to 100%. After it "circled" once I was able to "Restart the app". Tested only once but seems like a bug.

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/91a7ef7e-d52c-4c38-bd0f-0e12c658e533)

**Comment by ManuGowda** [comment]
@punkrock the whole download logic is controlled by the electron auto updater, so we do not have any control over this, hence if this is a bug we have to report in electron as it impacts in general and we wont be able to make any fixes for this.

If you are ok with this, I will close this issue? or you can move the issue to electron repo?

**Comment by punkrock** [comment]
@ManuGowda Ok, close it. On next update I will record it and open an issue in the Electron repo. EDIT: I just updated again from rc2 to rc3 and this time it worked as expected.

**Comment by przemerr** [comment]
@punkrock if you want to redownload the update through the wallet to capture the behavior delete the folder 
`C:\Users\<your username>\AppData\Local\lisk-desktop-updater` if you're on windows
