### ISSUE TITLE
Signing a message takes forever

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5425]
### Expected behavior
A user should be able to sign a message

### Actual behavior
I am unable to sign a message because it takes too long even after 5mins I was still unable to sign a simple text

### Steps to reproduce
- Navigate to the sign message page
- Try to sign a message after providing a password

**Comment by JesusTheHun** [comment]
@ManuGowda I'm still experiencing the issue with Lisk Desktop `v3.0.0-rc.3` on MacOS Somona 14.0 on Apple Silicon.
Check the video at 30:18
