### ISSUE TITLE
Need to Close "Transaction Signature Successful" Modal to Initiate New Transaction from blockchain application

### ISSUE THREAD

**Issue by RaphaelCornelis** [LiskHQ/lisk-desktop#5470]
### Actual behavior
In the Lisk Desktop application, after completing a transaction through a dApp, a modal appears indicating "Transaction signature successful". Users are required to manually close the modal to be able to proceed with a new transaction. This behavior interrupts the user experience and could potentially confuse or hinder users from performing multiple transactions seamlessly.

### Steps to reproduce
- Complete a transaction.
- Observe the "Transaction signature successful" modal.
- Attempt to initiate a new transaction without closing the modal.

### Which version(s) does this affect? (Environment, OS, etc...)
V3.0.0-rc.4

**Comment by ManuGowda** [comment]
@RaphaelCornelis could you please add the `Expected behavior`?

**Comment by ManuGowda** [comment]
I guess you have expressed the expected behaviour in this issue https://github.com/LiskHQ/lisk-desktop/issues/5469, shall we consider the same?
