### ISSUE TITLE
Error message and UX when signing with a wrong ledger

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5503]
### Expected behavior
Give user a better hint when they try to sign a hw account with the wrong ledger

### Actual behavior
https://github.com/LiskHQ/lisk-desktop/assets/8784876/71a3e1de-7471-4958-8c53-e4cec9f4d338

### Steps to reproduce
1. Import Account 1 from Ledger_1
2. Remove ledger_1 and connect Ledger_2
3. Try to send tokens from Account 1 and follow the flow with Ledger_2

**Comment by ManuGowda** [comment]
The transaction is signed from wrong ledger, as a work around the user needs to connect to correct device and import the account and sign.
