### ISSUE TITLE
Legacy checks should only be invoked when the current chain is the lisk main chain

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5504]
### Expected behavior
legacy account checks should only be invoked when the present chain is the lisk main chain.

### Actual behavior
Legacy accounts checks are invoked on every switch to any chain

### Steps to reproduce
- Open up the dev tools and navigate to networks
- switch the current chain to a side chain.
- It would be observed that an api call to legacy is invoked

### Which version(s) does this affect? (Environment, OS, etc...)
v3.0.0

**Comment by ManuGowda** [comment]
Changing this logic might introduce regression, currently its not causing any harm hence we would leave the check as it is.
