### ISSUE TITLE
Fiat value isn't displayed even though on the token balance fiat value is displayed

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5510]
### Expected behavior
- I should be able to see the fiat value of the rewards I am about to claim.

### Actual behavior
- Fiat value remains a zero value
- Value is seen as approximately zero because the fiat value is too small it can be represented in a 2 decimal place.

![image](https://github.com/LiskHQ/lisk-desktop/assets/32064769/6a046a8d-60cd-41a3-a16a-dc294890fbfc)

### Steps to reproduce
- Initiate a claim rewards flow.
- It would be seen that you can see the token to be claimed but the fiat value is approximately 0 possible because the fiat value is too small it is approximately equal to zero

**Comment by ManuGowda** [comment]
Since its limited to two decimal and the value is too low its not showing..

other cases its shows when value bit higher

![Screenshot 2023-11-30 at 3 30 24 PM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/5ae8d6f0-4603-4557-9e9b-d5f5193a1d02)
