### ISSUE TITLE
Improve user experience when blockchain client or service is indexing

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#5524]
### Description

Currently, we show a toaster to let users know that blockchain client is syncing or service is indexing.
However from user experience point of view this is not very good, as the basic users might not get to know why the wallet is not functioning.

### Motivation

- Provide a clear guidance or information to end users when blockchain client or service is indexing
- Since blockchain information is not up to date the users should not use the functionality until its fully index and synced up
- Users should be guided for next steps

### Additional information

Current approach
<img width="1418" alt="Indexin status" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/52920546-b24f-4401-a870-e6b82b92530d">

**Comment by Ade-kola** [comment]
@ManuGowda I thought wer discussed about indexing some days ago and talked about using this [design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=4430%3A324494&mode=design&t=g62fVib4RBr6YtOZ-1) instead, or am I mistaken?
