### ISSUE TITLE
Changing self-stake crashes wallet page

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5526]
Lisk Desktop 3.0.0

I changed my self-stake and it crashed the wallet page. It doesn't come back, even if I switch accounts. Only a restart of Lisk Desktop helps.

Error:
```
TypeError: Cannot read properties of undefined (reading 'timestamp'):

 in h
 in a
 in ForwardRef
 in ForwardRef
 in j
 in withI18nextTranslation(j)
 in withI18nextTranslation(j)
 in A
 in u
 in D
 in div
 in BoxContent
 in div
 in Box
 in O
 in div
 in BoxContent
 in div
 in Box
 in section
 in E
 in T
 in t
 in ErrorBoundary
 in withI18nextTranslation(ErrorBoundary)
 in main
 in j
 in t
 in div
 in j
 in withRouter(j)
 in b
 in section
 in main
 in section
 in a
 in div
 in Unknown
 in Connect(Component)
 in I
 in D
 in Q
 in withRouter(Q)
 in E
 in t
 in t
 in O
 in t
 in u
 in Unknown
```

![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/2adbfaf5-65e0-4c87-9d81-4039bbdc5e53)

**Comment by ManuGowda** [comment]
@punkrock i just tested on testnet.. it worked without any issues..

on mainnet its difficult to test for me.. can you check once on testnet? so that we can get to know the problem

**Comment by oskarleonard** [comment]
@ManuGowda I was able to replicate on Testnet. 
@punkrock No need to test on Testnet.
