### ISSUE TITLE
Claiming rewards when multiple stakes

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5531]
### Expected behavior
Should work to claim rewards when having multiple stakes

### Actual behavior
Claiming rewards doesn't work account having multiple stakes: it does not show the claimable rewards and does not let me click the claim option.. In contrast, while having staked only with one validator, everything works fine.

<img width="1389" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/8784876/6b80589f-2c30-409f-a523-50efa4db638d">

### Steps to reproduce
1. Stake for 2 or more validators
2. Wait until Claim Rewards button is enabled
3. Expected: User should see claimable rewards in the modal

**Comment by przemerr** [comment]
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/0461f33f-d52f-4884-bc2a-3b96d2b77218)

works on my end testnet/mainnet, maybe a specific validator is triggering the bug

**Comment by ManuGowda** [comment]
@oskarleonard can you cross check the issue?

Worked for me too.

<img width="970" alt="Screenshot 2023-12-12 at 2 11 33 PM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/1b916b44-9d97-40bc-ba37-bcb68ecef966">
