### ISSUE TITLE
Clicking stake button from validators list

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#5532]
### Expected behavior
When i click the stake button from validator list it should go to that validator and open the staking modal for that validator.

### Actual behavior
https://github.com/LiskHQ/lisk-desktop/assets/8784876/ae86bad6-f964-4ad7-af5a-3390a03cdebb

### Steps to reproduce
See actual behavior

**Comment by ManuGowda** [comment]
@oskarleonard this issue also worked for me
