### ISSUE TITLE
Switching to a different Mainchain lisk-service node doesn't work

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5555]
### Expected behavior
The desktop should use the new service node URL when querying for data
### Actual behavior
The desktop queries with https://service.lisk.com URL event if there's a different mainchain service selected
### Steps to reproduce

- Add a different mainchain Lisk service node, to the wallet, for example:
   https://mainnet-service.lemii.dev/ or https://mainnet-service.liskscan.com,
- Switch to one of them,
- Check console and the URLs used for querying 

### Which version(s) does this affect? (Environment, OS, etc...)
Desktop 3.0.1

**Comment by ikem-legend** [comment]
This issue was tied to a service configuration issue on the stated URLs. Therefore I'll be closing it
