### ISSUE TITLE
I can't unvote grumlin@temp

### ISSUE THREAD

**Issue by Grum1in** [LiskHQ/lisk-desktop#5563]
### Expected behavior
Just unvote, that's all :)
### Actual behavior
I can't unvote it, maybe because it contains "@" and Lisk Desktop don't understand it, or something else
<img width="557" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/18610794/59479583-219c-4fab-8a66-6c0461884801">
### Steps to reproduce
just try to unvote, you will get this error
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.2

**Comment by przemerr** [comment]
@Grum1in this is not a bug, there's a limit of 20 pending unlocks, you just need to wait for your other stakes to be ready for unlocking

**Comment by Grum1in** [comment]
> @Grum1in this is not a bug, there's a limit of 20 pending unlocks, you just need to wait for your other stakes to be ready for unlocking

thank you, close issue
