### ISSUE TITLE
Implement hardware wallet claim message signing for WalletConnect

### ISSUE THREAD

**Issue by ikem-legend** [LiskHQ/lisk-desktop#5574]
### Description

In order to carry out the token claim on Layer 2, along with regular users, hardware wallet users should also be able to sign the token claim message via WalletConnect.

### Acceptance Criteria

- Hardware wallet users should be able to sign claim messages
- Hardware wallet users should be able to sign regular messages

**Comment by Lemii** [comment]
This functionality is required for the Colecti refund process. They set a strict deadline after which you're not able to receive your refund any more, so pushing this update _might_ be worth giving priority.
