### ISSUE TITLE
Transaction tab errors

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#5589]
![walletError](https://github.com/LiskHQ/lisk-desktop/assets/25085095/c56fb457-bc07-4c93-a361-81b8dd71ddba)
note: there was a pending transaction during the error
![image](https://github.com/LiskHQ/lisk-desktop/assets/25085095/3c9b97a7-ea1c-46a0-972b-bca732ba815c)

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop 3.0.2 Windows

**Comment by shuse2** [comment]
it seems like it's working for me 🤔 

![Screenshot 2024-05-21 at 09 54 29](https://github.com/LiskHQ/lisk-desktop/assets/2367565/d396fee5-80ab-462e-ab0a-92109d1c4386)

**Comment by przemerr** [comment]
can you test with a pending transaction in the txpool?
