### ISSUE TITLE
Support private key import

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-desktop#5593]
### Description

Add support for importing private key into the Desktop wallet
https://www.reddit.com/r/Lisk/comments/1cynzx0/lisk_l1_wallet_private_key_import/

### Motivation

In order to allow migrating from account which were managed by other wallets than Lisk Desktop, we should support importing `private key` directly to the Lisk Desktop

**Comment by roccomuso** [comment]
This would be helpful 💯

**Comment by przemerr** [comment]
if someone can't wait for the official release I made a simple tool, that lets you import the private key using the import from JSON backup
there's also an .exe version in the releases
https://github.com/przemerr/exodusRecovery

use at your own risk
